### ISSUE TITLE
hello world runs without error on cromwell 36. on cromwell 37 if tinishes but throws several exceptions

### ISSUE THREAD

**Issue by wresch** [broadinstitute/cromwell#4626] opened 2019-02-11 15:24 UTC
Running on a Local backend with `java -jar $CROMWELL_JAR run -i input.json wf.wdl`

```
task hello {
    String outfilename
    String ? name

    command {
        echo "Hello ${default='world' name}" > ${outfilename}
    }
    output {
        File out = "${outfilename}"
    }
}

workflow test1 {
    String name

    call hello {
        input: outfilename="${name}.txt", name = "${name}"
    }
}
```

Using default configuration.

Output:
```
[2020-02-11 10:13:03,33] [info] Running with database db.url = jdbc:hsqldb:mem:89c116e0-5bca-4467-aaff-ae492c2ebbaf;shutdown=false;hsqldb.tx=mvcc
[2019-02-11 10:13:14,71] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2019-02-11 10:13:14,75] [info] [RenameWorkflowOptionsInMetadata] 100%
[2019-02-11 10:13:15,05] [info] Running with database db.url = jdbc:hsqldb:mem:6b5d8035-4932-4680-b912-34885765f705;shutdown=false;hsqldb.tx=mvcc
[2019-02-11 10:13:15,63] [info] Slf4jLogger started
[2019-02-11 10:13:16,02] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-1ddecb5",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2019-02-11 10:13:16,08] [info] Metadata summary refreshing every 2 seconds.
[2019-02-11 10:13:16,20] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-02-11 10:13:16,23] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-02-11 10:13:16,25] [warn] 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)
[2019-02-11 10:13:16,26] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2019-02-11 10:13:16,33] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2019-02-11 10:13:17,45] [info] SingleWorkflowRunnerActor: Version 37
[2019-02-11 10:13:17,46] [info] SingleWorkflowRunnerActor: Submitting workflow
[2019-02-11 10:13:17,59] [info] Unspecified type (Unspecified version) workflow 52999e15-953f-44d6-aaae-1774c74d2910 submitted
[2019-02-11 10:13:17,65] [info] SingleWorkflowRunnerActor: Workflow submitted 52999e15-953f-44d6-aaae-1774c74d2910
[2019-02-11 10:13:17,65] [info] 1 new workflows fetched
[2019-02-11 10:13:17,66] [info] WorkflowManagerActor Starting workflow 52999e15-953f-44d6-aaae-1774c74d2910
[2019-02-11 10:13:17,67] [info] WorkflowManagerActor Successfully started WorkflowActor-52999e15-953f-44d6-aaae-1774c74d2910
[2019-02-11 10:13:17,67] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2019-02-11 10:13:17,70] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2019-02-11 10:13:17,91] [info] MaterializeWorkflowDescriptorActor [52999e15]: Parsing workflow as WDL draft-2
[2019-02-11 10:13:19,06] [info] MaterializeWorkflowDescriptorActor [52999e15]: Call-to-Backend assignments: test1.hello -> Local
[2019-02-11 10:13:19,22] [info] Request threw an exception on attempt #1. Retrying after 269 milliseconds
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:301)
        at sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:209)
        at org.http4s.blaze.channel.nio2.ClientChannelFactory.connect(ClientChannelFactory.scala:36)
        at org.http4s.client.blaze.Http1Support.buildPipeline(Http1Support.scala:53)
        at org.http4s.client.blaze.Http1Support.$anonfun$makeClient$1(Http1Support.scala:45)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.run(Callback.scala:127)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
        at cats.effect.Async$$anon$1.run(Async.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2019-02-11 10:13:19,49] [info] Request threw an exception on attempt #2. Retrying after 1364 milliseconds
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:301)
        at sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:209)
        at org.http4s.blaze.channel.nio2.ClientChannelFactory.connect(ClientChannelFactory.scala:36)
        at org.http4s.client.blaze.Http1Support.buildPipeline(Http1Support.scala:53)
        at org.http4s.client.blaze.Http1Support.$anonfun$makeClient$1(Http1Support.scala:45)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.run(Callback.scala:127)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
        at cats.effect.Async$$anon$1.run(Async.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2019-02-11 10:13:20,86] [info] Request threw an exception on attempt #3. Retrying after 6737 milliseconds
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:301)
        at sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:209)
        at org.http4s.blaze.channel.nio2.ClientChannelFactory.connect(ClientChannelFactory.scala:36)
        at org.http4s.client.blaze.Http1Support.buildPipeline(Http1Support.scala:53)
        at org.http4s.client.blaze.Http1Support.$anonfun$makeClient$1(Http1Support.scala:45)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.run(Callback.scala:127)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
        at cats.effect.Async$$anon$1.run(Async.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2019-02-11 10:13:21,51] [info] WorkflowExecutionActor-52999e15-953f-44d6-aaae-1774c74d2910 [52999e15]: Starting test1.hello
[2019-02-11 10:13:22,36] [info] Assigned new job execution tokens to the following groups: 52999e15: 1
[2019-02-11 10:13:22,66] [info] BackgroundConfigAsyncJobExecutionActor [52999e15test1.hello:NA:1]: echo "Hello World" > World.txt
[2019-02-11 10:13:22,75] [info] BackgroundConfigAsyncJobExecutionActor [52999e15test1.hello:NA:1]: executing: /usr/bin/env bash /spin1/users/wresch/test_data/cromwell/test1/cromwell-executions/test1/52999e15-953f-44d6-aaae-1774c74d2910/call-hello/execution/script
[2019-02-11 10:13:26,29] [info] BackgroundConfigAsyncJobExecutionActor [52999e15test1.hello:NA:1]: job id: 12910
[2019-02-11 10:13:26,30] [info] BackgroundConfigAsyncJobExecutionActor [52999e15test1.hello:NA:1]: Status change from - to Done
[2019-02-11 10:13:27,61] [info] Request method=GET uri=https://auth.docker.io/token?service=registry.docker.io&scope=repository%3Alibrary/ubuntu%3Apull headers= threw an exception on attempt #4. Giving up.
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:301)
        at sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:209)
        at org.http4s.blaze.channel.nio2.ClientChannelFactory.connect(ClientChannelFactory.scala:36)
        at org.http4s.client.blaze.Http1Support.buildPipeline(Http1Support.scala:53)
        at org.http4s.client.blaze.Http1Support.$anonfun$makeClient$1(Http1Support.scala:45)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.run(Callback.scala:127)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
        at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
        at cats.effect.Async$$anon$1.run(Async.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2019-02-11 10:13:27,63] [info] Message [cromwell.docker.DockerInfoActor$DockerInfoFailedResponse] from Actor[akka://cromwell-system/user/HealthMonitorDockerHashActor#-638598959] to Actor[akka://cromwell-system/deadLetters] was not delivered. [1] dead letters encountered, no more dead letters will be logged. If this is not an expected behavior, then [Actor[akka://cromwell-system/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2019-02-11 10:13:27,65] [info] WorkflowExecutionActor-52999e15-953f-44d6-aaae-1774c74d2910 [52999e15]: Workflow test1 complete. Final Outputs:
{
  "test1.hello.out": "/spin1/users/wresch/test_data/cromwell/test1/cromwell-executions/test1/52999e15-953f-44d6-aaae-1774c74d2910/call-hello/execution/World.txt"
}
[2019-02-11 10:13:27,69] [info] WorkflowManagerActor WorkflowActor-52999e15-953f-44d6-aaae-1774c74d2910 is in a terminal state: WorkflowSucceededState
[2019-02-11 10:13:35,97] [info] SingleWorkflowRunnerActor workflow finished with status 'Succeeded'.
{
  "outputs": {
    "test1.hello.out": "/spin1/users/wresch/test_data/cromwell/test1/cromwell-executions/test1/52999e15-953f-44d6-aaae-1774c74d2910/call-hello/execution/World.txt"
  },
  "id": "52999e15-953f-44d6-aaae-1774c74d2910"
}
[2019-02-11 10:13:36,30] [info] Workflow polling stopped
[2019-02-11 10:13:36,32] [info] Shutting down WorkflowStoreActor - Timeout = 5 seconds
[2019-02-11 10:13:36,33] [info] Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
[2019-02-11 10:13:36,34] [info] Aborting all running workflows.
[2019-02-11 10:13:36,34] [info] WorkflowStoreActor stopped
[2019-02-11 10:13:36,34] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2019-02-11 10:13:36,34] [info] JobExecutionTokenDispenser stopped
[2019-02-11 10:13:36,34] [info] WorkflowLogCopyRouter stopped
[2019-02-11 10:13:36,35] [info] Shutting down WorkflowManagerActor - Timeout = 3600 seconds
[2019-02-11 10:13:36,35] [info] WorkflowManagerActor All workflows finished
[2019-02-11 10:13:36,35] [info] WorkflowManagerActor stopped
[2019-02-11 10:13:36,78] [info] Connection pools shut down
[2019-02-11 10:13:36,78] [info] Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
[2019-02-11 10:13:36,78] [info] Shutting down JobStoreActor - Timeout = 1800 seconds
[2019-02-11 10:13:36,78] [info] SubWorkflowStoreActor stopped
[2019-02-11 10:13:36,78] [info] JobStoreActor stopped
[2019-02-11 10:13:36,78] [info] Shutting down CallCacheWriteActor - Timeout = 1800 seconds
[2019-02-11 10:13:36,78] [info] Shutting down ServiceRegistryActor - Timeout = 1800 seconds
[2019-02-11 10:13:36,78] [info] Shutting down DockerHashActor - Timeout = 1800 seconds
[2019-02-11 10:13:36,78] [info] Shutting down IoProxy - Timeout = 1800 seconds
[2019-02-11 10:13:36,78] [info] CallCacheWriteActor Shutting down: 0 queued messages to process
[2019-02-11 10:13:36,78] [info] CallCacheWriteActor stopped
[2019-02-11 10:13:36,78] [info] IoProxy stopped
[2019-02-11 10:13:36,79] [info] WriteMetadataActor Shutting down: 0 queued messages to process
[2019-02-11 10:13:36,79] [info] DockerHashActor stopped
[2019-02-11 10:13:36,79] [info] KvWriteActor Shutting down: 0 queued messages to process
[2019-02-11 10:13:36,80] [info] ServiceRegistryActor stopped
[2019-02-11 10:13:36,80] [info] Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
[2019-02-11 10:13:36,80] [info] Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
[2019-02-11 10:13:36,81] [info] Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
[2019-02-11 10:13:36,84] [info] Database closed
[2019-02-11 10:13:36,84] [info] Stream materializer shut down
[2019-02-11 10:13:36,84] [info] WDL HTTP import resolver closed

```

**Comment by danbills** [comment] 2019-02-11 15:57
@wresch Looks like you are having DNS resolution issues.  \

Can you resolve the endpoint per the error message?
 `nslookup https://auth.docker.io/token`

**Comment by wresch** [comment] 2019-02-11 16:28
Thanks for the response @danbills - this is on a compute node which only has access to the outside network through an http(s)/ftp proxy so it can't do name resolution for outside addresses.  Why does cromwell try to resolve that particular address? We don't have docker available and I tried with a config file that only defines a local and slurm backend and still get the same exceptions.

**Comment by mcovarr** [comment] 2019-02-11 17:24
I reproduced the problem locally. The problem is our default health monitor `StandardHealthMonitorServiceActor` which periodically tries to ping Docker Hub. I'm not sure what changed between 36 and 37 that this now manifests when previously it did not. There is a `cromwell.services.healthmonitor.impl.noop.NoopHealthMonitorServiceActor` that one should be able to swap in to turn off health monitoring, but unfortunately there's a bug in the 37 version of this class that causes it to crash during initialization.

As you've noticed the workflow still runs successfully albeit with a lot of noise, we'll try to come up with a more satisfactory resolution.

**Comment by wresch** [comment] 2019-02-11 18:18
Alright. Thanks.

**Comment by aednichols** [comment] 2019-03-27 21:46
Since we merged a PR intended to address this issue, closing as presumed-fixed

**Closed by aednichols** 2019-03-27 21:46 UTC
Labels: Needs Triage
