### ISSUE TITLE
CLI improvements: usage message and behavior

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#1939] opened 2017-02-01 21:40 UTC
- [ ] Usage message
  - Update the usage message to better describe how to use the commands

- [ ] Parameters
   - Switch from positional parameters to parameter arguments so that users explicitly include inputs and other parameters (workflow options, metadata, imports, lables, etc).
   - Make all parameters optional, so if a user doesn't include the parameter argument, then no error.
   - Get rid of functionality that Cromwell looks for files with specific extensions, like `.imputs`, `.options`, etc.

To Be Continued.

**Comment by kcibul** [comment] 2017-02-02 02:15
Great ticket!

**Comment by katevoss** [comment] 2017-04-14 13:57
From @ruchim, suggestion for the usage message:

```
run <WDL file> [<workflow inputs file>] [<workflow options file>] [<workflow metadata output path>] [<WDL zip file>] [<labels file>]

WDL file - WDL file that contains primary workflow to be run. Required

Inputs file - JSON file that has inputs that get passed to WDL file. Optional

Workflow options file - JSON file that contains workflow level options. Optional

Workflow metadata path - File path where workflow metadata is to be outputted. Optional (NOTE: provide an example??)

WDL zip file - zip file containing workflows being imported by the primary workflow. Optional (Not required if primary workflow is importing workflows that exist inside the same directory where 
Cromwell is being run.) (NOTE: maybe that last line isn't required??)

labels file - JSON file containing labels applied to all tasks in the WDL file. Optional
```

**Comment by ruchim** [comment] 2017-06-27 17:59
Duplicate of #2343 so I'll close this ticket as it's actively being worked on in #2369.

**Closed by ruchim** 2017-06-27 17:59 UTC
Labels: Technical Debt ⚓
