### ISSUE TITLE
Creating S3 folder for writing logs/results silently failing

### ISSUE THREAD

**Issue by tom-dyar** [broadinstitute/cromwell#3774] opened 2018-06-13 19:06 UTC
I am trying to adapt a WDL workflow originally developed for DNAnexus, to work in AWS Batch. I am running from "develop" branch on Mac, server mode. The workflow seems to run on AWS, but then fails when checking for output logs in S3...

inputs: [demux_plus_inputs.json.txt](https://github.com/broadinstitute/cromwell/files/2099495/demux_plus_inputs.json.txt)
workflow: [demux_only.wdl.txt](https://github.com/broadinstitute/cromwell/files/2099496/demux_only.wdl.txt)
resource file: [workflows.zip](https://github.com/broadinstitute/cromwell/files/2099470/workflows.zip)
config file, which shows some attempts to add the local filesystem, since I get an error about that: 
[aws.conf.txt](https://github.com/broadinstitute/cromwell/files/2099528/aws.conf.txt)

```
2018-06-13 14:29:27,796 cromwell-system-akka.dispatchers.api-dispatcher-72 INFO  - Unspecified type (Unspecified version) workflow a67833cb-b894-4790-872f-9f3104cab60c submitted
2018-06-13 14:29:44,760 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - 1 new workflows fetched
2018-06-13 14:29:44,761 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - WorkflowManagerActor Starting workflow UUID(a67833cb-b894-4790-872f-9f3104cab60c)
2018-06-13 14:29:44,765 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - WorkflowManagerActor Successfully started WorkflowActor-a67833cb-b894-4790-872f-9f3104cab60c
2018-06-13 14:29:44,765 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - Retrieved 1 workflows from the WorkflowStoreActor
2018-06-13 14:29:44,774 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
2018-06-13 14:29:45,255 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - MaterializeWorkflowDescriptorActor [UUID(a67833cb)]: Parsing workflow as WDL draft-2
2018-06-13 14:29:46,004 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - MaterializeWorkflowDescriptorActor [UUID(a67833cb)]: Call-to-Backend assignments: demux_only.illumina_demux -> AWSBATCH
2018-06-13 14:29:46,085 cromwell-system-akka.dispatchers.backend-dispatcher-91 WARN  - AWSBATCH [UUID(a67833cb)]: Key/s [preemptible, dx_instance_type] is/are not supported by backend. Unsupported attributes will not be part of job executions.
2018-06-13 14:29:47,088 cromwell-system-akka.dispatchers.backend-dispatcher-91 WARN  - Localhost hostname lookup failed, keeping the value 'unavailable'
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.getsentry.raven.event.EventBuilder$HostnameCache.updateCache(EventBuilder.java:491)
	at com.getsentry.raven.event.EventBuilder$HostnameCache.getHostname(EventBuilder.java:477)
	at com.getsentry.raven.event.EventBuilder.autoSetMissingValues(EventBuilder.java:97)
	at com.getsentry.raven.event.EventBuilder.build(EventBuilder.java:410)
	at com.getsentry.raven.logback.SentryAppender.buildEvent(SentryAppender.java:324)
	at com.getsentry.raven.logback.SentryAppender.append(SentryAppender.java:230)
	at com.getsentry.raven.logback.SentryAppender.append(SentryAppender.java:37)
	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.warn(Logger.java:716)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.$anonfun$applyOrElse$2(Slf4jLogger.scala:75)
	at akka.event.slf4j.Slf4jLogger.withMdc(Slf4jLogger.scala:100)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:75)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:54)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-06-13 14:29:47,368 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - WorkflowExecutionActor-a67833cb-b894-4790-872f-9f3104cab60c [UUID(a67833cb)]: Starting demux_only.illumina_demux
2018-06-13 14:29:48,004 cromwell-system-akka.dispatchers.engine-dispatcher-32 ERROR - Failed to hash /Volumes/nextseq_ngs/180405_NB501680_0019_AHKGNJBGX5.tar.lz4
cromwell.core.path.PathParsingException: java.lang.IllegalArgumentException: /Volumes/nextseq_ngs/180405_NB501680_0019_AHKGNJBGX5.tar.lz4 exists on a filesystem not supported by this instance of Cromwell. Supported filesystems are: s3. Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems
	at cromwell.core.path.PathFactory$.$anonfun$buildPath$4(PathFactory.scala:47)
	at scala.Option.getOrElse(Option.scala:121)
	at cromwell.core.path.PathFactory$.buildPath(PathFactory.scala:42)
	at cromwell.core.path.PathFactory.buildPath(PathFactory.scala:29)
	at cromwell.core.path.PathFactory.buildPath$(PathFactory.scala:29)
	at cromwell.backend.impl.aws.AwsBatchWorkflowPaths.buildPath(AwsBatchWorkflowPaths.scala:51)
	at cromwell.backend.io.WorkflowPaths.$anonfun$getPath$1(WorkflowPaths.scala:43)
	at scala.util.Try$.apply(Try.scala:209)
	at cromwell.backend.io.WorkflowPaths.getPath(WorkflowPaths.scala:43)
	at cromwell.backend.io.WorkflowPaths.getPath$(WorkflowPaths.scala:43)
	at cromwell.backend.impl.aws.AwsBatchWorkflowPaths.getPath(AwsBatchWorkflowPaths.scala:51)
	at cromwell.backend.standard.StandardCachingActorHelper.getPath(StandardCachingActorHelper.scala:41)
	at cromwell.backend.standard.StandardCachingActorHelper.getPath$(StandardCachingActorHelper.scala:41)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.getPath(StandardFileHashingActor.scala:59)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.$anonfun$asyncHashing$1(StandardFileHashingActor.scala:100)
	at scala.util.Try$.apply(Try.scala:209)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.asyncHashing(StandardFileHashingActor.scala:99)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor$$anonfun$fileHashingReceive$1.applyOrElse(StandardFileHashingActor.scala:82)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.akka$actor$Timers$$super$aroundReceive(StandardFileHashingActor.scala:59)
	at akka.actor.Timers.aroundReceive(Timers.scala:44)
	at akka.actor.Timers.aroundReceive$(Timers.scala:36)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.aroundReceive(StandardFileHashingActor.scala:59)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: /Volumes/nextseq_ngs/180405_NB501680_0019_AHKGNJBGX5.tar.lz4 exists on a filesystem not supported by this instance of Cromwell. Supported filesystems are: s3. Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems
	at cromwell.core.path.PathParsingException.<init>(PathParsingException.scala:5)
	... 35 common frames omitted
2018-06-13 14:29:48,009 cromwell-system-akka.dispatchers.engine-dispatcher-32 ERROR - a67833cb:demux_only.illumina_demux:-1:1: Hash error, disabling call caching for this job.
cromwell.core.path.PathParsingException: java.lang.IllegalArgumentException: /Volumes/nextseq_ngs/180405_NB501680_0019_AHKGNJBGX5.tar.lz4 exists on a filesystem not supported by this instance of Cromwell. Supported filesystems are: s3. Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems
	at cromwell.core.path.PathFactory$.$anonfun$buildPath$4(PathFactory.scala:47)
	at scala.Option.getOrElse(Option.scala:121)
	at cromwell.core.path.PathFactory$.buildPath(PathFactory.scala:42)
	at cromwell.core.path.PathFactory.buildPath(PathFactory.scala:29)
	at cromwell.core.path.PathFactory.buildPath$(PathFactory.scala:29)
	at cromwell.backend.impl.aws.AwsBatchWorkflowPaths.buildPath(AwsBatchWorkflowPaths.scala:51)
	at cromwell.backend.io.WorkflowPaths.$anonfun$getPath$1(WorkflowPaths.scala:43)
	at scala.util.Try$.apply(Try.scala:209)
	at cromwell.backend.io.WorkflowPaths.getPath(WorkflowPaths.scala:43)
	at cromwell.backend.io.WorkflowPaths.getPath$(WorkflowPaths.scala:43)
	at cromwell.backend.impl.aws.AwsBatchWorkflowPaths.getPath(AwsBatchWorkflowPaths.scala:51)
	at cromwell.backend.standard.StandardCachingActorHelper.getPath(StandardCachingActorHelper.scala:41)
	at cromwell.backend.standard.StandardCachingActorHelper.getPath$(StandardCachingActorHelper.scala:41)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.getPath(StandardFileHashingActor.scala:59)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.$anonfun$asyncHashing$1(StandardFileHashingActor.scala:100)
	at scala.util.Try$.apply(Try.scala:209)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.asyncHashing(StandardFileHashingActor.scala:99)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor$$anonfun$fileHashingReceive$1.applyOrElse(StandardFileHashingActor.scala:82)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.akka$actor$Timers$$super$aroundReceive(StandardFileHashingActor.scala:59)
	at akka.actor.Timers.aroundReceive(Timers.scala:44)
	at akka.actor.Timers.aroundReceive$(Timers.scala:36)
	at cromwell.backend.standard.callcaching.StandardFileHashingActor.aroundReceive(StandardFileHashingActor.scala:59)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: /Volumes/nextseq_ngs/180405_NB501680_0019_AHKGNJBGX5.tar.lz4 exists on a filesystem not supported by this instance of Cromwell. Supported filesystems are: s3. Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems
	at cromwell.core.path.PathParsingException.<init>(PathParsingException.scala:5)
	... 35 common frames omitted
2018-06-13 14:29:48,013 cromwell-system-akka.dispatchers.backend-dispatcher-95 WARN  - AwsBatchAsyncBackendJobExecutionActor [UUID(a67833cb)demux_only.illumina_demux:NA:1]: Unrecognized runtime attribute keys: preemptible, dx_instance_type
2018-06-13 14:29:48,218 cromwell-system-akka.dispatchers.backend-dispatcher-95 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(a67833cb)demux_only.illumina_demux:NA:1]: `set -ex -o pipefail

if [ -d /mnt/tmp ]; then
  TMPDIR=/mnt/tmp
fi
FLOWCELL_DIR=$(mktemp -d)

read_utils.py extract_tarball \
  /Volumes/nextseq_ngs/180405_NB501680_0019_AHKGNJBGX5.tar.lz4 $FLOWCELL_DIR \
  --loglevel=DEBUG

# find 95% memory
mem_in_mb=`/opt/viral-ngs/source/docker/mem_in_mb_95.sh`

# note that we are intentionally setting --threads to about 2x the core
# count. seems to still provide speed benefit (over 1x) when doing so.
illumina.py illumina_demux \
  $FLOWCELL_DIR \
  1 \
  . \
   \
   \
  --outMetrics=metrics.txt \
  --commonBarcodes=barcodes.txt \
   \
   \
  --max_mismatches=1 \
   \
   \
   \
  --minimum_quality=10 \
   \
  --JVMmemory="$mem_in_mb"m \
  --threads=64 \
  --compression_level=5 \
  --loglevel=DEBUG

rm -f Unmatched.bam
for bam in *.bam; do
  fastqc_out=$(basename $bam .bam)_fastqc.html
  reports.py fastqc $bam $fastqc_out
done`
2018-06-13 14:29:48,871  INFO  - Submitting job to AWS Batch
2018-06-13 14:29:48,871  INFO  - dockerImage: quay.io/broadinstitute/viral-ngs
2018-06-13 14:29:48,871  INFO  - jobQueueArn: arn:aws:batch:us-east-1:140059717706:job-queue/funnel-job-queue
2018-06-13 14:29:48,871  INFO  - commandLine: set -ex -o pipefail

if [ -d /mnt/tmp ]; then
  TMPDIR=/mnt/tmp
fi
FLOWCELL_DIR=$(mktemp -d)

read_utils.py extract_tarball \
  /Volumes/nextseq_ngs/180405_NB501680_0019_AHKGNJBGX5.tar.lz4 $FLOWCELL_DIR \
  --loglevel=DEBUG

# find 95% memory
mem_in_mb=`/opt/viral-ngs/source/docker/mem_in_mb_95.sh`

# note that we are intentionally setting --threads to about 2x the core
# count. seems to still provide speed benefit (over 1x) when doing so.
illumina.py illumina_demux \
  $FLOWCELL_DIR \
  1 \
  . \
   \
   \
  --outMetrics=metrics.txt \
  --commonBarcodes=barcodes.txt \
   \
   \
  --max_mismatches=1 \
   \
   \
   \
  --minimum_quality=10 \
   \
  --JVMmemory="$mem_in_mb"m \
  --threads=64 \
  --compression_level=5 \
  --loglevel=DEBUG

rm -f Unmatched.bam
for bam in *.bam; do
  fastqc_out=$(basename $bam .bam)_fastqc.html
  reports.py fastqc $bam $fastqc_out
done
2018-06-13 14:29:48,873  INFO  - reconfiguredScript: #!/bin/bash
mkdir -p /cromwell_root
    #!/bin/bash

cd /cromwell_root
tmpDir=`mkdir -p "/atbiofx-cromwell/cromwell-execution/demux_only/a67833cb-b894-4790-872f-9f3104cab60c/call-illumina_demux/tmp.e5175ec1" && echo "/atbiofx-cromwell/cromwell-execution/demux_only/a67833cb-b894-4790-872f-9f3104cab60c/call-illumina_demux/tmp.e5175ec1"`
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell_root

)
(
cd /cromwell_root


set -ex -o pipefail

if [ -d /mnt/tmp ]; then
  TMPDIR=/mnt/tmp
fi
FLOWCELL_DIR=$(mktemp -d)

read_utils.py extract_tarball \
  /Volumes/nextseq_ngs/180405_NB501680_0019_AHKGNJBGX5.tar.lz4 $FLOWCELL_DIR \
  --loglevel=DEBUG

# find 95% memory
mem_in_mb=`/opt/viral-ngs/source/docker/mem_in_mb_95.sh`

# note that we are intentionally setting --threads to about 2x the core
# count. seems to still provide speed benefit (over 1x) when doing so.
illumina.py illumina_demux \
  $FLOWCELL_DIR \
  1 \
  . \
   \
   \
  --outMetrics=metrics.txt \
  --commonBarcodes=barcodes.txt \
   \
   \
  --max_mismatches=1 \
   \
   \
   \
  --minimum_quality=10 \
   \
  --JVMmemory="$mem_in_mb"m \
  --threads=64 \
  --compression_level=5 \
  --loglevel=DEBUG

rm -f Unmatched.bam
for bam in *.bam; do
  fastqc_out=$(basename $bam .bam)_fastqc.html
  reports.py fastqc $bam $fastqc_out
done
)  > '/cromwell_root/illumina_demux-stdout.log' 2> '/cromwell_root/illumina_demux-stderr.log'
echo $? > /cromwell_root/illumina_demux-rc.txt.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell_root
find . -type d -empty -print | xargs -I % touch %/.file
)
(
cd /cromwell_root
sync
# make the directory which will keep the matching files
mkdir /cromwell_root/glob-3bcbe4e7489c90f75e0523ac6f3a9385

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-3bcbe4e7489c90f75e0523ac6f3a9385/cromwell_glob_control_file

# symlink all the files into the glob directory
( ln -L *.bam /cromwell_root/glob-3bcbe4e7489c90f75e0523ac6f3a9385 2> /dev/null ) || ( ln *.bam /cromwell_root/glob-3bcbe4e7489c90f75e0523ac6f3a9385 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-3bcbe4e7489c90f75e0523ac6f3a9385 | grep -v cromwell_glob_control_file > /cromwell_root/glob-3bcbe4e7489c90f75e0523ac6f3a9385.list

# make the directory which will keep the matching files
mkdir /cromwell_root/glob-9c776de0acb8005c55560748eb4a7f63

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-9c776de0acb8005c55560748eb4a7f63/cromwell_glob_control_file

# symlink all the files into the glob directory
( ln -L *_fastqc.html /cromwell_root/glob-9c776de0acb8005c55560748eb4a7f63 2> /dev/null ) || ( ln *_fastqc.html /cromwell_root/glob-9c776de0acb8005c55560748eb4a7f63 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-9c776de0acb8005c55560748eb4a7f63 | grep -v cromwell_glob_control_file > /cromwell_root/glob-9c776de0acb8005c55560748eb4a7f63.list


)
mv /cromwell_root/illumina_demux-rc.txt.tmp /cromwell_root/illumina_demux-rc.txt

echo "MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="bdbdba51eee253d75fcf6d84ee981016"

--bdbdba51eee253d75fcf6d84ee981016
Content-Type: text/plain
Content-Disposition: attachment; filename="rc.txt"
"
cat /cromwell_root/illumina_demux-rc.txt
echo "--bdbdba51eee253d75fcf6d84ee981016
Content-Type: text/plain
Content-Disposition: attachment; filename="stdout.txt"
"
cat /cromwell_root/illumina_demux-stdout.log
echo "--bdbdba51eee253d75fcf6d84ee981016
Content-Type: text/plain
Content-Disposition: attachment; filename="stderr.txt"
"
cat /cromwell_root/illumina_demux-stderr.log
echo "--bdbdba51eee253d75fcf6d84ee981016--"

2018-06-13 14:29:54,112 cromwell-system-akka.dispatchers.backend-dispatcher-95 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(a67833cb)demux_only.illumina_demux:NA:1]: job id: e9e747cf-2da8-4117-aedb-ac68d83b7c70
2018-06-13 14:29:54,182 cromwell-system-akka.dispatchers.backend-dispatcher-94 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(a67833cb)demux_only.illumina_demux:NA:1]: Status change from - to Initializing
2018-06-13 14:32:37,206 cromwell-system-akka.dispatchers.backend-dispatcher-95 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(a67833cb)demux_only.illumina_demux:NA:1]: Status change from Initializing to Running
2018-06-13 14:41:13,832  INFO  - Job Complete. Exit code: 0
2018-06-13 14:41:13,833  INFO  - Output path: s3://atbiofx-cromwell/cromwell-execution/demux_only/a67833cb-b894-4790-872f-9f3104cab60c/call-illumina_demux/illumina_demux-stdout.log
2018-06-13 14:41:14,088 cromwell-system-akka.dispatchers.backend-dispatcher-112 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(a67833cb)demux_only.illumina_demux:NA:1]: Status change from Running to Succeeded
2018-06-13 14:41:15,905 cromwell-system-akka.dispatchers.engine-dispatcher-37 ERROR - WorkflowManagerActor Workflow a67833cb-b894-4790-872f-9f3104cab60c failed (during ExecutingWorkflowState): cromwell.core.CromwellFatalException: java.nio.file.NoSuchFileException: target not exists: s3://s3.amazonaws.com/atbiofx-cromwell/cromwell-execution/demux_only/a67833cb-b894-4790-872f-9f3104cab60c/call-illumina_demux/illumina_demux-rc.txt
	at cromwell.core.CromwellFatalException$.apply(core.scala:18)
	at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:38)
	at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:37)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.nio.file.NoSuchFileException: target not exists: s3://s3.amazonaws.com/atbiofx-cromwell/cromwell-execution/demux_only/a67833cb-b894-4790-872f-9f3104cab60c/call-illumina_demux/illumina_demux-rc.txt
	at org.lerch.s3fs.S3SeekableByteChannel.<init>(S3SeekableByteChannel.java:50)
	at org.lerch.s3fs.S3FileSystemProvider.newByteChannel(S3FileSystemProvider.java:359)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at better.files.File.loadBytes(File.scala:171)
	at better.files.File.byteArray(File.scala:174)
	at better.files.File.contentAsString(File.scala:214)
	at cromwell.core.path.BetterFileMethods.contentAsString(BetterFileMethods.scala:112)
	at cromwell.core.path.BetterFileMethods.contentAsString$(BetterFileMethods.scala:112)
	at cromwell.filesystems.s3.S3Path.contentAsString(S3PathBuilder.scala:157)
	at cromwell.core.path.EvenBetterPathMethods.readContentAsString(EvenBetterPathMethods.scala:90)
	at cromwell.core.path.EvenBetterPathMethods.readContentAsString$(EvenBetterPathMethods.scala:90)
	at cromwell.filesystems.s3.S3Path.readContentAsString(S3PathBuilder.scala:157)
	at cromwell.engine.io.nio.NioFlow.$anonfun$readAsString$4(NioFlow.scala:92)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	... 12 more
```

**Comment by tom-dyar** [comment] 2018-06-14 18:56
@elerch -- I got IntelliJ fired up and can step through to see if I can track down what is happening...

**Comment by delagoya** [comment] 2018-06-20 18:10
The staging of Inputs and Outputs from S3 are not yet implemented.

**Comment by elerch** [comment] 2018-06-22 15:55
This is a duplicate of #3804. I'll keep both open for the time being - that issue is more clear about what is going on at a high level, but this has good technical detail.

**Comment by delagoya** [comment] 2018-07-05 21:02
One other thing to keep in mind is that currently STDOUT/STDERR and return code are written to a S3 location that is not unique to runtime of a task. I believe the call ID needs to be added, as was discovered in issue #3744 for per-task volume mounts on the instance. 

E.g. I think a retry of a task in the same workflow will clash on current S3 paths for rc/stderr/stdout

**Comment by geoffjentry** [comment] 2019-04-18 19:11
Closing as per @elerch

**Closed by geoffjentry** 2019-04-18 19:11 UTC
Labels: AWS Backend, gatk 🔧on AWS
