### ISSUE TITLE
no_new_calls fails

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2889] opened 2017-11-14 19:45 UTC
@mcovarr commented on [Fri Aug 05 2016](https://github.com/broadinstitute/centaur/issues/96)

---

@cjllanwarne commented on [Tue Dec 20 2016](https://github.com/broadinstitute/centaur/issues/96#issuecomment-268376059)

@mcovarr what's the context of this ticket?

---

@ruchim commented on [Tue Dec 20 2016](https://github.com/broadinstitute/centaur/issues/96#issuecomment-268390892)

I believe he's referring to the test in Centaur? I notice today the test was set to ignored, even though we offer this wf failure mode. Perhaps its just outdated, I'll try un-ignoring the test

---

@mcovarr commented on [Mon Jan 30 2017](https://github.com/broadinstitute/centaur/issues/96#issuecomment-276110656)

Only seeing this now!  Yes I was referring to the test in Centaur, and I just confirmed it still fails.

**Comment by mcovarr** [comment] 2017-11-14 19:45
The code may or may not be okay, but the test is still failing.

**Comment by kshakir** [comment] 2017-11-21 19:53
Duplicate of #2865

**Closed by kshakir** 2017-11-21 19:53 UTC
