### ISSUE TITLE
Cromwell not killing JES jobs when workflow fails

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2517] opened 2017-08-04 15:04 UTC
- cromwell v28
- JES/PAPI backend

http://104.197.74.91:8000/api/workflows/v1/fd85e95d-8a5e-4010-85e5-f4009ac85776/metadata

My workflow failed.  But I contacted google and the instances were still running.  

I did not have the continue while possible option enabled.

**Comment by LeeTL1220** [comment] 2017-08-04 15:07
Please note that I *did* have continueOnReturnCode:true, but I would not have expected the workflow to have failed and stopped.  Not sure if this is working as designed.

**Comment by Horneth** [comment] 2017-08-04 16:49
It's working as expected at least, Cromwell does not abort running jobs when a workflow fails. It just stops tracking them and fails the workflow without starting new jobs.
`ContinueWhilePossible` makes Cromwell continue to start new jobs "while possible" even if some jobs have failed.
In neither case does Cromwell abort running jobs when the workflow fails though.

**Comment by LeeTL1220** [comment] 2017-08-04 17:02
Sorry, that was one run.  I have another one where that was zero and the
same issue happened.

**Comment by Horneth** [comment] 2017-11-07 19:07
This looks like a feature request along the line to what @cjllanwarne suggested. It could be a third execution mode like "AbortJobsOnFailure".

**Comment by geoffjentry** [comment] 2018-08-18 20:37
@LeeTL1220 Closing this. If you can provide a reproducible example on a modern cromwell, please open a new ticket

**Closed by geoffjentry** 2018-08-18 20:37 UTC
