### ISSUE TITLE
Error with missing files in input JSON

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#703] opened 2016-04-14 11:22 UTC
From @yfarjoun 
----------------
I lost a whole day on this stupid bug....
when the input file specified in a JSON is missing, submitting the job takes a long time and returns with:

Resource representation is only available with these Content-Types:
text/plain; charset=UTF-8
text/plain

Which, needless to say is not pointing at the problem...I only managed to figure this out by slowly transitioning from a functioning JSON to the "problematic" one...

Cheers,

Yossi.

**Comment by kcibul** [comment] 2016-04-14 11:25
@yfarjoun can you add more details to the above?  such as

1. an example of the WDL / JSON you were using
2. when you say "returns with" what was doing that returning?  Swagger/REST?  which endpoint? FireCloud?

**Comment by meganshand** [comment] 2016-04-14 13:01
Not sure if this is a separate issue or not, but when @knoblett and I were submitting a workflow yesterday we got the exact same error message (submitted with Swagger). The issue for her was that there was an input that was specified to be a File type, but in reality it was just a String (so I'm guessing the issue was similar in that it couldn't find the "file"). Unfortunately, it validated just fine, but we weren't able to submit it. 

I'd be happy to provide the WDL and JSON files (both the broken version and the fixed version) but they won't attach in a github comment.

**Comment by yfarjoun** [comment] 2016-04-14 13:12
I submitted the regular single_sample.wdl with the VIR_1923 .JSON that's
there...I guess I don't have permissions or something to access the files
that are listed.

**Comment by meganshand** [comment] 2016-04-14 13:16
Actually if that's true, then I think this is related to #589. @yfarjoun This is assuming that you were submitting with swagger (vs curl in the other issue) and that the project the cromwell server you were using was not the same as broad-gp-gotc-pilot (so it didn't have access to those input files).

**Comment by yfarjoun** [comment] 2016-04-14 13:25
duplicate of #589

**Closed by yfarjoun** 2016-04-14 13:25 UTC
Labels: UserSupport
