### ISSUE TITLE
check-alive polling

### ISSUE THREAD

**Issue by MatthewMah** [broadinstitute/cromwell#2281] opened 2017-05-18 15:21 UTC
When running jobs on backends with job runtime limits such as LSF or SLURM, jobs reaching the runtime limits are killed by the backend. [Cromwell never detects that this occurs](http://gatkforums.broadinstitute.org/wdl/discussion/9542/does-cromwell-detect-task-failures-based-on-check-alive), and will wait forever for a job that is already dead. It would be helpful to configure periodic checks for whether tasks are still alive, and enter failure modes for non-zero return codes when unfinished tasks are no longer alive.

**Comment by katevoss** [comment] 2017-05-30 17:53
@geoffjentry do you have an idea of how much work this would be? I believe it has been requested frequently when there is an issue with Cromwell being out of date.

**Comment by geoffjentry** [comment] 2017-05-30 23:01
@katevoss if I managed to correlate this correctly w/ the previous issue I was discussing w/ @kshakir it sounded like it isn't a huge deal, just that there's some nuance to it.

**Comment by katevoss** [comment] 2017-09-07 13:57
from @cjllanwarne:

> Some SFS backends can kill jobs outside of Cromwell, leaving us waiting forever for an rc file that will never be created.
Idea: occasionally run the check-alive command to verify that long-running jobs are indeed still alive outside of restarting Cromwell.

**Comment by katevoss** [comment] 2017-09-08 14:57
This is a dupe of #1499, future conversations will be tracked there.

**Closed by katevoss** 2017-09-08 14:57 UTC
Labels: Medium, User Requested Improvement
