### ISSUE TITLE
Unable to pass VPC network name

### ISSUE THREAD

**Issue by hsimran13** [broadinstitute/cromwell#4005] opened 2018-08-14 22:52 UTC
Hello,

I am trying to use our on premise cromwell instance to submit jobs to GCP via the genomics api.  I seem to have everything working except the VPC network name.  We have a naming convention for the VPC network names configured in our GCP project and don't have the flexibility to change the name.  However, cromwell seems to expect the VPC network name to be "default" and this does not seem to be configurable.  Here is the error I am receiving when trying to submit the workflow:

[error] WorkflowManagerActor Workflow 8f55bf4d-9389-40e6-a469-dbd434394dd8 failed (during ExecutingWorkflowState): java.lang.Exception: Task wf_hello.hello:NA:1 failed. The job was stopped before the command finished. PAPI error code 3. Invalid value for field 'resource.networkInterfaces[0].network': 'https://www.googleapis.com/compute/v1/projects/projectxyz/global/networks/default'. The referenced network resource cannot be found.

Is there a way for me to pass a different network name?  If not, where can I request this feature be added to a future version?

Thanks!

**Comment by ruchim** [comment] 2018-08-19 23:25
In Google Compute Engine, one can create custom networks and even delete the default network.
Docs: https://cloud.google.com/vpc/docs/using-vpc
List of networks: https://console.cloud.google.com/networking/networks/list

The ability to specify a network where operations are created is supported in v2alpha1, but there is no place to specify it in Cromwell (which always uses the "default" network).

AC: Add an option to Cromwell's global config where a user can specify the VPC network name, for the PAPI v2 backend. This would override the current "default" network used by Cromwell.

Testing Criteria:
Confirm that Cromwell honors using a non-default network when specified via the config.
If the network name specified doesn't exist, the error returned to the user contains information about 1) a link to documentation on how to create a network and 2) how to confirm a network exists through the cloud console.

**Comment by geoffjentry** [comment] 2018-09-17 20:57
Hi @hsimran13 - this is effectively a duplicate of #4070 so I'm going to close that one and reference this one there

**Closed by geoffjentry** 2018-09-17 20:57 UTC
Labels: PAPIv2
