### ISSUE TITLE
Cromwell Logs: reduce and redirect

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1012] opened 2016-06-16 17:23 UTC
Currently we have a lot of information that gets logged by Cromwell and some of it seems like it may not be useful to our customers. For example, every actor state transition gets logged, but it's unclear who is using that information. 

We tech talked today an the suggestion was to meet with some key customer's, figure out if there are aspects of our logging they don't need to help reduce, and instead just redirect the unwanted logging to debug level, so that it can still be used for debugging purposes.

**Comment by geoffjentry** [comment] 2016-07-07 19:06
I believe this is a duplicate of #778

**Comment by kcibul** [comment] 2016-07-13 17:16
yes -- closing (but copying Ruchi's great description into #778)

**Closed** 2016-07-13 17:17 UTC
