### ISSUE TITLE
Verify that cache hits no longer cause cromwell to seemingly lock up

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#794] opened 2016-05-05 22:25 UTC
We have a workflow that scatters 95 wide as its first step.  When running with `read_from_cache=false` the workflow chugs along normally.  When we allow the same workflow to read from the cache, Cromwell seems to lock up after the first handful of cache hits(~30).  Cromwell will stop responding to api requests and after some time with logs being written the workflow that was getting the cache hits will hit 503 and timeout errors.  When running the workflow with `read_from_cache=false` we run into none of these errors.

Timeout Error

```
2016-05-05 17:37:02,285 cromwell-system-akka.actor.default-dispatcher-25 WARN  - Configured registration timeout of 1 second expired, stoppingw
```

503 Error

```
Exception occurred while attempting to copy outputs from gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/ccba2c79-c998-4f03-b736-af097391db66/call-SplitGvcf/shard-50 to gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/7164dc88-af61-4ea6-8a73-f0b79594ae9a/call-SplitGvcf/shard-50

com.google.api.client.googleapis.json.GoogleJsonResponseException: 503 Service Unavailable

{

  "code" : 503,

  "errors" : [ {

    "domain" : "global",

    "message" : "Backend Error",

    "reason" : "backendError"

  } ],

  "message" : "Backend Error"

}

at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145) ~[cromwell.jar:0.19]

at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113) ~[cromwell.jar:0.19]

at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40) ~[cromwell.jar:0.19]

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321) ~[cromwell.jar:0.19]

at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056) ~[cromwell.jar:0.19]

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) ~[cromwell.jar:0.19]

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[cromwell.jar:0.19]

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) ~[cromwell.jar:0.19]

at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider.cromwell$engine$backend$io$filesystem$gcs$GcsFileSystemProvider$$innerCopy$1(GcsFileSystemProvider.scala:180) ~[cromwell.jar:0.19]

at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider$$anonfun$copy$1.apply(GcsFileSystemProvider.scala:184) ~[cromwell.jar:0.19]

at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider$$anonfun$copy$1.apply(GcsFileSystemProvider.scala:184) ~[cromwell.jar:0.19]

at scala.util.Try$.apply(Try.scala:192) ~[cromwell.jar:0.19]

at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider$.withRetry(GcsFileSystemProvider.scala:48) ~[cromwell.jar:0.19]

at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider.copy(GcsFileSystemProvider.scala:184) ~[cromwell.jar:0.19]

at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider.copy(GcsFileSystemProvider.scala:96) ~[cromwell.jar:0.19]

at java.nio.file.Files.copy(Files.java:1274) ~[na:1.8.0_72]

at better.files.File$$anon$1.visitFile(File.scala:327) ~[cromwell.jar:0.19]

at better.files.File$$anon$1.visitFile(File.scala:318) ~[cromwell.jar:0.19]

at java.nio.file.Files.walkFileTree(Files.java:2670) ~[na:1.8.0_72]

at java.nio.file.Files.walkFileTree(Files.java:2742) ~[na:1.8.0_72]

at better.files.File.copyTo(File.scala:318) ~[cromwell.jar:0.19]

at cromwell.engine.backend.jes.JesBackend$$anonfun$cromwell$engine$backend$jes$JesBackend$$copyingWork$1$1.apply(JesBackend.scala:403) ~[cromwell.jar:0.19]

at cromwell.engine.backend.jes.JesBackend$$anonfun$cromwell$engine$backend$jes$JesBackend$$copyingWork$1$1.apply(JesBackend.scala:403) ~[cromwell.jar:0.19]

at scala.util.Try$.apply(Try.scala:192) ~[cromwell.jar:0.19]

at cromwell.engine.backend.jes.JesBackend.cromwell$engine$backend$jes$JesBackend$$copyingWork$1(JesBackend.scala:403) ~[cromwell.jar:0.19]

at cromwell.engine.backend.jes.JesBackend$$anonfun$useCachedCall$1.apply(JesBackend.scala:409) [cromwell.jar:0.19]

at cromwell.engine.backend.jes.JesBackend$$anonfun$useCachedCall$1.apply(JesBackend.scala:407) [cromwell.jar:0.19]

at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [cromwell.jar:0.19]

at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [cromwell.jar:0.19]

at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [cromwell.jar:0.19]

at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [cromwell.jar:0.19]

at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [cromwell.jar:0.19]

at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [cromwell.jar:0.19]

at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [cromwell.jar:0.19]

at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [cromwell.jar:0.19]
```

**Comment by kcibul** [comment] 2016-05-23 17:37
Is this the same as #832

**Comment by kcibul** [comment] 2016-05-24 13:02
@cjllanwarne -- is the the same as #832?  If so, can you just close this one?

**Comment by kcibul** [comment] 2016-07-07 17:43
This is to make sure that we don't see this problem on 0.21+, not that we fix it on 0.19 (reported version)

**Comment by geoffjentry** [comment] 2016-07-25 20:55
This turns out to be easy to explain. Every file hash was being checked against the google API and was a fully blocking operation (complete with blocking retries). While within a call each file was checked serially (a problem in and of itself), when there were many calls running at once w/ File objects they'd each sit there and block. That's not a recipe for success

**Comment by ruchim** [comment] 2016-09-21 14:26
@kcibul --- this is the ticket thats moving out of the current milestone and something more related to JointGenotyping scaling.

**Comment by kcibul** [comment] 2016-09-21 16:02
@ruchim -- can you update this ticket with the current status (e.g. how far we scaled initially)?

**Comment by cjllanwarne** [comment] 2017-01-27 21:08
Closing as (a less ambitious) duplicate of #1185

**Closed by cjllanwarne** 2017-01-27 21:08 UTC
Labels: GreenFriends, Q4_2016
