### ISSUE TITLE
Timeout persisting runtime attributes causes workflow failure.

### ISSUE THREAD

**Issue by jacarey** [broadinstitute/cromwell#737] opened 2016-04-25 20:37 UTC
The following workflow failed in cromwell (4ef40f07-ff52-426b-9610-3c9dc66ec67e) on production. Looking metadata we have no logs for the step that failed.

```
{
      "executionStatus": "Failed",
      "shardIndex": 5,
      "outputs": {

      },
      "runtimeAttributes": {

      },
      "cache": {
        "allowResultReuse": true
      },
      "inputs": {
        "input_bam": "SortAndFixSampleBam.output_bam",
        "ref_fasta": "ref_fasta",
        "ref_dict": "ref_dict",
        "disk_size": "agg_medium_disk",
        "dbSNP_vcf": "dbSNP_vcf",
        "known_snps_sites_vcf": "known_snps_sites_vcf",
        "dbSNP_vcf_index": "dbSNP_vcf_index",
        "known_indels_sites_vcf_index": "known_indels_sites_vcf_index",
        "input_bam_index": "SortAndFixSampleBam.output_bam_index",
        "recalibration_report_filename": "sample_name + \".recal_data.csv\"",
        "known_snps_sites_vcf_index": "known_snps_sites_vcf_index",
        "ref_fasta_index": "ref_fasta_index",
        "sequence_group_interval": "subgroup",
        "known_indels_sites_vcf": "known_indels_sites_vcf"
      },
      "failures": [{
        "failure": "Call failed to initialize: Could not persist runtime attributes: Timeout after 5059ms of waiting for a connection.",
        "timestamp": "2016-04-23T09:14:54.651Z"
      }],
      "backend": "JES",
      "end": "2016-04-23T09:14:56.000Z",
      "attempt": 1,
      "executionEvents": [],
      "start": "2016-04-23T09:14:45.000Z"
    }
```

**Comment by jacarey** [comment] 2016-04-25 20:55
Stacktrace:

```
java.sql.SQLTimeoutException: Timeout after 5059ms of waiting for a connection.
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93) ~[cromwell.jar:0.19]
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:12) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$BaseSession.startInTransaction(JdbcBackend.scala:437) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:41) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:38) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
```

**Comment by bradtaylor** [comment] 2016-06-23 16:24
@kcibul @ruchim FYI - this has failed 62 workflows for us (out of 277 total failures, 22%). It is tied for our largest source of failure. We have not seen it since 6/7

**Comment by kcibul** [comment] 2016-06-30 11:47
Please investigate and see what the root cause is.  Then let's decide if would still be a problem on 0.20+ and if we need to hotfix it in 0.19

**Comment by Horneth** [comment] 2016-07-05 16:53
I'm pretty sure this is related to the slick upsert bug. The cromwell code triggering this exception doesn't exist anymore in 0.20 and runtime attributes are persisted the same way all other metadata is. So this will not be a problem in 0.20.

**Comment by kcibul** [comment] 2016-07-05 16:58
@ktibbett can you comment if this is something you need patched into hotfix?  Or something you can tolerate until you're on 0.20+

**Comment by geoffjentry** [comment] 2016-10-14 18:06
@kcibul I strike to close this - no one has answered your last question for multiple months now and upgrades to 0.2x are underway

**Comment by cjllanwarne** [comment] 2016-10-17 19:07
Closing for the reasons @geoffjentry mentioned.

**Closed by cjllanwarne** 2016-10-17 19:07 UTC
Labels: backlog, GreenFriends
