### ISSUE TITLE
put Validate and Inputs methods to Cromwell REST API

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2918] opened 2017-11-19 22:14 UTC
It is sometimes inconvenient to use both WDLTool and Cromwell. Is it possible just to make a REST call in Cromwell specifically for validating WLDs and generating inputs? For people who also write UI-s that interact with Cromwell it will make life easier.

**Comment by geoffjentry** [comment] 2017-11-19 22:22
Duplicate of #2652

**Closed by geoffjentry** 2017-11-19 22:22 UTC
