### ISSUE TITLE
Bulk JES status query

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1089] opened 2016-06-28 22:52 UTC
It would be great if JES had a bulk operation status query API and Cromwell would call that a single time on thousands of operations rather than making thousands of status queries for a single operation each.

**Comment by mcovarr** [comment] 2016-06-28 23:02
This has the potential to reduce QPS errors enormously.

**Comment by kcibul** [comment] 2016-06-30 11:14
I'll put this on the JES WishList, but the place to start with this could work would be SGE support since SGE already has a bulk status API(ish)

**Comment by geoffjentry** [comment] 2016-06-30 14:25
@kcibul I think the sole motivator for this was the QPS issue (see my email to @dionloy last night) as a massive percentage of our JES queries are status polls. Also we don't currently have SGE :)

**Comment by pgrosu** [comment] 2016-06-30 15:55
The simplest way this can be done is to use [Google Cloud Pub/Sub](https://cloud.google.com/pubsub/overview), and then have the message pushed to all subscribed VMs since one can get an Operation ([globally](https://cloud.google.com/compute/docs/reference/latest/globalOperations/list), [by region](https://cloud.google.com/compute/docs/reference/latest/regionOperations/list) or [zone](https://cloud.google.com/compute/docs/reference/latest/zoneOperations/list)).  Then based on the message each individual VM can query itself, and provide the Operation resource status to a central location (Web service, Google Storage, etc).  For more information, here are a link:

https://cloud.google.com/pubsub/overview

Hope it helps,
Paul

**Comment by cjllanwarne** [comment] 2016-10-14 22:36
Duplicate of a ticket that was resolved using the Google batch API

**Closed by cjllanwarne** 2016-10-14 22:36 UTC
