### ISSUE TITLE
Reword error message when failure is due to an invalid return code from the script

### ISSUE THREAD

**Issue by knoblett** [broadinstitute/cromwell#2740] opened 2017-10-12 17:24 UTC
A user requested this [here](https://gatkforums.broadinstitute.org/firecloud/discussion/10319/incorrect-error-message-when-task-fails-to-complete). 

When a script fails to run, the error that is eventually returned is that Cromwell failed to delocalize the output file, due to the fact that the file is missing because the script failed to run. They would like the error message to be clearer as to the true reason of the failure, that it is due to an invalid return code from the script and (secondarily) a failure to delocalize the missing file.

**Comment by bradtaylor** [comment] 2017-11-08 17:12
I'd like to vote for this.

**Comment by katevoss** [comment] 2017-11-14 17:41
#2774 is a dupe of this, so I'll close the other issue.

**Comment by geoffjentry** [comment] 2019-07-30 19:11
This is believed to be resolved with PAPI2 as we handle our own delocalization

**Closed by geoffjentry** 2019-07-30 19:11 UTC
