### ISSUE TITLE
Restart / Recover should not kick off until services have initialized and Liquibase has run

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1196] opened 2016-07-22 17:27 UTC

**Comment by geoffjentry** [comment] 2016-07-22 17:34
oops

**Comment by Horneth** [comment] 2016-07-27 13:57
@mcovarr have you seen evidence that it doesn't happen this way ?

**Comment by mcovarr** [comment] 2016-07-27 13:58
Yes this pretty much always happens with the recover code I merged to develop yesterday.

**Comment by Horneth** [comment] 2016-07-27 20:50
I can't seem to reproduce this - I have a workflow running, stop cromwell, restart it, and no matter how many times I do it I don't see anything wrong with the sequence of events:

```

2016-07-27 16:48:47,144  INFO  - Slf4jLogger started
2016-07-27 16:48:48,456 cromwell-system-akka.actor.default-dispatcher-3 INFO  - Bound to /0.0.0.0:8009
2016-07-27 16:48:48,460 ForkJoinPool-2-worker-15 INFO  - Cromwell service started...
2016-07-27 16:48:48,703  INFO  - Running with database db.url = jdbc:mysql://localhost/cromwell_new
2016-07-27 16:48:50,251  INFO  - Reading from cromwell_new.DATABASECHANGELOG
2016-07-27 16:48:50,337  INFO  - Successfully acquired change log lock
2016-07-27 16:48:50,400  INFO  - Successfully released change log lock
2016-07-27 16:48:50,689 cromwell-system-akka.actor.default-dispatcher-3 INFO  - 1 new workflows fetched
2016-07-27 16:48:50,689 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - WorkflowManagerActor Restarting workflow UUID(c6eb4949-cb81-4a56-b3de-11b1cde3e13e)
2016-07-27 16:48:50,693 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - WorkflowManagerActor Successfully started WorkflowActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e
2016-07-27 16:48:50,773 cromwell-system-akka.dispatchers.engine-dispatcher-15 INFO  - WorkflowActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: transitioning from WorkflowUnstartedState to MaterializingWorkflowDescriptorState
2016-07-27 16:48:51,258 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - MaterializeWorkflowDescriptorActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: Call-to-Backend assignments: hello.hello -> JES
2016-07-27 16:48:51,284 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - MaterializeWorkflowDescriptorActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: transition from ReadyToMaterializeState to MaterializationSuccessfulState: shutting down
2016-07-27 16:48:51,291 cromwell-system-akka.dispatchers.engine-dispatcher-15 INFO  - WorkflowActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: transitioning from MaterializingWorkflowDescriptorState to InitializingWorkflowState
2016-07-27 16:48:51,320 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - WorkflowInitializationActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: State is transitioning from InitializationPendingState to InitializationInProgressState.
2016-07-27 16:48:51,631 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - WorkflowInitializationActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: State is now terminal. Shutting down.
2016-07-27 16:48:51,637 cromwell-system-akka.dispatchers.engine-dispatcher-15 INFO  - WorkflowActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: transitioning from InitializingWorkflowState to ExecutingWorkflowState
2016-07-27 16:48:51,663 cromwell-system-akka.dispatchers.engine-dispatcher-16 INFO  - WorkflowExecutionActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: Starting calls: hello.hello:NA:1
2016-07-27 16:48:51,670 cromwell-system-akka.dispatchers.engine-dispatcher-16 INFO  - WorkflowExecutionActor-c6eb4949-cb81-4a56-b3de-11b1cde3e13e [UUID(c6eb4949)]: WorkflowExecutionActor [UUID(c6eb4949)] transitioning from WorkflowExecutionPendingState to WorkflowExecutionInProgressState.
2016-07-27 16:48:53,508  INFO  - JesRun [UUID(c6eb4949)hello.hello:NA:1]: JES Run ID is operations/EMKB-PDiKhiz_dqSktq89pQBINHtgZmgHSoPcHJvZHVjdGlvblF1ZXVl
2016-07-27 16:48:53,610 cromwell-system-akka.dispatchers.backend-dispatcher-17 INFO  - $a [UUID(c6eb4949)hello.hello:NA:1]: JesAsyncBackendJobExecutionActor [UUID(c6eb4949):hello.hello:NA:1] Status change from - to Initializing
2016-07-27 16:49:59,947 cromwell-system-akka.dispatchers.backend-dispatcher-20 INFO  - $a [UUID(c6eb4949)hello.hello:NA:1]: JesAsyncBackendJobExecutionActor [UUID(c6eb4949):hello.hello:NA:1] Status change from Initializing to Running
```

**Comment by Horneth** [comment] 2016-07-27 21:06
Discussed with @mcovarr - Couldn't reproduce it, was probably fixed in between.

**Closed by Horneth** 2016-07-27 21:06 UTC
Labels: 0.21
