### ISSUE TITLE
Cromwell 21 fails retrying non-preemptible jobs when getting a 429 error

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#1763] opened 2016-12-08 20:25 UTC
GOTC was running the test for staging PAPI (Pipelines API).  This test is launching 50 Single Sample workflows at once and 4 of our workflows failed with this error.
```
"message": "429 Too Many Requests\n{\n  \"code\" : 429,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"message\" : \"Insufficient tokens for quota group and limit 'defaultUSER-100s' of service 'staging-genomics.sandbox.googleapis.com', using the limit by ID '628662467800@1088569555438'.\",\n    \"reason\" : \"rateLimitExceeded\"\n  } ],\n  \"message\" : \"Insufficient tokens for quota group and limit 'defaultUSER-100s' of service 'staging-genomics.sandbox.googleapis.com', using the limit by ID '628662467800@1088569555438'.\",\n  \"status\" : \"RESOURCE_EXHAUSTED\"\n}"
```

All 4 of the jobs that failed were non-premptible whereas there are preemptible jobs that ran into this error and just went from attempt 1 to attempt 2 or w/e.  

I don't think we would want this error to count towards our attempt count and we definitely don't want it to fail non preemptible tasks.

@kcibul for prioritization

**Comment by kcibul** [comment] 2016-12-13 15:12
@geoffjentry commented in a thread  (can you please confirm Jeff)
 
> It's considered a transient exception, we retry up to 10 times I
believe w/ exponential backoff up to 10 seconds IIRC

I think we should increase this significantly as we should buffer the end user from this as much as we can.  What would be the impact of increasing significantly (e.g. 10 minutes)?

**Comment by geoffjentry** [comment] 2016-12-13 16:09
@kcibul I actually meant minutes but still managed to be correct as it is indeed seconds. 

The only impact would be e.g. if something was actually done and your next poll might have not been rate limited you could wind up waiting 10 minutes. For this use case I think it's fine

**Comment by geoffjentry** [comment] 2016-12-13 16:40
@kcibul Disregard what I said, realized I was looking at our initial creation not our polling

**Comment by jsotobroad** [comment] 2016-12-13 16:42
commit hash has our cromwell was running on - 192ea6025613df967d60e9e975693144035379d7

**Comment by geoffjentry** [comment] 2016-12-13 16:47
Polling interval now maxes out at maxPollingInterval, it was 10 minutes until that little buglet was fixed. I also can't find evidence that we're treating 429s as transient during polling. I feel like that has to have been lost along the way at some point.

**Comment by geoffjentry** [comment] 2016-12-13 17:06
@kcibul Ok - that was bothering me so I tracked it down. Turns out that I was misremembering how it was working in the first place in terms of what we retry. We'll retry perpetually for any HTTP error we receive except for a 404 using the exponential backoff up to maxPollingInterval. 

How does this related to preemption? Well, it shouldn't. Preemption isn't an HTTP error it's an actual operation failure. When we receive an operation failure we process that and among other things look to see if it had a preemption error code.

**Comment by kcibul** [comment] 2017-01-06 22:02
is this fixed?  can't reproduce?

**Comment by geoffjentry** [comment] 2017-01-07 02:15
It was in the "what happened shouldn't be possible but yet it happened" category. It disturbed the hell out of me but I wasn't able to reproduce it nor find a code path which made sense.

**Comment by jsotobroad** [comment] 2017-01-10 17:09
They upped our QPS on our projects so we can't actually reproduce 429 errors in our projects anymore with any tests that we currently have(we were able to do it before with our 50 workflow test).  You would have to write some wdl that scatters wide and send in a number of them at the same time to cromwell in some non-upped QPS project.

**Comment by jsotobroad** [comment] 2017-01-10 17:28
Realized I had more logs that might be helpful from what we saw in one of the workflows that failed.   This is a task that is pre-emptible
```
2016-12-08 16:14:28,581 cromwell-system-akka.dispatchers.engine-dispatcher-145 WARN  - WorkflowExecutionActor-0545f731-803b-4194-a74e-44cc5c208ce4 [UUID(0545f731)]: Job PairedEndSingleSampleWorkflow.SamToFastqAndBwaMem:5:1 failed with a retryable failure: cromwell.core.package$CromwellFatalException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 429 Too Many Requests
{
  "code" : 429,
  "errors" : [ {
    "domain" : "global",
    "message" : "Insufficient tokens for quota group and limit 'defaultUSER-100s' of service 'staging-genomics.sandbox.googleapis.com', using the limit by ID '628662467800@1088569555438'.",
    "reason" : "rateLimitExceeded"
  } ],
  "message" : "Insufficient tokens for quota group and limit 'defaultUSER-100s' of service 'staging-genomics.sandbox.googleapis.com', using the limit by ID '628662467800@1088569555438'.",
  "status" : "RESOURCE_EXHAUSTED"
}
2016-12-08 16:14:28,581 cromwell-system-akka.dispatchers.engine-dispatcher-145 INFO  - WorkflowExecutionActor-0545f731-803b-4194-a74e-44cc5c208ce4 [UUID(0545f731)]: Retrying job execution for PairedEndSingleSampleWorkflow.SamToFastqAndBwaMem:5:2
2016-12-08 16:14:28,585 cromwell-system-akka.dispatchers.engine-dispatcher-145 INFO  - WorkflowExecutionActor-0545f731-803b-4194-a74e-44cc5c208ce4 [UUID(0545f731)]: Starting calls: PairedEndSingleSampleWorkflow.SamToFastqAndBwaMem:5:2
```

and this is one that was not pre-emptible(is my guess based on metadata from the workflow, only one task is "failed" in that workflow)
```
2016-12-08 16:14:36,602 cromwell-system-akka.dispatchers.engine-dispatcher-289 ERROR - WorkflowManagerActor Workflow 0545f731-803b-4194-a74e-44cc5c208ce4 failed (during ExecutingWorkflowState): cromwell.core.package$CromwellFatalException: cromwell.core.package$CromwellFatalException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 429 Too Many Requests
{
  "code" : 429,
  "errors" : [ {
    "domain" : "global",
    "message" : "Insufficient tokens for quota group and limit 'defaultUSER-100s' of service 'staging-genomics.sandbox.googleapis.com', using the limit by ID '628662467800@1088569555438'.",
    "reason" : "rateLimitExceeded"
  } ],
  "message" : "Insufficient tokens for quota group and limit 'defaultUSER-100s' of service 'staging-genomics.sandbox.googleapis.com', using the limit by ID '628662467800@1088569555438'.",
  "status" : "RESOURCE_EXHAUSTED"
}
2016-12-08 16:14:36,604 cromwell-system-akka.dispatchers.engine-dispatcher-89 INFO  - WorkflowManagerActor WorkflowActor-0545f731-803b-4194-a74e-44cc5c208ce4 is in a terminal state: WorkflowFailedState
```

**Comment by katevoss** [comment] 2017-03-17 19:57
We expect this to be fixed in Cromwell 26. Closing for now.

**Closed by katevoss** 2017-03-17 19:57 UTC
Labels: Bug, GreenFriends, Low
