### ISSUE TITLE
Bug when calling read_objects

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1179] opened 2016-07-19 14:52 UTC
See user question at: http://gatkforums.broadinstitute.org/wdl/discussion/8015/usage-of-wdl-objects-and-the-read-objects-function#latest

When the user calls read_objects and then correctly (as per the spec) tries to access the value an exception occurs.

**Comment by mcovarr** [comment] 2017-01-03 18:43
looks like this might be another instance of #615

**Comment by mcovarr** [comment] 2017-01-03 20:56
Not a dupe of #615 at all, and fixed in 23/24.

**Closed by mcovarr** 2017-01-03 20:56 UTC
Labels: bug ☢, User Requested Improvement
