### ISSUE TITLE
A probrably "bug" in WDL trying to compose an array out of seemly incompatible arrays results in a silence task hang in "Starting" status.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/cromwell#4755] opened 2019-03-19 15:11 UTC
Working with v36, directly from source running ```git checkout tags/36; sbt assembly```; saying this because the resulting .jar file name contains a "35" instead (```server/target/scala-2.12/cromwell-35-71debed-SNAP.jar```)

A subworkflow task is tryting to do the following assignation...:

```
  Array[File]? y 
  # ...
  Array[File] x = select_first([y, []])
```
where ```y``` is a task argument that is assigned the value of a ```Array[File]+``` argument by the invoking workflow.

Eventually I fixed this by unraveling the unnecessary conversions since in this case there is no need for a "?" in the ```y``` nor the ```x``` or the invokation of ```select_first```; however I have to say that I don't see why this "coversion" would be invalid but I'm not much of a wdl or scala expert.

Now the for-sure issue here is that instead of failing indicating what is going on the workflow was still running and the offending task(s) were reported as "Starting" in the metadata and the timing and they stayed that way forever. 

In order to find out what was going on I needed to install and run a locally v36 server (I usually use dsde-method's community  cromwell servers). The logs show first the causing wdl bug like so:

```
[ERROR] [03/19/2019 09:52:14.444] [cromwell-system-akka.dispatchers.engine-dispatcher-47] [akka://cromwell-system ... Could not construct array of type WomMaybeEmptyArrayType(WomOptionalType(WomMaybeEmptyArrayType(WomAnyType))) with this value: List(WomOptionalValue(WomMaybeEmptyArrayType(WomSingleFileType),Some(["gs:// .... 70.tsv.gz"])), [])
```
Notice that Skipped most of the message text showing (what I think are) the important bits . 

This meesage is follow for java exception directly dump into the log output file.

java.lang.UnsupportedOperationException: Could not construct array of type WomMaybeEmptyArrayType(W....z"])), [])
        at wom.values.WomArray$.apply(WomArray.scala:34)
        at wom.values.WomArray$.apply(WomArray.scala:38)
        at wdl.transforms.base.linking.expression.values.LiteralEvaluators$$anon$6.$anonfun$evaluateValue$16(LiteralEvaluators.scala:108)
        at cats.data.Validated.map(Validated.scala:194)
        ...

After this exception there is a log [ERROR] entry appears reporting the exception and exception stack trace.

The timing diagram show the tasks hanging in the "Starting" state forever and the metadata does not report anything apart than these tasks are "Starting".  So the error is silenced and the only recurse left is to abort. A re-submit of the workflow would just get stuck in the same place.

**Comment by aednichols** [comment] 2019-03-19 15:56
Running the workflow
```
version 1.0

workflow test {
  input {
    Array[File]? y = ["some/file/path.txt"]
  }

  output {
    Array[File] x = select_first([y, []])
  }
}
```
on latest `develop` seems to work fine, producing outputs
```
{
  "test.x": ["some/file/path.txt"]
}
```

Is this an accurate simplification of your problem case?

There is a good chance this bug is fixed in 37 onward as a result of https://github.com/broadinstitute/cromwell/pull/4324
>Fixed a regression in Cromwell 36 that could cause operations on empty arrays to fail with a spurious type error

I suspect your workflow got stuck after failing because the `WomArray` code [throws an exception](https://github.com/broadinstitute/cromwell/blob/develop/wom/src/main/scala/wom/values/WomArray.scala#L37) that screws up control flow.

I believe this is a "this should never happen" case so we did not bother upgrading it to our fancier error handling that encodes failures in the type system to achieve predictable behavior.

**Comment by aednichols** [comment] 2019-03-19 17:01
I was ultimately able to reproduce this on 36 by putting the value for `y` in the inputs JSON instead of as a default.

The same scenario works fine on latest `develop`, so I am going to close this issue with the advice that you upgrade to 37.

**Closed by aednichols** 2019-03-19 17:01 UTC
Labels: Awaiting user info
