### ISSUE TITLE
Support optional outputs

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1342] opened 2016-08-26 00:54 UTC
<< being discussed in Google Doc, copy here when it settles down >>

**Comment by cjllanwarne** [comment] 2016-12-20 22:40
Name change because 'conditionals' covers skipped tasks

**Comment by cjllanwarne** [comment] 2016-12-20 22:43
I think we could do this pretty neatly with a `glob()` like function (maybe `optional("out.txt")`) to get around the JES restraints of having to declare file outputs upfront. 

In fact the entire handling logic could be the same, just at the last minute we would convert the array into an Option as long as it has exactly 1 element.

**Comment by cjllanwarne** [comment] 2016-12-20 23:01
An even easier interim: the `toOptional(Array[X]): X?` function

**Comment by cjllanwarne** [comment] 2017-01-31 21:11
Duplicates #1838

**Comment by katevoss** [comment] 2017-03-28 16:53
Closing this as a duplicate of #1838.

**Closed by katevoss** 2017-03-28 16:53 UTC
Labels: WDL Developer Joy
