### ISSUE TITLE
Workflows stuck in submitted status for 45 minutes in CaaS

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3673] opened 2018-05-23 15:23 UTC
Copying chat log below:

---

dshiga [4:46 PM]
hi @kshakir, we're seeing a lot of workflows that have been stuck in submitted status for the past ~45 minutes. is something wrong in caas?
for example this workflow is stuck: 8de76a93-6b66-4c29-a2fe-31e6cd1f969e

kshakir [4:48 PM]
```
Workflow 8de76a93-6b66-4c29-a2fe-31e6cd1f969e in state Running and restarted = false cannot be started and should not have been fetched.
        at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:60)
        at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:56)
        at cromwell.engine.workflow.workflowstore.SqlWorkflowStore.$anonfun$fetchStartableWorkflows$1(SqlWorkflowStore.scala:57)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
:hmmm:

chrisl [4:50 PM]
that sort of looks like the kind of error message I put in when I’m 99% sure a situation is impossible…

mcovarr [4:50 PM]
workflows that are picked up but have old heartbeats will look eligible for pickup, but they won't actually get run and you'll see that message

chrisl [4:50 PM]
oh, or that :slightly_smiling_face:

kshakir [4:51 PM]
I see 13 of these:
```
024bf23f-b7a3-4ede-bddf-938321ac570f
26707981-d32b-4814-ba1f-4e5f27f739dc
52fe6d61-2ba8-4c79-8a50-e365b355e36b
5cbeca9f-c686-45a9-ab57-167379029964
627a48a3-1584-42de-9b57-ee7a859b08d1
6ed1070c-e478-47f2-8ea9-7ccc656bbba9
70786146-ac4e-4d26-9906-ba211fde03f9
8de76a93-6b66-4c29-a2fe-31e6cd1f969e
8f07ade2-0a6d-40df-b886-cf99e3a1ed13
9bda3e3d-1e17-4406-87e3-9ec7f71f4822
cb4b3331-193a-4c22-a95d-40f1ac9b53d6
dc9ded6f-463f-4cb1-a71a-0503c53f702a
f6644044-f4af-412a-a978-12ff080af3e1
```
(edited)

mcovarr [4:51 PM]
yeah that's from the 2/3 of horizontal Cromwell we implemented

mcovarr [4:52 PM]
but not sure why this is happening in this specific case

kshakir [4:52 PM]
How does :heartbeat:-ing work? There was a restart event in the middle of these workflows.
i think

mcovarr [4:55 PM]
timer in the WorkflowExecutionActor

kshakir [4:59 PM]
uploaded and commented on this file 
caas_cromwell_logs.txt
6 MB Plain Text
Scratch the-restart-in-the-middle idea. I think they might have been submitted after the last restart. Gotta take off for now but here's the log dump for chatting at standup tomorrow.

mcovarr [5:02 PM]
that looks odd, it didn't actually restart anything
how was this shut down?

kshakir [5:05 PM]
I assume caas shutdowns are _not_ clean

mcovarr [5:06 PM]
Just curious, I *thought* Cromwell always put the workflow store into a sane state when it started up

**Comment by danbills** [comment] 2018-05-23 15:29
[caas_logs.txt](https://github.com/broadinstitute/cromwell/files/2031717/caas_logs.txt)

**Comment by mcovarr** [comment] 2018-05-23 16:33
I can reproduce this locally, medieval shutdown + restart not working as intended.

**Comment by mcovarr** [comment] 2018-05-23 19:14
PR merged

**Closed by mcovarr** 2018-05-23 19:14 UTC

**Comment by mbookman** [comment] 2018-05-24 16:10
I believe that I am running into this problem with a batch of workflows.
I have a Cromwell instance running on GCE (launched via `docker-compose ... up`).

Cromwell had gotten stuck accepting new workflow requests, so I shut it down and it didn't go down cleanly. After restarting Cromwell, I see:

```
cromwell_1  | 2018-05-24 16:03:29,668 cromwell-system-akka.dispatchers.engine-dispatcher-27 ERROR - Error trying to fetch new workflows
cromwell_1  | common.exception.AggregatedMessageException: Error(s):
cromwell_1  | Workflow a07583dd-f571-44bf-abb7-5bf281dfd249 in state Running and restarted = false cannot be started and should not have been fetched.
```

with a lengthy list of workflows listed with the same error message.

All of these workflows came to a stop. In fact, querying cromwell, I saw:

```
$ curl http://localhost:8000/engine/v1/stats
{"workflows":0,"jobs":0}
```

I have been able to now restart cromwell and submit new workflows and get them running, but these other workflows were fairly well along. I would like to get them started again. What is the best way to do this?

```
$ curl http://localhost:8000/engine/v1/version
{"cromwell":"32-c07d8d9-SNAP"}
```

Thanks!

**Comment by mcovarr** [comment] 2018-05-24 21:29
Hi Matt

Without looking at your DB I can't be sure exactly what the states of your workflows are, but I don't think it would hurt to try a more recent 32 snapshot with the fixes for this issue to see if that helps. If the workflows are still in the workflow store there's at least a chance they would be picked up and resumed on a Cromwell restart.

**Comment by mbookman** [comment] 2018-05-30 00:51
I picked up the latest version of cromwell:develop and upon restarting, the existing workflows were restarted.

Thanks!
