### ISSUE TITLE
Assigning default_runtime_attributes to tasks should be in MaterializeWorkflowDescriptorActor

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1068] opened 2016-06-24 20:47 UTC
This is the test `"assign default runtime attributes"` in `MaterializeWorkflowDescriptorActorSpec`.

To avoid having to recompute the defaults separately in every backend, it should be filled in by the MWDA

**Comment by kcibul** [comment] 2016-06-30 11:20
duplicate of #1076

**Closed by kcibul** 2016-06-30 11:20 UTC
