### ISSUE TITLE
Options + file path relativizing bugs

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1945] opened 2017-02-02 18:47 UTC
Related to #1944 but with some options problems as well:

The following WDL prints nothing for `string_from_maybe_file` and a non-relativized path for `string_from_file` on JES, AWS, and Local (on Local the path is not relativized under the cromwell executions directory):

```
task strings {
  File file 
  File? maybe_file

  String string_from_file = file
  String? string_from_maybe_file = maybe_file

  command {
    echo string_from_file: ${string_from_file} string_from_maybe_file: ${string_from_maybe_file}
  }
  runtime {
    docker: "ubuntu:latest"
  }
}

workflow w {
  File file

  call strings { input: file = file, maybe_file = file }
}
```

**Comment by ruchim** [comment] 2017-02-02 18:51
@mcovarr  is this a dupe of #1940  ?

**Comment by mcovarr** [comment] 2017-02-02 19:00
@ruchim The options part of this might duplicate that bug, but I'm not sure since I don't know the failure mode there.  The non-localized paths part of this is maybe related to #1944 or could be original, not sure about that either.  😦

**Comment by cjllanwarne** [comment] 2017-02-02 21:56
It'll be worth double-checking once the other bug is fixed

**Comment by mcovarr** [comment] 2017-02-06 20:39
Per discussion with @ruchim and @cjllanwarne, the coercion from `File` to `String` in task declarations can't possibly yield a localized path since wdl4s coercions simply don't have the information required to do this.  We're beginning to think File to String coercions probably shouldn't be allowed at all, but I'll keep the issue of disallowing them out of this ticket.

There's still an issue with the optional "filling" not being transferred between the optional File and optional String.  Here's a WDL that reproduces the issue.  `coerced_int` and `coerced_string` stringify as empty:

```
task strings {
  Int? int
  String? string

  Int? coerced_int = string
  String? coerced_string = int

  command {
    echo int: ${int} string: ${string} coerced_int: ${coerced_int} coerced_string: ${coerced_string}
  }
  runtime {
    docker: "ubuntu:latest"
  }
}

workflow w {
  call strings { input: int = 1, string = "2" }
}
```

**Comment by katevoss** [comment] 2017-02-06 20:44
To clarify, @mcovarr does your latest comment mean that @yfarjoun is still unable to use optional parameters? Or did your comment in #1944 confirm that it is working in JES?

**Comment by mcovarr** [comment] 2017-02-06 20:47
The WDL in #1944 is working in JES with develop Cromwell, but the WDL above is not.  I'm not sure exactly what @yfarjoun is trying to do in his WDLs so I'm not sure if he's still impacted.  But certainly the WDL above is still broken.

**Closed** 2017-02-07 22:55 UTC
Labels: Bug, Fire
