### ISSUE TITLE
Workflow finished, middle job still reported as running.

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/cromwell#3483] opened 2018-04-05 20:00 UTC
I have a job that ended up in a weird state.  It's a series of 3 tasks, where each one depends on the output of the previous one.  The workflow finished, but the middle job is listed as still running.  It's workflow.  Seems like an error state.

See https://cromwell-v30.dsde-methods.broadinstitute.org/api/workflows/v1/01c7d76f-5b2b-48cd-be08-ce75b923666e/timing

**Comment by lbergelson** [comment] 2018-04-05 20:02
Here's the metadata
```
{
  "workflowName": "MarkDuplicates",
  "calls": {
    "MarkDuplicates.SortSam": [
      {
        "executionStatus": "Done",
        "backendStatus": "Success",
        "shardIndex": -1,
        "jes": {
          "instanceName": "ggp-8929414080671740740",
          "machineType": "us-east1-d/n1-highmem-4",
          "zone": "us-east1-d"
        },
        "outputs": {
          "outBam": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-SortSam/md.sorted.bam"
        },
        "callCaching": {
          "hashes": {
            "output count": "C4CA4238A0B923820DCC509A6F75849B",
            "runtime attribute": {
              "docker": "727DC68A78243A55A510496DBD51C8FD",
              "continueOnReturnCode": "CFCD208495D565EF66E7DFF9F98764DA",
              "failOnStderr": "68934A3E9455FA72420237EB05902327"
            },
            "output expression": {
              "File outBam": "51E81723BF4AE3737FA7A05AD3C404E0"
            },
            "input count": "A87FF679A2F3E71D9181A67B7542122C",
            "backend name": "5BAA79C7C5A573C899A61D342AA00484",
            "command template": "7F303905B5A7C3C5E133EEA5D655F93F",
            "input": {
              "String docker": "5FFD9AB91DECDD52945847CAED219F0A",
              "String outputName": "A3830295D56B220883B7627EB49D6ECD",
              "String sortOrder": "D68E1AF2DA2A70598DD21717D8621A4C",
              "File bam": "WRKp1w=="
            }
          }
        },
        "returnCode": 0,
        "end": "2018-04-04T06:49:15.680Z",
        "dockerImageUsed": "us.gcr.io/broad-gatk/gatk@sha256:fd8e7a9e65e6a981ab3b92305492d54c3baef7a803ec3fcb895e5ebeedf824e7",
        "attempt": 1,
        "executionEvents": [
          {
            "startTime": "2018-04-04T03:54:17.587Z",
            "description": "Pending",
            "endTime": "2018-04-04T03:54:17.587Z"
          },
          {
            "startTime": "2018-04-04T06:49:04.424457737Z",
            "description": "cromwell poll interval",
            "endTime": "2018-04-04T06:49:12.726Z"
          },
          {
            "startTime": "2018-04-04T06:49:12.726Z",
            "description": "UpdatingCallCache",
            "endTime": "2018-04-04T06:49:14.698Z"
          },
          {
            "startTime": "2018-04-04T03:54:17.588Z",
            "description": "PreparingJob",
            "endTime": "2018-04-04T03:54:17.593Z"
          },
          {
            "startTime": "2018-04-04T06:35:13.639652324Z",
            "description": "delocalizing-files",
            "endTime": "2018-04-04T06:49:04.424457737Z"
          },
          {
            "startTime": "2018-04-04T03:54:27Z",
            "description": "initializing VM",
            "endTime": "2018-04-04T03:55:10.042468067Z"
          },
          {
            "startTime": "2018-04-04T03:54:17.587Z",
            "description": "RequestingExecutionToken",
            "endTime": "2018-04-04T03:54:17.587Z"
          },
          {
            "startTime": "2018-04-04T03:55:14.019652794Z",
            "description": "pulling-image",
            "endTime": "2018-04-04T03:57:25.437055018Z"
          },
          {
            "startTime": "2018-04-04T03:54:20.370Z",
            "description": "RunningJob",
            "endTime": "2018-04-04T03:54:20Z"
          },
          {
            "startTime": "2018-04-04T06:49:04.424457737Z",
            "description": "ok",
            "endTime": "2018-04-04T06:49:04.424457737Z"
          },
          {
            "startTime": "2018-04-04T03:54:20Z",
            "description": "waiting for quota",
            "endTime": "2018-04-04T03:54:27Z"
          },
          {
            "startTime": "2018-04-04T03:57:25.437055018Z",
            "description": "localizing-files",
            "endTime": "2018-04-04T04:20:16.453751287Z"
          },
          {
            "startTime": "2018-04-04T06:49:14.698Z",
            "description": "UpdatingJobStore",
            "endTime": "2018-04-04T06:49:15.680Z"
          },
          {
            "startTime": "2018-04-04T03:55:10.042468067Z",
            "description": "start",
            "endTime": "2018-04-04T03:55:14.019652794Z"
          },
          {
            "startTime": "2018-04-04T03:54:17.593Z",
            "description": "CheckingCallCache",
            "endTime": "2018-04-04T03:54:20.370Z"
          },
          {
            "startTime": "2018-04-04T04:20:16.453751287Z",
            "description": "running-docker",
            "endTime": "2018-04-04T06:35:13.639652324Z"
          },
          {
            "startTime": "2018-04-04T03:54:17.587Z",
            "description": "WaitingForValueStore",
            "endTime": "2018-04-04T03:54:17.588Z"
          }
        ]
      }
    ],
    "MarkDuplicates.ClassicMarkDuplicates": [
      {
        "preemptible": false,
        "executionStatus": "Running",
        "stdout": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-ClassicMarkDuplicates/ClassicMarkDuplicates-stdout.log",
        "backendStatus": "Running",
        "shardIndex": -1,
        "jes": {
          "executionBucket": "gs://broad-dsde-methods/cromwell-execution-30",
          "endpointUrl": "https://genomics.googleapis.com/",
          "googleProject": "broad-dsde-methods"
        },
        "runtimeAttributes": {
          "preemptible": "0",
          "failOnStderr": "false",
          "bootDiskSizeGb": "10",
          "disks": "local-disk 1 LOCAL",
          "continueOnReturnCode": "0",
          "docker": "us.gcr.io/broad-gatk/gatk:4.0.2.1",
          "cpu": "4",
          "noAddress": "false",
          "zones": "us-central1-a,us-central1-b,us-east1-d,us-central1-c,us-central1-f,us-east1-c",
          "memory": "16 GB"
        },
        "callCaching": {
          "allowResultReuse": true,
          "effectiveCallCachingMode": "ReadAndWriteCache",
          "hit": false,
          "result": "Cache Miss"
        },
        "inputs": {
          "outputName": "md",
          "bam": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-PreSort/md.sorted.bam",
          "docker": "us.gcr.io/broad-gatk/gatk:4.0.2.1"
        },
        "backendLabels": {
          "cromwell-workflow-id": "cromwell-01c7d76f-5b2b-48cd-be08-ce75b923666e",
          "wdl-task-name": "classicmarkduplicates"
        },
        "labels": {
          "wdl-task-name": "ClassicMarkDuplicates",
          "cromwell-workflow-id": "cromwell-01c7d76f-5b2b-48cd-be08-ce75b923666e"
        },
        "jobId": "operations/EI-bgPCoLBiv-9bxttKRjqUBIJ-XkZe9BioPcHJvZHVjdGlvblF1ZXVl",
        "backend": "JES",
        "stderr": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-ClassicMarkDuplicates/ClassicMarkDuplicates-stderr.log",
        "callRoot": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-ClassicMarkDuplicates",
        "attempt": 1,
        "backendLogs": {
          "log": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-ClassicMarkDuplicates/ClassicMarkDuplicates.log"
        },
        "start": "2018-04-04T00:13:08.587Z"
      }
    ],
    "MarkDuplicates.PreSort": [
      {
        "preemptible": false,
        "executionStatus": "Done",
        "stdout": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-PreSort/PreSort-stdout.log",
        "backendStatus": "Success",
        "shardIndex": -1,
        "jes": {
          "endpointUrl": "https://genomics.googleapis.com/",
          "machineType": "us-east1-d/n1-highmem-4",
          "googleProject": "broad-dsde-methods",
          "executionBucket": "gs://broad-dsde-methods/cromwell-execution-30",
          "zone": "us-east1-d",
          "instanceName": "ggp-10276417784841300252"
        },
        "outputs": {
          "outBam": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-PreSort/md.sorted.bam"
        },
        "runtimeAttributes": {
          "preemptible": "0",
          "failOnStderr": "false",
          "bootDiskSizeGb": "10",
          "disks": "local-disk 1 LOCAL",
          "continueOnReturnCode": "0",
          "docker": "us.gcr.io/broad-gatk/gatk:4.0.2.1",
          "cpu": "4",
          "noAddress": "false",
          "zones": "us-central1-a,us-central1-b,us-east1-d,us-central1-c,us-central1-f,us-east1-c",
          "memory": "16 GB"
        },
        "callCaching": {
          "allowResultReuse": true,
          "hit": false,
          "result": "Cache Miss",
          "hashes": {
            "output count": "C4CA4238A0B923820DCC509A6F75849B",
            "runtime attribute": {
              "docker": "727DC68A78243A55A510496DBD51C8FD",
              "continueOnReturnCode": "CFCD208495D565EF66E7DFF9F98764DA",
              "failOnStderr": "68934A3E9455FA72420237EB05902327"
            },
            "output expression": {
              "File outBam": "51E81723BF4AE3737FA7A05AD3C404E0"
            },
            "input count": "A87FF679A2F3E71D9181A67B7542122C",
            "backend name": "5BAA79C7C5A573C899A61D342AA00484",
            "command template": "7F303905B5A7C3C5E133EEA5D655F93F",
            "input": {
              "String docker": "5FFD9AB91DECDD52945847CAED219F0A",
              "String outputName": "A3830295D56B220883B7627EB49D6ECD",
              "String sortOrder": "33D645FB17F6C04818DAB3100252CF39",
              "File bam": "v+At8g=="
            }
          },
          "effectiveCallCachingMode": "ReadAndWriteCache"
        },
        "inputs": {
          "outputName": "md.sorted",
          "bam": "gs://broad-public-datasets/NA12878/NA12878.hg38.aligned.unsorted.duplicates_marked.bam",
          "docker": "us.gcr.io/broad-gatk/gatk:4.0.2.1",
          "sortOrder": "queryname"
        },
        "backendLabels": {
          "wdl-task-name": "sortsam",
          "wdl-call-alias": "presort",
          "cromwell-workflow-id": "cromwell-01c7d76f-5b2b-48cd-be08-ce75b923666e"
        },
        "returnCode": 0,
        "labels": {
          "wdl-call-alias": "PreSort",
          "cromwell-workflow-id": "cromwell-01c7d76f-5b2b-48cd-be08-ce75b923666e",
          "wdl-task-name": "SortSam"
        },
        "jobId": "operations/EKKkveuoLBic0uPn9PDKzo4BIJ-XkZe9BioPcHJvZHVjdGlvblF1ZXVl",
        "backend": "JES",
        "end": "2018-04-04T00:13:06.677Z",
        "dockerImageUsed": "us.gcr.io/broad-gatk/gatk@sha256:fd8e7a9e65e6a981ab3b92305492d54c3baef7a803ec3fcb895e5ebeedf824e7",
        "stderr": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-PreSort/PreSort-stderr.log",
        "callRoot": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-PreSort",
        "attempt": 1,
        "executionEvents": [
          {
            "startTime": "2018-04-04T00:13:04.837Z",
            "description": "UpdatingCallCache",
            "endTime": "2018-04-04T00:13:05.697Z"
          },
          {
            "startTime": "2018-04-03T21:35:02.588Z",
            "description": "PreparingJob",
            "endTime": "2018-04-03T21:35:02.606Z"
          },
          {
            "startTime": "2018-04-03T21:35:02.606Z",
            "description": "CheckingCallCache",
            "endTime": "2018-04-03T21:35:05.337Z"
          },
          {
            "startTime": "2018-04-03T21:52:07.621362223Z",
            "description": "running-docker",
            "endTime": "2018-04-03T23:46:57.248430517Z"
          },
          {
            "startTime": "2018-04-03T23:46:57.248430517Z",
            "description": "delocalizing-files",
            "endTime": "2018-04-04T00:10:30.287776787Z"
          },
          {
            "startTime": "2018-04-03T21:35:05.337Z",
            "description": "RunningJob",
            "endTime": "2018-04-03T21:35:05Z"
          },
          {
            "startTime": "2018-04-04T00:10:30.287776787Z",
            "description": "ok",
            "endTime": "2018-04-04T00:10:30.287776787Z"
          },
          {
            "startTime": "2018-04-03T21:35:47.186424Z",
            "description": "start",
            "endTime": "2018-04-03T21:35:48.818896012Z"
          },
          {
            "startTime": "2018-04-03T21:35:05Z",
            "description": "waiting for quota",
            "endTime": "2018-04-03T21:35:09Z"
          },
          {
            "startTime": "2018-04-04T00:13:05.697Z",
            "description": "UpdatingJobStore",
            "endTime": "2018-04-04T00:13:06.677Z"
          },
          {
            "description": "initializing VM",
            "endTime": "2018-04-03T21:35:47.186424Z",
            "startTime": "2018-04-03T21:35:09Z"
          },
          {
            "startTime": "2018-04-03T21:35:02.588Z",
            "description": "Pending",
            "endTime": "2018-04-03T21:35:02.588Z"
          },
          {
            "startTime": "2018-04-03T21:35:48.818896012Z",
            "description": "pulling-image",
            "endTime": "2018-04-03T21:37:50.448425714Z"
          },
          {
            "startTime": "2018-04-03T21:35:02.588Z",
            "description": "WaitingForValueStore",
            "endTime": "2018-04-03T21:35:02.588Z"
          },
          {
            "startTime": "2018-04-03T21:37:50.448425714Z",
            "description": "localizing-files",
            "endTime": "2018-04-03T21:52:07.621362223Z"
          },
          {
            "startTime": "2018-04-03T21:35:02.588Z",
            "description": "RequestingExecutionToken",
            "endTime": "2018-04-03T21:35:02.588Z"
          },
          {
            "startTime": "2018-04-04T00:10:30.287776787Z",
            "description": "cromwell poll interval",
            "endTime": "2018-04-04T00:13:04.837Z"
          }
        ],
        "backendLogs": {
          "log": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-PreSort/PreSort.log"
        },
        "start": "2018-04-03T21:35:02.588Z"
      }
    ]
  },
  "outputs": {
    "MarkDuplicates.ClassicMarkDuplicates.outputMetrics": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-ClassicMarkDuplicates/md.metrics",
    "MarkDuplicates.SortSam.outBam": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-SortSam/md.sorted.bam",
    "MarkDuplicates.ClassicMarkDuplicates.outBam": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-ClassicMarkDuplicates/md.bam",
    "MarkDuplicates.PreSort.outBam": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/call-PreSort/md.sorted.bam"
  },
  "workflowRoot": "gs://broad-dsde-methods/cromwell-execution-30/MarkDuplicates/01c7d76f-5b2b-48cd-be08-ce75b923666e/",
  "id": "01c7d76f-5b2b-48cd-be08-ce75b923666e",
  "inputs": {
    "MarkDuplicates.inBam": "gs://broad-public-datasets/NA12878/NA12878.hg38.aligned.unsorted.duplicates_marked.bam"
  },
  "labels": {
    "cromwell-workflow-id": "cromwell-01c7d76f-5b2b-48cd-be08-ce75b923666e"
  },
  "submission": "2018-04-03T21:34:39.539Z",
  "status": "Succeeded",
  "end": "2018-04-04T06:49:21.892Z",
  "start": "2018-04-03T21:34:56.418Z"
}
```

Might be a duplicate of https://github.com/broadinstitute/cromwell/issues/1489

**Comment by ruchim** [comment] 2018-05-22 01:58
@lbergelson -- is this a reproducible issue? Perhaps we can create a simplified test case for our debugging.

**Comment by lbergelson** [comment] 2018-05-23 20:49
@ruchim No, it was a one off weird thing.  I don't know how to reproduce it.

**Comment by Horneth** [comment] 2018-05-23 21:43
Do you happen to have the Cromwell server logs around the time the workflow was running ?

**Comment by lbergelson** [comment] 2018-06-18 17:35
@Horneth I totally missed your message here.  It was on the methods cromwell 30 instance.  I'm not sure how to find logs.  My guess is that if they're produced by default they're still available somewhere.

**Comment by ernoc** [comment] 2018-12-05 14:04
Hi, I posted comments on #1489 but this is issue is probably the more relevant one. 
I'm getting this behaviour in Cromwell 36:

- Task finishes in SGE backend
- Cromwell logs show `Status change from Running to Done`
- However the metadata and status REST endpoints still show the workflow as `Running` (many hours after - now ~20hs - possibly indefinitely?)
- Restarting Cromwell did not help (workflow still shows as "running")

**Comment by ernoc** [comment] 2018-12-05 14:06
This look reproducible - it's happened 3 times in a row now, but I don't know what triggers this behaviour. My workflow has a large scatter task (~10k items) followed by a very small (computationally) task that gets the scatter results as input.

**Comment by ernoc** [comment] 2018-12-07 10:43
Hi, here's some more, hopefully useful info:
I started a workflow yesterday, its last SGE job finished at 16:50, however Cromwell picked it up at 10AM this morning. 

Cromwell seems to have worked very hard during the night even though it was not processing any workflows:

![image](https://user-images.githubusercontent.com/13629974/49642727-c0bd0f00-fa0b-11e8-8f46-c950fc1cc54f.png)

Then when it marked the workflow as finished, it stopped:

![image](https://user-images.githubusercontent.com/13629974/49642653-98351500-fa0b-11e8-8fa9-0089c647294a.png)

Cromwell did not process anything during the night except for a small workflow at 9pm, which finished quickly. Since that, there are no log entries until 10am today:
```
Dec 06 16:51:02 cromwell-orchestrator docker[14229]: [INFO] [12/06/2018 16:51:02.807] [cromwell-system-akka.dispatchers.backend-dispatcher-2902] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor/WorkflowActor-c20aa0f7-88b3-46da-89d8-05b6d3632e1d/WorkflowExecutionActor-c20aa0f7-88b3-46da-89d8-05b6d3632e1d/c20aa0f7-88b3-46da-89d8-05b6d3632e1d-SubWorkflowExecutionActor-SubWorkflow-XXX:-1:1/eaf7979f-bca0-4c53-bed9-a9e90d585565-SubWorkflowActor-SubWorkflow-XXX:-1:1/eaf7979f-bca0-4c53-bed9-a9e90d585565-EngineJobExecutionActor-XXX.YYY:NA:1/eaf7979f-bca0-4c53-bed9-a9e90d585565-BackendJobExecutionActor-XXX.YYY:NA:1/DispatchedConfigAsyncJobExecutionActor] DispatchedConfigAsyncJobExecutionActor [UUID(eaf7979f)XXX.YYY:NA:1]: Status change from Running to Done
...
Dec 06 21:47:12 cromwell-orchestrator [INFO] [12/06/2018 21:47:12.543] [cromwell-system-akka.dispatchers.engine-dispatcher-36] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor] WorkflowManagerActor WorkflowActor-404f9e8a-702c-4779-9a92-532c8abcfa4a is in a terminal state: WorkflowSucceededState
Dec 07 10:02:28 cromwell-orchestrator [INFO] [12/07/2018 10:02:28.694] [cromwell-system-akka.dispatchers.engine-dispatcher-33] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor/WorkflowActor-c20aa0f7-88b3-46da-89d8-05b6d3632e1d/WorkflowExecutionActor-c20aa0f7-88b3-46da-89d8-05b6d3632e1d/c20aa0f7-88b3-46da-89d8-05b6d3632e1d-SubWorkflowExecutionActor-SubWorkflow-XXX:-1:1/eaf7979f-bca0-4c53-bed9-a9e90d585565-SubWorkflowActor-SubWorkflow-XXX:-1:1] eaf7979f-bca0-4c53-bed9-a9e90d585565-SubWorkflowActor-SubWorkflow-XXX:-1:1 [UUID(eaf7979f)]: Workflow XXX complete. Final Outputs:
```

I initially had thought there might be an exponential backoff causing this but the CPU usage pattern seems to suggest otherwise.

**Comment by ruchim** [comment] 2018-12-07 14:16
@ernoc So this sounds like there's a disconnect between the status changing in memory and getting updated in the db (as the REST endpoints report status from the db). 

1. Do you see anything in your logs that indicate db errors?
2. What does your db config look like? 
3. When you report the REST endpoint shows the workflow as 'Running', what about the `executionStatus` key in the metadata? Are some jobs marked as 'Running' as well?
4. Do you see this behavior only with large scatters (10K) or do you see it with smaller scatters as well? Or any other type of workflow shape?

Thanks!

**Comment by ernoc** [comment] 2018-12-10 11:49
Hi @ruchim !

1. Do you see anything in your logs that indicate db errors?

No. I see that the SGE job completed (`Status change from Running to Done`)

2. What does your db config look like?
```
database {
  db.url = "jdbc:mysql://.../${CROMWELL_DB}?useSSL=false&rewriteBatchedStatements=true"
  db.user = ...
  db.password = ...
  db.driver = "com.mysql.jdbc.Driver"
  profile = "slick.jdbc.MySQLProfile$"
}
```
backed by a MariaDB instance.

3. When you report the REST endpoint shows the workflow as 'Running', what about the executionStatus key in the metadata? Are some jobs marked as 'Running' as well?

The SGE job reported as running as well. I manually query the database, and I see no changes in the `JOB_STORE_ENTRY` table when the SGE job completes and the corresponding entry appears in the Cromwell logs (although not entirely sure I should see something).

4.  Do you see this behavior only with large scatters (10K) or do you see it with smaller scatters as well? Or any other type of workflow shape?

I've only observed this behaviour with large scatters AND a file-of-file-names approach. I don't know exactly what combination of WDL features or what threshold of scatter width triggers it .

**Comment by ernoc** [comment] 2018-12-14 11:16
@ruchim I was trying to follow the code path and it does seem that I see the effect of line 1012 in the logs:
https://github.com/broadinstitute/cromwell/blob/develop/backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala#L1012

but can't see the effect of line 1013 in the metadata, until many hours later ... maybe some contention handling / regulating code? I don't yet understand how MetadataBuilderRegulatorActor works but could this be involved?

```
      jobLogger.info(s"Status change from $prevStatusName to $state")
      tellMetadata(Map(CallMetadataKeys.BackendStatus -> state))
```

**Comment by danbills** [comment] 2019-01-11 20:27
This issue should be addressed by an issue we found with the metadata summarizer.  It should be fixed, we are running tests to confirm

**Comment by ruchim** [comment] 2019-03-22 18:12
@ernoc -- Feel free to reopen if you continue seeing this on Cromwell v38.

**Closed by ruchim** 2019-03-22 18:12 UTC
Labels: Needs Triage, User Requested Improvement
