### ISSUE TITLE
excluding some input variables from caching

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2927] opened 2017-11-21 19:21 UTC
Many tools have thread/cores as parameter. It does not influence the end results but its change in inputs may be considered as cache invalidation by cromwell. It would be nice to have a way to tell cromwell to ignore some variables (like threads) in the caching process.

**Comment by cjllanwarne** [comment] 2017-11-30 19:21
To clarify the current situation...

Most of these "don't affect the results" attributes are indeed ignored for call caching. But workflow inputs are all used.

So, if it's a hard-coded value it won't be call cached, but if the attribute is set by an expression based on an input, the input value will be hashed even if the runtime attribute value isn't.

Hope that made sense...

**Comment by cjllanwarne** [comment] 2017-11-30 19:30
Maybe an example would also help:
```wdl
workflow foo {
  ...
  runtime {
    memory: "2GB" # ignored for call caching
  }
}
```

```wdl
workflow foo {
  String memory_string # hashed for call caching
  runtime {
    memory: memory_string # still ignored for call caching
  }
}
```

**Comment by antonkulaga** [comment] 2017-12-03 16:24
@cjllanwarne actually that what I ask - give me a feature to mark manually the fields that should not affect caching, probably in options.json

**Comment by katevoss** [comment] 2017-12-04 20:40
@antonkulaga in that case this is a duplicate of #1210, I'm going to close this issue in favor of continuing the conversation on that one.

**Closed by katevoss** 2017-12-04 20:40 UTC
