### ISSUE TITLE
Merge in wdl4s wdl_refactor branch

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1443] opened 2016-09-19 16:41 UTC
Bring in lots of Scott's wdl4s goodness.  This should include

- [x] Individuals spend 1-2 hours reviewing the PR as homework
- [x] Team gathers for group discussion of the code
- [ ] Rebase wdl4s
- [ ] Test cromwell 0.21 with wdl4s (unit tests & centaur)
- [ ] Fix test failures from above
- [ ] Merge!

**Comment by ruchim** [comment] 2016-10-17 13:01
Duplicate of ticket in Progress #1522, closing this issue.

**Closed by ruchim** 2016-10-17 13:01 UTC
Labels: Q4_2016
