### ISSUE TITLE
Cromwell Out of Memory Error Joint Genotyping Workflow Large Array of Arrays

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#1051] opened 2016-06-22 19:19 UTC
This Cromwell jar running this was using 25G of memory.  I have the heapdump on my local machine (wont let me upload because of size, even gzipped).  The task that causes this issue outputs two `Array[Array[String]]` with the `read_tsv()` function.  The dimensions of these arrays are 901 x 5205.  I did not run into this issue if I cut the data in half resulting in two arrays with dimensions of 450 x 5205.

```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
    at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
    at java.lang.StringCoding.encode(StringCoding.java:344)
    at java.lang.StringCoding.encode(StringCoding.java:387)
    at java.lang.String.getBytes(String.java:958)
    at cromwell.util.StringUtil$StringCompression$$anonfun$deflate$extension$1.apply(StringUtil.scala:17)
    at cromwell.util.StringUtil$StringCompression$$anonfun$deflate$extension$1.apply(StringUtil.scala:14)
    at scala.util.Try$.apply(Try.scala:192)
    at cromwell.util.StringUtil$StringCompression$.deflate$extension(StringUtil.scala:14)
    at cromwell.engine.db.slick.SlickDataAccess.deflate$1(SlickDataAccess.scala:152)
    at cromwell.engine.db.slick.SlickDataAccess.cromwell$engine$db$slick$SlickDataAccess$$wdlValueToDbValue(SlickDataAccess.scala:160)
    at cromwell.engine.db.slick.SlickDataAccess$$anonfun$44$$anonfun$apply$35.apply(SlickDataAccess.scala:612)
    at cromwell.engine.db.slick.SlickDataAccess$$anonfun$44$$anonfun$apply$35.apply(SlickDataAccess.scala:608)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
    at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
    at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
    at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
    at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
    at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:245)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
    at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:245)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at cromwell.engine.db.slick.SlickDataAccess$$anonfun$44.apply(SlickDataAccess.scala:608)
    at cromwell.engine.db.slick.SlickDataAccess$$anonfun$44.apply(SlickDataAccess.scala:607)
    at slick.backend.DatabaseComponent$DatabaseDef$$anonfun$runInContext$1.apply(DatabaseComponent.scala:146)
    at slick.backend.DatabaseComponent$DatabaseDef$$anonfun$runInContext$1.apply(DatabaseComponent.scala:146)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
```

**Comment by jsotobroad** [comment] 2016-06-22 19:28
```
task TsvToArrayOfArrays {
    File tsv_1
    File tsv_2
    command {

    }

    runtime {
      docker: "python:2.7"
      memory: "1 GB"
    }

    output {
        Array[Array[String]] output_matrix = read_tsv("${tsv_1}")
        Array[Array[String]] output_matrix = read_tsv("${tsv_2}")
    }
}
```

**Comment by pgrosu** [comment] 2016-06-29 00:10
@jsotobroad  Could you use a `n1-highmem-8` or `n1-standard-16` machine type, which gives you 52 GB and 60 GB of memory respectively, so you don't have to experience this?  All the machine types are listed here:

https://cloud.google.com/compute/docs/machine-types#standard_machine_types

Hope it helps,
Paul

**Comment by geoffjentry** [comment] 2016-09-09 16:25
@kcibul It might not be. I made the same claim at one point and got a lot of hesitant looks from fellow Cromwellians. We're a lot more robust to storing this stuff but at some point it still needs to be gathered into a single array object

**Comment by kcibul** [comment] 2016-09-19 16:57
This is with a 5k scatter... let's verify with 20k and then benchmark how far it can go

**Comment by geoffjentry** [comment] 2016-09-19 16:59
https://www.youtube.com/watch?v=TuEdU_lrtZk

**Comment by cjllanwarne** [comment] 2017-01-31 20:29
Closing as duplicate of our newer and more ambitious JG tickets.

**Closed by cjllanwarne** 2017-01-31 20:29 UTC
Labels: GreenFriends, Q4_2016
