### ISSUE TITLE
Please callcache based on Docker image hashes, not the image string + tag

### ISSUE THREAD

**Issue by helgridly** [broadinstitute/cromwell#1617] opened 2016-10-24 20:00 UTC
When a user specifies a Docker image of `whoever/myimage:latest`, they almost certainly don't want to avoid to a version of the job that was latest two years ago. This is the current behaviour.

Please instead resolve the string to a Docker image hash and use that for call caching instead.

The final Docker hash used should end up in call-level metadata so we can know what it is later.

Tagging @abaumann so he knows I made this and can chime in to agree with me if there are any questions.

Further Refinement from Office Hours:
- Supported Docker Image Repository
-- must have: DockerHub, GCR
-- should have: ECR if it doesn't delay, otherwise a separate ticket
-- bonus points to verify this works against Quay 
- Only API v2 supported  
- Support for both public and private images

**Comment by cjllanwarne** [comment] 2016-10-25 15:21
Pinging @kcibul for priority

**Comment by geoffjentry** [comment] 2016-10-25 15:24
Implementer: please use the akka http client

**Comment by kcibul** [comment] 2016-10-25 18:24
This is being discussed with faces.  First with Hussein and his PO to see
if this is a priority for FireCloud

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by helgridly** [comment] 2016-10-25 18:28
I already discussed this with Alex, and he said yes, which is why I made this ticket.

**Comment by kcibul** [comment] 2016-10-25 18:51
Cool - he and I can talk priority then. Thanks!

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by kcibul** [comment] 2016-11-08 21:57
I believe to do this properly, it's the specific backend that should grab the docker image hash when a task is actually run (as opposed to the engine which can evaluate it when it sends it to the backend... which could queue it for any length of time).

When checking for a call cache hit... we should first check everything else that's cheap before getting this hash

**Comment by kcibul** [comment] 2017-01-03 14:53
We agreed that this can be restricted to the v1.2 API and should include support for public and private images on dockerhub, gcr and ecr with quay.io as a bonus.

**Comment by kshakir** [comment] 2017-01-03 15:08
Minor edit to Kris' comment: It's the Docker Registry v2 API: https://docs.docker.com/registry/spec/api/

**Comment by katevoss** [comment] 2017-03-13 16:05
@kshakir is this a dupe of the Docker hashing work that is already completed? If so, I'll close it out.

**Comment by helgridly** [comment] 2017-03-13 16:06
@katevoss yes

**Closed** 2017-03-13 17:33 UTC
