### ISSUE TITLE
Clean up Centaur-in-Travis build so someone other than Jeff can do it

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1296] opened 2016-08-16 11:13 UTC

**Comment by geoffjentry** [comment] 2016-08-16 13:34
Oops, I forgot about this.

The tricky part is defining *where* the stuff lives. Private dir on broad NFS, private repo, confluence, etc. There's precedence for all of the above.

**Comment by cjllanwarne** [comment] 2017-01-31 20:55
Closing presumed fixed

**Comment by geoffjentry** [comment] 2017-01-31 21:07
It is not, it just came up today actually

**Comment by mcovarr** [comment] 2017-01-31 22:28
The title of the ticket is kind of wrong, it should instead say something like "pull the Centaur Docker from a Broad Docker Hub repo rather than out of Jeff's repo".

**Comment by geoffjentry** [comment] 2017-01-31 22:29
@mcovarr That's the least of the problem here. You literally can't recreate the travis stuff on your own at the moment.

**Comment by mcovarr** [comment] 2017-01-31 22:34
💩

**Comment by katevoss** [comment] 2017-07-13 19:00
Let's resurrect this!

**Comment by geoffjentry** [comment] 2017-07-13 19:02
As I commented above, the tricky part is determining where to put this stuff such that it a) makes sense and b) people will remember it is there. I don't really care, I lean towards a private repo, but the real bottleneck at the time (as I remember asking in person as well) was getting people to opine, and no one did.

**Comment by katevoss** [comment] 2017-07-13 19:40
Hey team (@mcovarr @cjllanwarne @kshakir @danbills), who wants to opine?

**Comment by kcibul** [comment] 2017-07-13 19:40
Could be that @davidbernick has something to offer here for config/secrets management

**Comment by geoffjentry** [comment] 2017-07-13 20:08
Which reminds me that @kshakir mentioned vault-ifying this, except that the original & unencrypted files are only on the laptop in question

**Comment by davidbernick** [comment] 2017-07-13 21:19
I have no background in this situation and the issue isn't helping. Talk voices tomorrow.

**Closed** 2017-07-24 15:32 UTC
