### ISSUE TITLE
cromwell AwsBatchAsyncBackendJobExecutionActor submit identical tumor job instead of tumor/normal pair

### ISSUE THREAD

**Issue by lij41** [broadinstitute/cromwell#4537] opened 2019-01-10 19:03 UTC
I am not sure what is going on here, I am running cromwell with aws batch enabled.

In MarkDuplicate step, the cromwell server shows submit two job: tumor and normal, but it turns out it submitted tumor twice, no normal.

Here is the server log:

[2019-01-10 17:34:31,80] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:0:1]: gatk MarkDuplicates \
     --java-options -Djava.io.tmpdir='' \
     --INPUT /cromwell_root/s4-branford-dev-nphi-valinor-v2/cromwell-execution/tigris_workflow/00d0c2df-8f87-42af-9439-b45593930c84/call-SomaticSNVInDel/vc.SomaticSNVInDel/127f691e-ea2e-441f-9d58-deba01a84c5e/call-mergeBam/shard-0/JML005-M254-NORMAL.merged.bam \
     --OUTPUT JML005-M254-NORMAL.dedup.bam \
     --METRICS_FILE JML005-M254-NORMAL.dupmetric \

    sambamba index -t 4 JML005-M254-NORMAL.dedup.bam
[2019-01-10 17:34:31,80] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:1:1]: gatk MarkDuplicates \
     --java-options -Djava.io.tmpdir='' \
     --INPUT /cromwell_root/s4-branford-dev-nphi-valinor-v2/cromwell-execution/tigris_workflow/00d0c2df-8f87-42af-9439-b45593930c84/call-SomaticSNVInDel/vc.SomaticSNVInDel/127f691e-ea2e-441f-9d58-deba01a84c5e/call-mergeBam/shard-1/JML005-M253-TUMOR.merged.bam \
     --OUTPUT JML005-M253-TUMOR.dedup.bam \
     --METRICS_FILE JML005-M253-TUMOR.dupmetric \

    sambamba index -t 4 JML005-M253-TUMOR.dedup.bam
[2019-01-10 17:34:31,81] [info] Submitting job to AWS Batch
[2019-01-10 17:34:31,81] [info] dockerImage: 267795504649.dkr.ecr.us-east-1.amazonaws.com/s4-radbinf-somaticgenomicsrd-tigris:1.2.0
[2019-01-10 17:34:31,81] [info] jobQueueArn: arn:aws:batch:us-east-1:260062248592:job-queue/GenomicsDefaultQueue-63f905e0-1459-11e9-8f03-0a4a1f15abc2
[2019-01-10 17:34:31,81] [info] taskId: SomaticSNVInDel.MarkDuplicates-Some(1)-1
[2019-01-10 17:34:31,81] [info] hostpath root: vc.SomaticSNVInDel/vc.MarkDuplicates/127f691e-ea2e-441f-9d58-deba01a84c5e/Some(1)/1
[2019-01-10 17:34:31,81] [info] Submitting job to AWS Batch
[2019-01-10 17:34:31,81] [info] dockerImage: 267795504649.dkr.ecr.us-east-1.amazonaws.com/s4-radbinf-somaticgenomicsrd-tigris:1.2.0
[2019-01-10 17:34:31,81] [info] jobQueueArn: arn:aws:batch:us-east-1:260062248592:job-queue/GenomicsDefaultQueue-63f905e0-1459-11e9-8f03-0a4a1f15abc2
[2019-01-10 17:34:31,82] [info] taskId: SomaticSNVInDel.MarkDuplicates-Some(0)-1
[2019-01-10 17:34:31,82] [info] hostpath root: vc.SomaticSNVInDel/vc.MarkDuplicates/127f691e-ea2e-441f-9d58-deba01a84c5e/Some(0)/1
[2019-01-10 17:34:31,99] [warn] Job definition already exists. Performing describe and retrieving latest revision.
[2019-01-10 17:34:35,76] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:0:1]: job id: b632db00-aef4-4463-8ccf-74be73b3c251
[2019-01-10 17:34:35,76] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:1:1]: job id: 26c8aab7-48f7-4a6c-9bf0-306de3037265
[2019-01-10 17:34:35,81] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:0:1]: Status change from - to Initializing
[2019-01-10 17:34:35,81] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:1:1]: Status change from - to Initializing
[2019-01-10 17:36:24,60] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:0:1]: Status change from Initializing to Running
[2019-01-10 17:36:32,19] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:1:1]: Status change from Initializing to Running
[2019-01-10 18:21:56,23] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:1:1]: Status change from Running to Succeeded
[2019-01-10 18:23:09,43] [info] AwsBatchAsyncBackendJobExecutionActor [127f691eSomaticSNVInDel.MarkDuplicates:0:1]: Status change from Running to Succeeded
[2019-01-10 18:23:10,45] [error] WorkflowManagerActor Workflow 00d0c2df-8f87-42af-9439-b45593930c84 failed (during ExecutingWorkflowState): cromwell.engine.io.IoAttempts$EnhancedCromwellIoException: [Attempted 1 time(s)] - IOException: Could not read from s3://s4-branford-dev-nphi-valinor-v2/cromwell-execution/tigris_workflow/00d0c2df-8f87-42af-9439-b45593930c84/call-SomaticSNVInDel/vc.SomaticSNVInDel/127f691e-ea2e-441f-9d58-deba01a84c5e/call-MarkDuplicates/shard-0/MarkDuplicates-0-rc.txt: s3://s3.amazonaws.com/s4-branford-dev-nphi-valinor-v2/cromwell-execution/tigris_workflow/00d0c2df-8f87-42af-9439-b45593930c84/call-SomaticSNVInDel/vc.SomaticSNVInDel/127f691e-ea2e-441f-9d58-deba01a84c5e/call-MarkDuplicates/shard-0/MarkDuplicates-0-rc.txt
Caused by: java.io.IOException: Could not read from s3://s4-branford-dev-nphi-valinor-v2/cromwell-execution/tigris_workflow/00d0c2df-8f87-42af-9439-b45593930c84/call-SomaticSNVInDel/vc.SomaticSNVInDel/127f691e-ea2e-441f-9d58-deba01a84c5e/call-MarkDuplicates/shard-0/MarkDuplicates-0-rc.txt: s3://s3.amazonaws.com/s4-branford-dev-nphi-valinor-v2/cromwell-execution/tigris_workflow/00d0c2df-8f87-42af-9439-b45593930c84/call-SomaticSNVInDel/vc.SomaticSNVInDel/127f691e-ea2e-441f-9d58-deba01a84c5e/call-MarkDuplicates/shard-0/MarkDuplicates-0-rc.txt
	at cromwell.engine.io.nio.NioFlow$$anonfun$withReader$2.applyOrElse(NioFlow.scala:146)
	at cromwell.engine.io.nio.NioFlow$$anonfun$withReader$2.applyOrElse(NioFlow.scala:145)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scal

And here is the corresponding batch job screen shot:
![screen shot 2019-01-10 at 2 00 54 pm](https://user-images.githubusercontent.com/30246817/50990531-44bd5780-14e0-11e9-9d29-c14f408f5008.png)
![screen shot 2019-01-10 at 2 01 21 pm](https://user-images.githubusercontent.com/30246817/50990538-4850de80-14e0-11e9-9227-3cbf52883f81.png)

For job whose id is b632db00-aef4-4463-8ccf-74be73b3c251 suppose to run normal, but if you looked its input, it is running tumor instead.

**Comment by TimurIs** [comment] 2019-01-16 17:27
I believe that you have a WDL that looks something like this
```
call IndexBam as IndexNormal 
{
   ...
} 
call IndexBam as IndexTumor
{
   ...
}
```
If that's the case, then it is a bug - if you have one task called multiple time using "as" then it will run this task with the inputs from the first "as" call.

At least that what I've faced myself.

**Comment by delocalizer** [comment] 2019-02-06 03:45
I'd say this is a dupe of an issue I logged a while back #4364

**Closed** 2019-02-12 01:37 UTC
Labels: AWS Backend, Red team, 🐛Bug
