### ISSUE TITLE
Too Many AWS Requests

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4816] opened 2019-04-09 15:46 UTC
Centaur testing appears to fail when too many tests run concurrently due to:
```
java.lang.RuntimeException: AwsBatchAsyncBackendJobExecutionActor failed and didn't catch its exception.
	at cromwell.backend.standard.StandardSyncExecutionActor$$anonfun$jobFailingDecider$1.applyOrElse(StandardSyncExecutionActor.scala:183)
	at cromwell.backend.standard.StandardSyncExecutionActor$$anonfun$jobFailingDecider$1.applyOrElse(StandardSyncExecutionActor.scala:180)
	at akka.actor.SupervisorStrategy.handleFailure(FaultHandling.scala:298)
[...]
Caused by: software.amazon.awssdk.services.batch.model.BatchException: Too Many Requests (Service: Batch, Status Code: 429, Request ID: 932e695f-5a4b-11e9-abf3-d5638efd51d6)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:115)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:73)
[...]
```

**Comment by cjllanwarne** [comment] 2019-04-09 15:54
A little digging shows that if this is harder than just "raise our limit" then we may be able to use the token throttling mechanism described here: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html

**Comment by geoffjentry** [comment] 2019-04-09 16:04
Duplicate of #4303

**Closed by geoffjentry** 2019-04-09 16:04 UTC
