### ISSUE TITLE
Tidy up the synchronous hell that is the current AWS backend

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1570] opened 2016-10-14 15:28 UTC
- [ ] Add the AsyncAwsBackendExecutionActor FSM to manage all the states we're going to need
- [ ] Remove `Await.result()`
- [ ] Remove `Thread.sleep()`

**Comment by geoffjentry** [comment] 2016-10-14 15:32
I'd <3 it if this was done via actor messaging vs futures, from convo with @cjllanwarne it sounded like that was viable

**Comment by cjllanwarne** [comment] 2016-10-14 15:39
@geoffjentry I agree. I think we could easily replace the `promise.complete`s in `AwsSdkAsyncHandler` with appropriate messages to appropriate actors (NB we probably don't *need* the `AwsSdkAsyncHandler` wrapper class at all)

**Comment by ruchim** [comment] 2016-12-07 15:00
@kshakir is this a duplicate of your current ticket?

**Comment by katevoss** [comment] 2017-03-17 19:50
Unlikely to clean up in the next 6 months. Closing for now.

**Closed by katevoss** 2017-03-17 19:50 UTC
Labels: AWS Backend
