### ISSUE TITLE
Directory does not work properly

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#5041] opened 2019-06-23 14:06 UTC
I get a lot of coercion errors area just when I want to get a file inside the Directory, like dir + "/" +"filename" that makes the Directory totally useless for the pipelines for me.
the error is:
```
Workflow failed

WorkflowFailure(Failed to evaluate job outputs,List(WorkflowFailure(Bad output 'methylation_extraction.out': IllegalArgumentException: No coercion defined from wom value(s) '"/data/cromwell-executions/bs_map_fast/1ea51f16-2197-4703-be02-ee3e59c448c1/call-methylation_search/execution/output/output_CpG.bedGraph"' of type 'Directory' to 'File'.,List())))
```
I enclose the pipeline ( main WDL there is bs_map_run_fast.wdl) and the input
[bs-seq.zip](https://github.com/broadinstitute/cromwell/files/3317934/bs-seq.zip)

**Comment by geoffjentry** [comment] 2019-06-23 15:56
Hi @antonkulaga - as far as I know there is no provision in the WDL spec to subset a `Directory` like this (nor do I believe this was intended behavior). As such, I'm closing this issue because the error you describe indicates Cromwell is correctly implementing the WDL spec. 

If I'm incorrect and there is indeed something in the spec allowing this please reopen.

**Closed by geoffjentry** 2019-06-23 15:56 UTC

**Comment by antonkulaga** [comment] 2019-06-24 10:55
So, how can I get the file inside the folder then?

**Comment by antonkulaga** [comment] 2019-06-24 10:59
That means that the spec sucks as being unable to get a children from the Directory makes it totally useless comparing with File, opened an issue on this

**Comment by geoffjentry** [comment] 2019-06-24 13:41
You can get to a specific file from a directory but using the `Directory` as an input to a `task` and then having that `task` output the `File` you wish to get ahold of

**Comment by antonkulaga** [comment] 2019-06-24 15:39
>You can get to a specific file from a directory but using the Directory as an input to a task and then having that task output the File you wish to get ahold of

Could you explain how? In a task the tool uses directory and writes stuff inside of it. If I cannot get the file that is inside that directory as directory "/filename" how will the task output the file then?
