### ISSUE TITLE
Inputs with different types

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#3059] opened 2017-12-13 18:09 UTC
In order to evaluate CWL expressions we feed the javascript a WomMap of the inputs to the step.
WomMap does not support values with different types which makes the workflow crash if the inputs are of mixed types.

**Comment by danbills** [comment] 2018-01-02 18:22
closing this as a duplicate of #2748

**Closed by danbills** 2018-01-02 18:22 UTC
Labels: AlphaCWL, CWL
