### ISSUE TITLE
Occasionally run `check-alive` in config backend

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2315] opened 2017-06-01 19:25 UTC
Some SFS backends can kill jobs outside of Cromwell, leaving us waiting forever for an rc file that will never be created. 

Idea: occasionally run the `check-alive` command to verify that long-running jobs are indeed still alive outside of restarting Cromwell.

**Comment by MatthewMah** [comment] 2017-06-02 17:28
This is a duplicate of #2281.

**Comment by katevoss** [comment] 2017-09-07 13:57
Closing in favor of #2281

**Closed by katevoss** 2017-09-07 13:57 UTC
Labels: User Requested Improvement
