### ISSUE TITLE
Bonus: Implement (control flow) 'else's

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1550] opened 2016-10-07 18:48 UTC

**Comment by geoffjentry** [comment] 2016-12-18 17:27
@cjllanwarne This looks like it could be the infamous `esled`?

**Comment by mcovarr** [comment] 2017-04-11 18:37
isn't this done?

**Comment by cjllanwarne** [comment] 2017-04-24 15:35
Alas, no. We have `String s = if true then "x" else "y"`, but this ticket is for flow control style `else`s:
```
if (true) {
 call x
} else {
 call y
}
```

**Comment by katevoss** [comment] 2017-08-25 20:19
@cjllanwarne it's still not done, right? What effort would it take to implement?
@ruchim can you explain what the "else" would do and why?

**Comment by geoffjentry** [comment] 2018-08-18 15:48
Closing this as it is more or less a dupe of #2436

**Closed by geoffjentry** 2018-08-18 15:48 UTC
