### ISSUE TITLE
Don't publish noisy "copied * file" events from JES to metadata service

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1298] opened 2016-08-16 15:21 UTC
In order to overcome the eventual consistency of ls on GCS, JES has added additional information to their metadata in the form of 'events' of the form

>   - description: copied 1 file(s) to "gs://fc-8011932d-d76e-4c5d-9f66-1538d86a683b/5e9d3b03-8300-4322-bf3f-822fc6b06b74/ContEstMuTectOncotatorWorkflow/3ffafa1d-7259-4581-b95b-14d38f3ba1ce/call-MiniMutationCalling_Nozzle_Report_Task/nozzle.RData"
    startTime: '2016-08-15T19:39:49.261235611Z'

These are not "events" as we have thought about them (state transitions).

While these should be used to implement glob support in Cromwell, these should be filtered out and not published to the Cromwell metadata service.  They add a huge amount of bulk and there isn't a user story for retrieving them directly through cromwell.  For forensics, the user can get the JES operation ID from the Cromwell metadata and query that for the details.

**Comment by kcibul** [comment] 2016-08-17 17:40
could also be "specifically include the ones we want"

**Comment by ruchim** [comment] 2016-08-19 14:28
Duplicate of issue #1299 -- which as been resolved.

**Comment by kcibul** [comment] 2016-08-19 16:23
Hey Ruchi -- this was for 0.20+, did 1299 fix it both on hot fix and develop?

**Comment by ruchim** [comment] 2016-08-19 17:42
Ahhhh you're right, I'm not thinking straight. I can cherry-pick the commit and and make a PR :)

**Closed** 2016-08-22 17:41 UTC
