### ISSUE TITLE
Support for Asserts

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1146] opened 2016-07-11 19:04 UTC
As a pipeline author, I would like the ability to add assert-like statements to my tasks.  For example, after the task has run check the output log for the presence of some message.  This is important because we often find problems in the pipelines that we could have detected with some basic checks that could be part of the pipeline.  They are different than unit tests because these problems often only arise under unusual data conditions that are hard to predict.

The current approach on this is for @yfarjoun to test run these ideas just within the command block of WDL as a way to figure out what this feature really looks like.  Then from that set of we can figure out what features need to be added in order to support this in a natural, DRY way

**Comment by cjllanwarne** [comment] 2016-12-20 22:21
With the conditionals, this feels more like it would be better as an "add a `fail` method" ticket rather than explicit `assert` statements?

**Comment by yfarjoun** [comment] 2016-12-21 00:55
The difference is that as a fail method I would need to explicitly declare
as output all of the logs, while this way I can keep the logs in the
execution directory and still operate on them within the task.

**Comment by cjllanwarne** [comment] 2017-01-27 21:54
@yfarjoun Is this good enough as an interim?
```
task foo {
  command {
    # do some stuff...
    # verify and write results to verification.txt
  }
  output {
    # normal outputs
    # Boolean verification = read_bool(verification.txt)
  }
}

task fail {
  command { 
    # something guaranteed to fail
  }
}

workflow bar {
  call foo
  if (!foo.verification) { call fail }
}
```

**Comment by yfarjoun** [comment] 2017-01-27 22:03
Not really. The problem is that then the command has to be written very
carefully so that errors in intermediate steps propagate...we already have
this problem, but this will make it worse.

**Comment by yanlinlin82** [comment] 2017-01-31 05:57
Sounds like some syntactic sugars are expected to simplify the fail method declaration.

In addition, will such 'assert' be dynamic (in run-time) or static (in parse-time, before running any task)?

**Comment by yfarjoun** [comment] 2017-01-31 13:26
This should be a dynamic assert, based on the results of the task.
validation can take a while, so I would like the output to be taken and
given to the next task in the workflow while the validation is happening. I
would also like to control the response of the run (fail and stop, fail but
continue, warn and continue, do not validate) if there's an assertion
failure.

**Comment by yanlinlin82** [comment] 2017-01-31 16:46
I see. My usual "workaround" for such fail (but continue) is like this:

```
task foo {
	command {
		(echo foo; false) || (echo 1>&2 MSG; true)
	}
}

workflow test {
	call foo
}
```

**Comment by yfarjoun** [comment] 2017-01-31 17:01
Right, but I want to know what happened...not that a tool fails silently...

**Comment by katevoss** [comment] 2017-08-21 21:21
@yfarjoun can you explain in more depth what kind of tool you are looking for? When you need it, what it would do, etc.

@cjllanwarne do you have an idea of how much an effort like that would take?

**Comment by yfarjoun** [comment] 2017-08-25 10:08
I think that we all got used to the workarounds by now, and there are bigger fish to fry...I suggest we close this.

**Closed** 2017-08-25 15:28 UTC
Labels: PO Cleanup, UserSupport ❤️
