### ISSUE TITLE
Error in Cromwell 24 on method that works in Cromwell 21

### ISSUE THREAD

**Issue by tmdefreitas** [broadinstitute/cromwell#1937] opened 2017-02-01 18:22 UTC
We were recently told that FireCloud has updated it's Cromwell version to 0.24. For our local testing, we had previously been using Cromwell 0.21, so I was trying to upgrade our build system to use 0.24 as well. However, v0.24 seems to have some regressions with respect to our WDLs. In addition after encountering the error cromwell is unkillable without `kill -9`.

To reproduce (Note: I am using OSX 10.10.5) :

1. Download and unzip [cromwell_24_bug.zip](https://github.com/broadinstitute/cromwell/files/745711/cromwell_24_bug.zip)

2. Get v0.21 of cromwell, to verify that the existing WDL runs
```bash
$ cd cromwell_24_bug
$ curl -L -o cromwell-21.jar https://github.com/broadinstitute/cromwell/releases/download/0.21/cromwell-0.21.jar
$ java -jar cromwell-21.jar run tool_icomut.wdl inputs.json
```
The workflow should succeed.
```
...
[2017-02-01 13:18:32,36] [info] WorkflowManagerActor WorkflowActor-5e2fd288-37a5-44d2-ab8a-a65b2fb5179d is in a terminal state: WorkflowSucceededState
{
  "outputs": {
    "tool_icomut_workflow.tool_icomut.iCoMut_table": "/Users/timdef/tmp/cromwell_24_bug/cromwell-executions/tool_icomut_workflow/5e2fd288-37a5-44d2-ab8a-a65b2fb5179d/call-tool_icomut/execution/TCGA-ACC.coMut_table.txt"
  },
  "id": "5e2fd288-37a5-44d2-ab8a-a65b2fb5179d"
}
[2017-02-01 13:18:34,64] [info] SingleWorkflowRunnerActor workflow finished with status 'Succeeded'.
```

3. Now download v0.24, and retry:
```bash
$ curl -L -o cromwell-24.jar https://github.com/broadinstitute/cromwell/releases/download/24/cromwell-24.jar
$ java -jar cromwell-24.jar run tool_icomut.wdl inputs.json
```

The workflow now fails:
```
...
[2017-02-01 13:08:17,13] [error] BackgroundConfigAsyncJobExecutionActor [c290b1fftool_icomut_workflow.tool_icomut:NA:1]: Error attempting to Execute
java.lang.UnsupportedOperationException: Could not find declaration for WdlOptionalValue(WdlFileType,None)
	at wdl4s.command.ParameterCommandPart.instantiate(ParameterCommandPart.scala:48)
	at wdl4s.Task$$anonfun$instantiateCommand$1$$anonfun$apply$2.apply(Task.scala:108)
	at wdl4s.Task$$anonfun$instantiateCommand$1$$anonfun$apply$2.apply(Task.scala:108)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
...
```

**Comment by tmdefreitas** [comment] 2017-02-01 18:32
This appears to be related to the optional input, removing the optional `clinical_features` parameter and deleting the entry from the command line allows the workflow to succeed.

**Comment by eddiebroad** [comment] 2017-02-01 19:30
@tmdefreitas I observed/experienced a similar issue.  I had a WDL with an optional input.  It was optional because its type was "File?".  I was passing in the input when issuing a submission on FireCloud.  Using the developer tab I saw the error 

```
"failures": [{
    "message": "Couldn't resolve all inputs for CallingGroup_Workflow.CallSomaticMutations_131_Prepare_Task at index None.: Input evaluation for Call CallingGroup_Workflow.CallSomaticMutations_131_Prepare_Task failed.:\n\tnormalPanelSize:\n\tFile not found fc-2edc2716-272a-438a-b458-25dbee1e253d/eb1f9669-ce6c-462d-950d-630b321ddc1f/CallingGroup_Workflow/096768d6-9e90-4d1d-81c7-f909559a1a55/call-CallSomaticMutations_131_Prepare_Task/\"gs:/firecloud-tcga-open-access/tutorial/reference/refseq_exome_10bp_hg19_300_1kg_normal_panel.vcf\""
  }],
```

I note two things.  First, I note as I mentioned that I was passing in the file and so the error "File Not found" does not make sense.  Second, I note that the gsURL has only one "/" after the "gs" ; in contrast the file IS where it is and in the workspace attribute (where it is pulled from) it is there and the file preview worked.  

To be able to successfully use the WDL I removed the "?" so that it's a plain "non-optional" input.  After removing the "?" I was able to successfully run the WDL.

**Comment by cjllanwarne** [comment] 2017-02-01 19:37
There were indeed a few regressions around optionals introduced when we implemented the conditionals. They should be fixed in C25, so if your WDL has a pattern like anything in the following test case, it should be good: https://github.com/broadinstitute/centaur/blob/develop/src/main/resources/standardTestCases/optional_parameter/optional_parameter.wdl

I'll add another test for the optional file input since it's not a case I was aware of. I believe @kshakir has been fixing a lot of file path manipulations recently so it might also be good in C25.

**Comment by cjllanwarne** [comment] 2017-02-01 22:30
I'm closing this ticket because the issue is addressed in our next release (and our develop branch, in case you're feeling brave). I've also added and started working on https://github.com/broadinstitute/cromwell/issues/1940 for the `File?` inputs bug.

**Closed by cjllanwarne** 2017-02-01 22:30 UTC
