### ISSUE TITLE
Cromwell 34 Hotfix -- stdout path mismatches metadata expectations

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4166] opened 2018-09-27 16:00 UTC
![screen shot 2018-09-27 at 11 52 59 am](https://user-images.githubusercontent.com/14941133/46158478-eda2b800-c24b-11e8-9987-94fec95bb97d.png)

It seems that on Cromwell 34 hotfix -- the name of the stdout/stderr files are:
`.../<call-name>-stdout.log`
`.../<call-name>-stderr.log`

However, the call metadata reports stdout/stderr locations to be:
`.../<call-name>/stdout`
`.../<call-name>/stderr`

AC: Ensure that the metadata values for log paths match up to actual log paths.

This impacts FC and Job Manager users on Cromwell 34 hotfix.

**Comment by mcovarr** [comment] 2018-09-27 17:11
I haven't been able to reproduce this on 34_hotfix or develop. Standard output and error filenames are `stdout` and `stderr` in both the metadata and IRL.

**Comment by mcovarr** [comment] 2018-09-27 17:12
Assuming this was reported against prod FC I'll figure out what hash they're currently using and try again with that.

**Comment by mcovarr** [comment] 2018-09-27 18:17
Can't reproduce on the prod FC hash. Reassigning back to you since I'm blocked at the moment.

**Comment by tmm211** [comment] 2018-09-27 20:32
Is it possible for you to inform me or Beri when this is released, so that we can update the folks on this thread: https://gatkforums.broadinstitute.org/firecloud/discussion/comment/52504#Comment_52504

**Comment by mcovarr** [comment] 2018-09-27 23:06
Ugh repro'd on PAPI v1, assigning back to me.

**Closed** 2018-10-02 13:46 UTC
Labels: 🐛Bug
