### ISSUE TITLE
Private DockerHub Support v2

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#3844] opened 2018-07-02 16:57 UTC
PAPI V1 had a different way of handling private dockerhub credentials and there needs to be a new methodology to pass credentials for operations in PAPI v2. 

Implement a system that allows a user to be able to pass in dockerhub credentials securely to their jobs container so a user can pull private docker images.

**Comment by mcovarr** [comment] 2018-07-13 14:12
appears to be a dupe of #3587

**Closed by mcovarr** 2018-07-13 14:12 UTC
