### ISSUE TITLE
Log every call to Google

### ISSUE THREAD

**Issue by dvoet** [broadinstitute/cromwell#1368] opened 2016-09-01 13:58 UTC
having a log of every call made to google is of tremendous value when trouble shooting google related issues. Here is the code that rawls uses: https://github.com/broadinstitute/rawls/blob/0ce87caf4e52cc4df83d286ef49d4d56d91b590f/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala#L867

This information is also valuable because we have hard evidence when we say api calls are slow.

**Comment by geoffjentry** [comment] 2016-12-27 03:19
If this is ever implemented it should be `DEBUG` or a configurable option w/ a warning about the potential performance impact

**Comment by katevoss** [comment] 2017-08-23 21:40
@dvoet do you have any better logging these days? Can you tell me more about what you are looking for when you need the Google logs?

**Comment by geoffjentry** [comment] 2017-08-23 21:42
He wants us to emit a log message on every HTTP call to a google service, and we still don't do that.

**Comment by geoffjentry** [comment] 2017-08-23 23:25
Fwiw this *is* a good idea for the sort of production purpose @dvoet has in mind. The issue is that we'd have an angry mob of other users if we ever did this. 

This goes into that "we need to not emit a one size fits all log" topic

**Comment by katevoss** [comment] 2017-08-28 19:57
Tracking this in the [Logging Spec document](https://docs.google.com/document/d/1Dc37EaPDoWXacSSzLgCdndx9zo5k6EmE5tvg-2fisPo/edit).

**Comment by katevoss** [comment] 2017-08-28 19:58
As a **super-user**, I want **to see every call Cromwell made to Google**, so that I can **debug what is wrong with Cromwell**.
- Effort: **Low**
- Risk: **Medium**
- - Need to make sure regular users don't see these logs, so that these are not visible by default.
- Business value: **Medium**

**Comment by ruchim** [comment] 2018-09-27 02:49
@geoffjentry @dvoet is this still a need? is this the only way to show proof for the fact that api calls can be slow?

**Comment by geoffjentry** [comment] 2018-09-27 03:07
No

**Comment by ruchim** [comment] 2018-09-27 12:57
@dvoet This may not be a very practical approach for Cromwell. I wonder if there is something else that can watch this traffic and speed of http responses. I'm closing this issue for now as its likely something we won't do in the near-term future but please re-open if you feel there's a strong case for it.

**Closed by ruchim** 2018-09-27 12:57 UTC
Labels: Logs, User Requested Improvement
