### ISSUE TITLE
What should be a transient Google credential error is fatal, not transient

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1436] opened 2016-09-17 11:28 UTC
@ruchim has the stack trace from 9/16 JG testing

**Comment by ruchim** [comment] 2016-09-17 16:48
`2016-09-16 14:45:19,558 cromwell-system-akka.dispatchers.backend-dispatcher-86 ERROR - Google credentials are invalid: Connection reset
akka.actor.ActorInitializationException: akka://cromwell-system/user/cromwell-service/WorkflowManagerActor/WorkflowActor-d86697f6-ca39-417b-b575-fc955c808983/WorkflowExecutionActor-d86697f6-ca39-417b-b575-fc955c808983/d86697f6-ca39-417b-b575-fc955c808983-EngineJobExecutionActor-DeliciousFileSpam.FileSpam:364:1/d86697f6-ca39-417b-b575-fc955c808983-BackendJobExecutionActor-d86697f6:DeliciousFileSpam.FileSpam:364:1/JesAsyncBackendJobExecutionActor: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:174)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Google credentials are invalid: Connection reset
	at cromwell.filesystems.gcs.GoogleAuthMode$class.validateCredentials(GoogleAuthMode.scala:79)
	at cromwell.filesystems.gcs.ApplicationDefaultMode.validateCredentials(GoogleAuthMode.scala:137)
	at cromwell.filesystems.gcs.GoogleAuthMode$class.credential(GoogleAuthMode.scala:63)
	at cromwell.filesystems.gcs.ApplicationDefaultMode.credential(GoogleAuthMode.scala:137)
	at cromwell.filesystems.gcs.GoogleAuthMode$class.buildStorage(GoogleAuthMode.scala:94)
	at cromwell.filesystems.gcs.ApplicationDefaultMode.buildStorage(GoogleAuthMode.scala:137)
	at cromwell.backend.impl.jes.JesWorkflowPaths.<init>(JesWorkflowPaths.scala:30)
	at cromwell.backend.impl.jes.JesCallPaths.<init>(JesCallPaths.scala:16)
	at cromwell.backend.impl.jes.JesCallPaths$.apply(JesCallPaths.scala:11)
	at cromwell.backend.impl.jes.JesWorkflowPaths.toJesCallPaths(JesWorkflowPaths.scala:42)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.jesCallPaths$lzycompute(JesAsyncBackendJobExecutionActor.scala:108)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.jesCallPaths(JesAsyncBackendJobExecutionActor.scala:108)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.cromwell$backend$impl$jes$JesAsyncBackendJobExecutionActor$$callRootPath(JesAsyncBackendJobExecutionActor.scala:115)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.<init>(JesAsyncBackendJobExecutionActor.scala:170)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor$$anonfun$props$1.apply(JesAsyncBackendJobExecutionActor.scala:49)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor$$anonfun$props$1.apply(JesAsyncBackendJobExecutionActor.scala:49)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	... 9 common frames omitted
`

**Comment by geoffjentry** [comment] 2016-12-18 17:30
This might be related to #1782 somehow, I believe I've seen these in some of the errorstorms which wind up w/ the symptoms described in #1782

**Comment by katevoss** [comment] 2017-03-13 16:03
Closing this, track #1886

**Closed by katevoss** 2017-03-13 16:03 UTC
