### ISSUE TITLE
latest snapshot of cromwell freezes when folder is given as File input

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#3383] opened 2018-03-09 01:30 UTC
What I started to get from time to time is that some jobs keep running forever while no files are created in its executions folder (incl. technical files like script and script.submit). If happens (althoug not deterministically, I cannot get 100% reproducibility) in the latest versions (like cromwell-31-d84be2e-SNAP.jar) of cromwell when I have folders as File inputs for both workflow and tasks.
When I looked into cromwell logs I noticed:
```
[ERROR] [03/09/2018 00:55:25.108] [cromwell-system-akka.dispatchers.engine-dispatcher-27] [akka://cromwell-system/user/cromwell-service/WorkflowManager
Mar 09 00:55:25 web start-cromwell.sh[110916]: java.io.IOException: Is a directory
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at sun.nio.ch.IOUtil.read(IOUtil.java:197)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at org.apache.commons.codec.digest.DigestUtils.updateDigest(DigestUtils.java:794)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at org.apache.commons.codec.digest.DigestUtils.digest(DigestUtils.java:50)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at org.apache.commons.codec.digest.DigestUtils.md5(DigestUtils.java:274)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at org.apache.commons.codec.digest.DigestUtils.md5Hex(DigestUtils.java:310)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.backend.impl.sfs.config.HashFileStrategy.$anonfun$hash$3(ConfigHashingStrategy.scala:82)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.util.TryWithResource$.$anonfun$tryWithResource$1(TryWithResource.scala:16)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at scala.util.Try$.apply(Try.scala:209)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.util.TryWithResource$.tryWithResource(TryWithResource.scala:10)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.backend.impl.sfs.config.HashFileStrategy.hash(ConfigHashingStrategy.scala:82)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.backend.impl.sfs.config.ConfigHashingStrategy.usingStandardInitData$1(ConfigHashingStrategy.scala:52)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.backend.impl.sfs.config.ConfigHashingStrategy.getHash(ConfigHashingStrategy.scala:57)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.backend.impl.sfs.config.ConfigBackendFileHashingActor.customHashStrategy(ConfigBackendFileHashingActor.scala:26)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.backend.standard.callcaching.StandardFileHashingActor$$anonfun$fileHashingReceive$1.applyOrElse(StandardFileHashingActor.scala:73)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.actor.Actor.aroundReceive(Actor.scala:514)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.actor.Actor.aroundReceive$(Actor.scala:512)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at cromwell.backend.standard.callcaching.StandardFileHashingActor.aroundReceive(StandardFileHashingActor.scala:59)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.actor.ActorCell.invoke(ActorCell.scala:496)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.dispatch.Mailbox.run(Mailbox.scala:224)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Mar 09 00:55:25 web start-cromwell.sh[110916]:         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
the minimal workflow that caused this (although not all 100% of the time) is:
```
workflow quantification_broken {

    File batch
    File references
    File samples_folder #folder provided as File, before now it worked perfectly

    Boolean keep_sra = true
    Int threads


    call prepare_samples {
        input: samples = batch, references = references, samples_folder = samples_folder
    }
}


task prepare_samples {
    File samples
    File references
    File samples_folder

    command {
        echo "whatever command you want"
    }

    output {
        File invalid = "invalid.tsv"
        File novel = "novel.tsv"
        File cached = "cached.tsv"
    }
}
```
I understand that there is plan to introduce Directory type in the future. But it may take long ago and it is better not to break current workflows where people have to use File for Directory inputs.

**Comment by antonkulaga** [comment] 2018-03-09 09:31
I also constantly get:
` Localization via hard link has failed`

**Comment by geoffjentry** [comment] 2018-08-18 20:28
Hi @antonkulaga - the fact that you're able to wire in a directory into a `File` is not intended behavior and thus a bug. As you're aware there's a discussion on OpenWDL regarding the `Directory` type. closing in favor of that.

**Closed by geoffjentry** 2018-08-18 20:28 UTC

**Comment by antonkulaga** [comment] 2018-08-18 21:11
>. As you're aware there's a discussion on OpenWDL regarding the Directory type. closing in favor of that.

The key question is when are you going to add Directory type to cromwell? I am quite pragmatic regarding cromwell, many tools in my pipeline require folders instead of files and I have to make it work somehow

**Comment by geoffjentry** [comment] 2018-08-18 21:13
After it is part of the WDL spec.

You can continue to stick directories into `File` objects, just know that it's not supported and you might find edge cases.
