### ISSUE TITLE
Optional input not being prefaced with localized path at runtime (cromwell 24, on laptop)

### ISSUE THREAD

**Issue by noblem** [broadinstitute/cromwell#1983] opened 2017-02-14 15:17 UTC
In the attached WDL, note that the input_table parameter is fed to an executing R script using the optional inputs syntax:   ${"-t"+input_table}.   In the attached bad-script.txt file (the "script" file generated by cromwell at runtime), note that the file given to the -t flag does not begin with an absolute path localized to the execution container.  This yields a "file not found" problem at runtime (as shown in the attached bad-stderr.txt).

If I simply change the WDL syntax to -t${input_table} then execute the same test with the exact same inputs, the -t flag is properly prefixed with an absolute path localized to the container (as shown in script-good.txt), enabling the file to be found and the successful completion of the workflow.

[bad-stderr.txt](https://github.com/broadinstitute/cromwell/files/774453/bad-stderr.txt)
[bad-script.txt](https://github.com/broadinstitute/cromwell/files/774447/bad-script.txt)
[example_wdl.txt](https://github.com/broadinstitute/cromwell/files/774444/example_wdl.txt)
[good-script.txt](https://github.com/broadinstitute/cromwell/files/774491/good-script.txt)

**Comment by cjllanwarne** [comment] 2017-02-14 16:01
I believe this is fixed in `develop`. It looks just like the new centaur test `interpolation_additions` in https://github.com/broadinstitute/centaur/blob/develop/src/main/resources/standardTestCases/optional_parameter/optional_parameter.wdl

@noblem - FWIW, your input is not optional in that WDL, so your proposed fix of `-t ${input_table}` should be functionally identical to `${"-t " + input_table}` in this case.

**Comment by cjllanwarne** [comment] 2017-02-14 16:09
Closing as duplicate of #1875.

**Closed by cjllanwarne** 2017-02-14 16:09 UTC
