### ISSUE TITLE
Adding "sleep 2" should not be necessary for Local Backend to work

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1894] opened 2017-01-23 18:32 UTC
Centaur tests should reliably pass even when they don't have a `sleep 2` suffixed to the command block.

**Comment by mcovarr** [comment] 2017-01-23 18:32
+1000

**Comment by geoffjentry** [comment] 2017-01-23 18:48
@cjllanwarne I think this is a dupe of #1868?

**Comment by ruchim** [comment] 2017-03-06 14:21
Closed by https://github.com/broadinstitute/centaur/pull/158

**Closed by ruchim** 2017-03-06 14:21 UTC
Labels: Bug, Low
