### ISSUE TITLE
Implementation details exposed in normal command-line output

### ISSUE THREAD

**Issue by dmohs** [broadinstitute/cromwell#4062] opened 2018-08-30 17:59 UTC
Command:
```bash
$ java -jar jars/cromwell-34.jar run hello_world/hello_world_0.wdl
```
Output:
```
[2018-08-30 17:53:11,17] [info] Running with database db.url = jdbc:hsqldb:mem:4fbaa426-09e6-4c70-9a1a-15469c4d77a0;shutdown=false;hsqldb.tx=mvcc
[2018-08-30 17:53:19,24] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2018-08-30 17:53:19,26] [info] [RenameWorkflowOptionsInMetadata] 100%
[2018-08-30 17:53:19,39] [info] Running with database db.url = jdbc:hsqldb:mem:146c8707-d56e-4f58-a2de-df327f328109;shutdown=false;hsqldb.tx=mvcc
[2018-08-30 17:53:20,13] [info] Slf4jLogger started
[2018-08-30 17:53:20,68] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-232861f",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2018-08-30 17:53:20,92] [info] Metadata summary refreshing every 2 seconds.
[2018-08-30 17:53:21,02] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2018-08-30 17:53:21,03] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-08-30 17:53:21,03] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-08-30 17:53:21,89] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2018-08-30 17:53:21,95] [info] SingleWorkflowRunnerActor: Version 34
[2018-08-30 17:53:21,97] [info] SingleWorkflowRunnerActor: Submitting workflow
[2018-08-30 17:53:22,05] [info] Unspecified type (Unspecified version) workflow 4dbd7d1c-e7e8-4f83-9750-5c638d1567bc submitted
[2018-08-30 17:53:22,16] [info] SingleWorkflowRunnerActor: Workflow submitted 4dbd7d1c-e7e8-4f83-9750-5c638d1567bc
[2018-08-30 17:53:22,16] [info] 1 new workflows fetched
[2018-08-30 17:53:22,16] [info] WorkflowManagerActor Starting workflow 4dbd7d1c-e7e8-4f83-9750-5c638d1567bc
[2018-08-30 17:53:22,17] [info] WorkflowManagerActor Successfully started WorkflowActor-4dbd7d1c-e7e8-4f83-9750-5c638d1567bc
[2018-08-30 17:53:22,17] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2018-08-30 17:53:22,18] [warn] SingleWorkflowRunnerActor: received unexpected message: Done in state RunningSwraData
[2018-08-30 17:53:22,20] [warn] Couldn't find a suitable DSN, defaulting to a Noop one.
[2018-08-30 17:53:22,21] [info] Using noop to send events.
[2018-08-30 17:53:22,25] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2018-08-30 17:53:22,30] [info] MaterializeWorkflowDescriptorActor [4dbd7d1c]: Parsing workflow as WDL draft-2
[2018-08-30 17:53:23,48] [info] MaterializeWorkflowDescriptorActor [4dbd7d1c]: Call-to-Backend assignments: HelloWorld.WriteGreeting -> Local
[2018-08-30 17:53:24,95] [info] WorkflowExecutionActor-4dbd7d1c-e7e8-4f83-9750-5c638d1567bc [4dbd7d1c]: Starting HelloWorld.WriteGreeting
[2018-08-30 17:53:26,42] [info] BackgroundConfigAsyncJobExecutionActor [4dbd7d1cHelloWorld.WriteGreeting:NA:1]: echo "Hello World"
[2018-08-30 17:53:26,49] [info] BackgroundConfigAsyncJobExecutionActor [4dbd7d1cHelloWorld.WriteGreeting:NA:1]: executing: /bin/bash /gatk/wsb/cromwell-executions/HelloWorld/4dbd7d1c-e7e8-4f83-9750-5c638d1567bc/call-WriteGreeting/execution/script
[2018-08-30 17:53:31,09] [info] BackgroundConfigAsyncJobExecutionActor [4dbd7d1cHelloWorld.WriteGreeting:NA:1]: job id: 115
[2018-08-30 17:53:31,10] [info] BackgroundConfigAsyncJobExecutionActor [4dbd7d1cHelloWorld.WriteGreeting:NA:1]: Status change from - to Done
[2018-08-30 17:53:33,13] [info] WorkflowExecutionActor-4dbd7d1c-e7e8-4f83-9750-5c638d1567bc [4dbd7d1c]: Workflow HelloWorld complete. Final Outputs:
{
  "HelloWorld.WriteGreeting.outfile": "/gatk/wsb/cromwell-executions/HelloWorld/4dbd7d1c-e7e8-4f83-9750-5c638d1567bc/call-WriteGreeting/execution/stdout"
}
[2018-08-30 17:53:33,18] [info] WorkflowManagerActor WorkflowActor-4dbd7d1c-e7e8-4f83-9750-5c638d1567bc is in a terminal state: WorkflowSucceededState
[2018-08-30 17:53:36,13] [info] SingleWorkflowRunnerActor workflow finished with status 'Succeeded'.
{
  "outputs": {
    "HelloWorld.WriteGreeting.outfile": "/gatk/wsb/cromwell-executions/HelloWorld/4dbd7d1c-e7e8-4f83-9750-5c638d1567bc/call-WriteGreeting/execution/stdout"
  },
  "id": "4dbd7d1c-e7e8-4f83-9750-5c638d1567bc"
}
[2018-08-30 17:53:41,12] [info] Workflow polling stopped
[2018-08-30 17:53:41,13] [info] Shutting down WorkflowStoreActor - Timeout = 5 seconds
[2018-08-30 17:53:41,14] [info] Aborting all running workflows.
[2018-08-30 17:53:41,15] [info] WorkflowStoreActor stopped
[2018-08-30 17:53:41,15] [info] Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
[2018-08-30 17:53:41,15] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2018-08-30 17:53:41,15] [info] JobExecutionTokenDispenser stopped
[2018-08-30 17:53:41,17] [info] WorkflowLogCopyRouter stopped
[2018-08-30 17:53:41,17] [info] Shutting down WorkflowManagerActor - Timeout = 3600 seconds
[2018-08-30 17:53:41,17] [info] WorkflowManagerActor All workflows finished
[2018-08-30 17:53:41,17] [info] WorkflowManagerActor stopped
[2018-08-30 17:53:41,17] [info] Connection pools shut down
[2018-08-30 17:53:41,18] [info] Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
[2018-08-30 17:53:41,18] [info] SubWorkflowStoreActor stopped
[2018-08-30 17:53:41,18] [info] Shutting down JobStoreActor - Timeout = 1800 seconds
[2018-08-30 17:53:41,18] [info] Shutting down CallCacheWriteActor - Timeout = 1800 seconds
[2018-08-30 17:53:41,19] [info] CallCacheWriteActor Shutting down: 0 queued messages to process
[2018-08-30 17:53:41,19] [info] CallCacheWriteActor stopped
[2018-08-30 17:53:41,18] [info] Shutting down ServiceRegistryActor - Timeout = 1800 seconds
[2018-08-30 17:53:41,19] [info] Shutting down DockerHashActor - Timeout = 1800 seconds
[2018-08-30 17:53:41,19] [info] KvWriteActor Shutting down: 0 queued messages to process
[2018-08-30 17:53:41,19] [info] WriteMetadataActor Shutting down: 0 queued messages to process
[2018-08-30 17:53:41,19] [info] DockerHashActor stopped
[2018-08-30 17:53:41,19] [info] Shutting down IoProxy - Timeout = 1800 seconds
[2018-08-30 17:53:41,19] [info] JobStoreActor stopped
[2018-08-30 17:53:41,19] [info] IoProxy stopped
[2018-08-30 17:53:41,19] [info] ServiceRegistryActor stopped
[2018-08-30 17:53:41,23] [info] Database closed
[2018-08-30 17:53:41,23] [info] Stream materializer shut down
[2018-08-30 17:53:41,29] [info] Automatic shutdown of the async connection
[2018-08-30 17:53:41,29] [info] Gracefully shutdown sentry threads.
[2018-08-30 17:53:41,29] [info] Shutdown finished.
```
Command-line tools are subject to usability standards identical to those of our other user interfaces. Unless the intended audience of this tool is Cromwell engineers, the class names in the above output are misleading. For example, in the line:
```
CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
```
a user may want to investigate the terms "batch size" and "process rate" through the documentation or forums, which will likely have meaning. CallCacheWriteActor, on the other hand, is likely an implementation detail that probably adds confusion rather than clarity.

hello_world_0.wdl:
```wdl
workflow HelloWorld {

	call WriteGreeting
}

task WriteGreeting {

	command {
		echo "Hello World"
	}
	output {
		File outfile = stdout()
	}
}
```

**Comment by geoffjentry** [comment] 2018-08-30 18:07
@dmohs I can't find it at the moment but this is effectively a dupe of another ticket.

It's been a known problem for years now that the logs Cromwell emits (console or otherwise) are trying to cover multiple user personas at once (and IMO not doing a great job for any of them) and that a more holistic solution needs to be put into place. 

When I find the ticket I redirect all of this stuff towards I'll update

**Closed by geoffjentry** 2018-08-30 18:07 UTC
