### ISSUE TITLE
CWL resource keys in wrong unit for SLURM

### ISSUE THREAD

**Issue by Shenglai** [broadinstitute/cromwell#4080] opened 2018-09-10 19:24 UTC
Hi all

I've been playing the CWL ResourceRequirement with cromwell under SLURM env.
https://www.commonwl.org/v1.0/CommandLineTool.html#ResourceRequirement

So, if I submit a CWL with
```
- class: ResourceRequirement
    coresMin: 1
    coresMax: 1
    ramMin: 2000
    ramMax: 2000
```
The cromwell will send the command to SLURM with a ridiculously high value of memory
```
executing: sbatch --nodes 1 --ntasks 1 \
--cpus-per-task=1 --mem-per-cpu=2097152000 \
```
And most likely it will fail because we do not have such a beefy flavor node, since SLURM reads the memory in MB.
```
sbatch: error: Batch job submission failed: Requested node configuration is not available
```
More tests like using different units or numbers will lead to similar errors:
Submit
```
- class: ResourceRequirement
    coresMin: 1
    coresMax: 1
    ramMin: 2GB
    ramMax: 2GB
```
will give me
```
executing: sbatch --nodes 1 --ntasks 1 \
--cpus-per-task=1 --mem-per-cpu=2000000000 \
```
and
```
- class: ResourceRequirement
    coresMin: 1
    coresMax: 1
    ramMin: 2
    ramMax: 2
```
gives me
```
executing: sbatch --nodes 1 --ntasks 1 \
--cpus-per-task=1 --mem-per-cpu=2097152 \
```
more for
```  - class: ResourceRequirement
    coresMin: 1
    coresMax: 1
    ramMin: 2000MB
    ramMax: 2000MB
```
it will give
```
executing: sbatch --nodes 1 --ntasks 1 \
--cpus-per-task=1 --mem-per-cpu=2000000000 \
```

So, it seems cromwell will read the numbers in MB and transfer it in bytes to SLURM. However, SLURM probably needs memory in MB as well. (I assume it is a bug when mapping CWL resource key to WDL)

Currently, I manage to use an expression in the config `memoryMin/1000000` to circumvent the issue.
I don't think it is a very major issue nor a complex one, so feel free to fix it whenever.

The cromwell version is the latest release, cromwell-34, and please find my working config if necessary.

[cromwell.slurm.conf.gz](https://github.com/broadinstitute/cromwell/files/2368103/cromwell.slurm.conf.gz)

**Comment by ruchim** [comment] 2018-11-15 19:46
Hey @Shenglai,

Although this isn't well documented, but for each scheduler based backend (such as SLURM), on has to configure the backend with the memory units required for the scheduler. And without this conversion, Cromwell doesn't assume what needs to be sent to the scheduler. I believe we just need to improve the documentation, but I do believe the intended behavior is that Cromwell always converts declared memory into bytes by default, and backends can be configured to use other units. 

Let me know if you have any questions, and I'll be closing this issue if there are no questions/concerns.

Thanks

**Comment by geoffjentry** [comment] 2018-11-15 20:19
@ruchim **NB** https://github.com/broadinstitute/cromwell/issues/3382

**Closed** 2019-07-23 21:16 UTC
