### ISSUE TITLE
Detect error 500 in JES backend and retry job

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1450] opened 2016-09-20 13:57 UTC
- cromwell pre-0.21 dev snapshot
- JES backend
- command line execution (single workflow) 

Current behavior, which happens frequently:
- Mysterious error 500 appears on cromwell stdout.  Apologies that I do not have example.  
- cromwell hangs.  One time, cromwell was left running overnight and no progress was made.
- ctl-c which ends cromwell
- up arrow and return
- job completes successfully

Can cromwell detect these errors on JES and retry the jobs?

More observations:
- These were never seen on local backend.  On JES, these were common.
- All jobs were self-contained.  I.e. did not hit a web service nor make a HTTP request.

**Comment by cjllanwarne** [comment] 2017-01-31 21:38
Closing this as a duplicate of our retry goals.

**Closed by cjllanwarne** 2017-01-31 21:38 UTC
