### ISSUE TITLE
FireCloud - cromwell losing jobs?

### ISSUE THREAD

**Issue by dvoet** [broadinstitute/cromwell#1965] opened 2017-02-08 20:18 UTC
We are seeing infrequent situations where JES says a call is done but cromwell thinks it is still running.

I see the call starting in the logs:
```
2017-02-08 18:55:58,500 cromwell-system-akka.dispatchers.engine-dispatcher-963 INFO - WorkflowExecutionActor-fa7e25a2-f51f-4763-9f8a-5a2e5cd1c954 [UUID(fa7e25a2)]: Starting calls: pon_gatk_workflow.PadTargets:NA:1
```

Then the only suspicious things I see later in the logs are these messages (which could be completely unrelated however they do start to appear 2.5 minutes after the job completes on JES):
```
2017-02-08 19:17:07,588 cromwell-system-akka.dispatchers.backend-dispatcher-424 INFO - The JES polling actor Actor[akka://cromwell-system/user/cromwell-service/$b/$a/$Enn#762671444] unexpectedly terminated while conducting 100 polls. Making a new one...
java.lang.NullPointerException: null
2017-02-08 19:17:07,588 cromwell-system-akka.dispatchers.backend-dispatcher-246 ERROR - null
```

For future reference by a FireCloud admin the operations id is ELSl1PihKxjdhp-6gvr3weYBILma7PWMHyoPcHJvZHVjdGlvblF1ZXVl and the workflow id is fa7e25a2-f51f-4763-9f8a-5a2e5cd1c954 and the workflow was aborted 3PM Feb 8.

**Comment by dvoet** [comment] 2017-02-09 19:46
a second attempt of this workflow (840769fa-dabc-45d7-8dc8-9158b5294c9f) eventually failed but passed the point of the prior trial on the same cromwell instance 30m later making it seem like there is not an overall backup in the system.

**Comment by dvoet** [comment] 2017-02-10 17:02
I am seeing this NPE a ton in our production logs and could also be a cause of jobs generally not progressing.

**Comment by geoffjentry** [comment] 2017-02-10 17:26
Yeah I was going to try to take a look today. It shouldn't be too hard to localize as any `null` is going to be coming from Google's java library. It'll probably require some logging to get more data though.

**Comment by kcibul** [comment] 2017-02-10 17:29
Given the potential impact of this, I'd like to prioritize this @geoffjentry @katevoss .  I think the the new policy is to add the priority label, right?  and bug wise, if confirmed, I'd say this is a P2 as there is a painful workaround (but still a priority ticket).

**Comment by katevoss** [comment] 2017-02-10 17:39
@kcibul sounds like this is a bug, I'll add that label. If confirmed I'll switch it over to High (P2).

**Comment by kcibul** [comment] 2017-02-10 17:41
cool -- yeah I'm already rethinking using the Px over High/Med/Low ;)

**Comment by geoffjentry** [comment] 2017-02-10 17:45
One quick thing that could be done to see if the NPE is related to other undesired behavior.

In JesApiQueryManager.handleTerminated I put in some logic a while back to automatically retry any polling actor which failed under the belief that it was going to be some goofy google error. That'd also be picking up actors which died via NPE. Changing it we're either specially handling NPE or being specific about what *is* being handled (which should be part of #1914 anyways) would make this better

**Comment by ruchim** [comment] 2017-03-06 14:03
Hey @kshakir, can this issue be considered closed by https://github.com/broadinstitute/cromwell/pull/2015?

**Comment by geoffjentry** [comment] 2017-03-06 14:05
@ruchim probably but i don't think we can know for sure until FC is shown to not be losing jobs

**Comment by ruchim** [comment] 2017-03-06 14:11
Spoke to @dvoet and he mentioned that since FC hasn't seen any more of the same symptoms (NPE's and jobs getting lost) for some time now, we can consider this issue resolved for now.

**Closed by ruchim** 2017-03-06 14:11 UTC
Labels: Bug, High
