### ISSUE TITLE
please explain retry tasks reported in workflow timing diagram

### ISSUE THREAD

**Issue by cbirger** [broadinstitute/cromwell#1860] opened 2017-01-17 16:24 UTC
(Note: this is from running workflows on FireCloud, which is currently running Cromwell 21)

We have a task that is filling up its boot disk and presumably failing.  We know how to address this issue.  But, in debugging this issue we observed a couple of things:

1. Cromwell  reports the "failed" task as being in the Running state.  It is clearly "stuck" in this state as there is no activity reported on the log files.
2.  The workflow timing diagram reports the task as being in some kind of retry state: the failed task is VEP, but the workflow timing diagram reports the task as VEP_Task.retry-1.  Does this mean that Cromwell retried this task?  I thought that cromwell only retried tasks that failed due to preemption.

**Comment by Horneth** [comment] 2017-01-17 18:11
Regarding your second point, I believe the `retry-1` is an artifact of the timing diagram, but the task has not been retried. The `1` really means "attempt #1". The timing diagram doesn't display the `retry` bit if a task is successful and its attempt is `1`. In that case it seems Cromwell believes the task to still be running which is why you see `retry-1` on the timing diagram. This is definitely confusing and should be fixed.

For the first point, is it certain that the task actually failed on the JES side ? Can you do a `gcloud alpha genomics operations describe <<operations_id>>` and look at the `done` field ?

**Comment by cbirger** [comment] 2017-01-17 19:23
The done field is false.  BUT, the task is completed.  It looks like the file de-localization is failing.  Here is the output from the `gcloud alpha genomics operations describ <<operations_id>>` command:


wm8b6-23c:~ birger$ gcloud alpha genomics operations describe operations/ELDjidCZKxiM28n8osukousBIN6K28SDHCoPcHJvZHVjdGlvblF1ZXVl
CBB: Python used is /usr/bin/python
done: false
metadata:
  '@type': type.googleapis.com/google.genomics.v1.OperationMetadata
  clientId: ''
  createTime: '2017-01-13T22:46:08Z'
  events:
  - description: start
    startTime: '2017-01-13T22:46:46.694323618Z'
  - description: pulling-image
    startTime: '2017-01-13T22:46:48.680547626Z'
  - description: localizing-files
    startTime: '2017-01-13T22:49:45.125140353Z'
  - description: running-docker
    startTime: '2017-01-13T22:50:40.950396160Z'
  - description: delocalizing-files
    startTime: '2017-01-13T23:00:45.139027328Z'
  - description: copied 0 file(s) to "gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/variant_effect_output.txt"
    startTime: '2017-01-13T23:04:22.693611455Z'
  - description: copied 0 file(s) to "gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/variant_effect_output.txt_summary.html"
    startTime: '2017-01-13T23:08:18.577755879Z'
  - description: copied 0 file(s) to "gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/VEP_Task-rc.txt"
    startTime: '2017-01-13T23:12:21.761179493Z'
  - description: copied 0 file(s) to "gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/dstat.log.txt"
    startTime: '2017-01-13T23:16:37.083751898Z'
  - description: copied 0 file(s) to "gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/df.log.txt"
    startTime: '2017-01-13T23:20:40.785907191Z'
  labels: {}
  projectId: broad-firecloud-benchmark
  request:
    '@type': type.googleapis.com/google.genomics.v1alpha2.RunPipelineRequest
    ephemeralPipeline:
      docker:
        cmd: /bin/bash /cromwell_root/exec.sh
        imageName: broadinstitute/broadmutationcalling_beta:benchmark_1
      inputParameters:
      - name: __extra_config_gcs_path
      - localCopy:
          disk: local-disk
          path: fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-GatherAndOncotate_Task/MuTect1.call_stats.vcf
        name: mutectMergedRawVCF-0
      - localCopy:
          disk: local-disk
          path: firecloud-tcga-open-access/tutorial/reference/my_dot_vep.zip
        name: VEP_File-0
      - localCopy:
          disk: local-disk
          path: exec.sh
        name: exec
      name: CallingGroup_Workflow
      outputParameters:
      - localCopy:
          disk: local-disk
          path: VEP_Task-rc.txt
        name: VEP_Task-rc.txt
      - localCopy:
          disk: local-disk
          path: dstat.log.txt
        name: dstat.log.txt
      - localCopy:
          disk: local-disk
          path: df.log.txt
        name: df.log.txt
      - localCopy:
          disk: local-disk
          path: variant_effect_output.txt
        name: variant_effect_output.txt
      - localCopy:
          disk: local-disk
          path: variant_effect_output.txt_summary.html
        name: variant_effect_output.txt_summary.html
      projectId: broad-firecloud-benchmark
      resources:
        bootDiskSizeGb: 10
        disks:
        - mountPoint: /cromwell_root
          name: local-disk
          sizeGb: 31
          type: PERSISTENT_HDD
        minimumCpuCores: 1
        minimumRamGb: 7
        zones:
        - us-central1-b
        - us-central1-c
        - us-central1-f
    pipelineArgs:
      clientId: ''
      inputs:
        VEP_File-0: gs://firecloud-tcga-open-access/tutorial/reference/my_dot_vep.zip
        __extra_config_gcs_path: gs://cromwell-auth-broad-firecloud-benchmark/04b3f189-18f3-47b3-972c-0e59d2a56174_auth.json
        exec: gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/exec.sh
        mutectMergedRawVCF-0: gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-GatherAndOncotate_Task/MuTect1.call_stats.vcf
      labels: {}
      logging:
        gcsPath: gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/VEP_Task.log
      outputs:
        VEP_Task-rc.txt: gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/VEP_Task-rc.txt
        df.log.txt: gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/df.log.txt
        dstat.log.txt: gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/dstat.log.txt
        variant_effect_output.txt: gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/variant_effect_output.txt
        variant_effect_output.txt_summary.html: gs://fc-58202a28-b82d-49da-a226-b9e14cf3c995/3a64e707-2544-409b-8a56-9a888840045d/CallingGroup_Workflow/04b3f189-18f3-47b3-972c-0e59d2a56174/call-VEP_Task/variant_effect_output.txt_summary.html
      projectId: broad-firecloud-benchmark
      resources:
        bootDiskSizeGb: 0
        disks: []
        minimumCpuCores: 0
        minimumRamGb: 0
        noAddress: false
        preemptible: false
        zones: []
      serviceAccount:
        email: default
        scopes:
        - https://www.googleapis.com/auth/genomics
        - https://www.googleapis.com/auth/compute
  runtimeMetadata:
    '@type': type.googleapis.com/google.genomics.v1alpha2.RuntimeMetadata
    computeEngine:
      diskNames:
      - local-disk-16952835813372226956
      instanceName: ggp-16952835813372226956
      machineType: us-central1-b/n1-standard-2
      zone: us-central1-b
  startTime: '2017-01-13T22:46:12Z'
name: operations/ELDjidCZKxiM28n8osukousBIN6K28SDHCoPcHJvZHVjdGlvblF1ZXVl
wm8b6-23c:

**Comment by geoffjentry** [comment] 2017-01-17 19:51
@cbirger re the failed & running, I believe what you are referring to ties to #1861

**Comment by Horneth** [comment] 2017-01-18 03:58
@geoffjentry Although if the Jes metadata says the job isn't done, even if Cromwell is still tracking it, it will stay in Running state until JES says otherwise. This looks like it might be a JES issue.

**Comment by geoffjentry** [comment] 2017-01-18 04:17
Good point. At the time I was thinking that Alex's issue was due to this umbrella issue but he later confirmed they weren't related and I forgot I posted that until just now :)

**Comment by geoffjentry** [comment] 2017-01-22 18:56
@cbirger Did this get fully discussed at office hours last week?

**Comment by cbirger** [comment] 2017-01-23 13:53
I got some clarification.  

@ruchim showed me how to use the API to get preemption data.

However, using that API I looked for evidence of preemption in four submissions, each launching 1000 workflows, and each workflow conducting a 25-way scatter.  All of these scatter jobs are set to run on preemptiible VMs.  So that is 4 X 1000 X 25 = 100K jobs run on preemptible machines.  Each job takes between 30 minutes and an hour to run.  I saw no reported incidents of preemption.  I'm not sure that I believe this is the case, and am wondering if either I'm access the preemption data incorrectly, or if cromwell is not reporting is correctly.

**Comment by geoffjentry** [comment] 2017-01-23 19:17
Hi @cbirger - Gotcha. That sounds separate from this issue so I'm going to close this one. As I've been catching up today it sounds like @vdauwera has answered these questions over in the Workbench forum for you. In general though preemption can be a fickle beast, it's not unheard of to see more/less preemptions than expected.

**Closed by geoffjentry** 2017-01-23 19:18 UTC
