### ISSUE TITLE
Call Caching hit 503 Service Unavailable error

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#1185] opened 2016-07-19 20:24 UTC
When getting call cache hits for a large (900+) amount of jobs, there is a highish likelihood that one of the call cache hits will fail with a 503 error when trying to copy the outputs from the cached call.  The error looks like:

```
2016-07-17 18:31:09,715 cromwell-system-akka.actor.default-dispatcher-153 ERROR - JesBackend [UUID(14410fce):GenotypeFilterAndMakeSitesOnlyVcf:1]: Exception occurred while attempting to copy outputs from gs://broad-gotc-dev-cromwell-execution/JointGenotyping/e71eba09-ef37-4cda-a89e-b0c4398fcc35/call-GenotypeFilterAndMakeSitesOnlyVcf/shard-1 to gs://broad-gotc-dev-cromwell-execution/JointGenotyping/14410fce-5b88-4166-b21b-e33a1e02911f/call-GenotypeFilterAndMakeSitesOnlyVcf/shard-1
com.google.api.client.googleapis.json.GoogleJsonResponseException: 503 Service Unavailable
{
  "code" : 503,
  "errors" : [ {
    "domain" : "global",
    "message" : "Backend Error",
    "reason" : "backendError"
  } ],
  "message" : "Backend Error"
}
```

**Comment by mcovarr** [comment] 2017-01-03 16:30
Is this a duplicate of #794?

**Comment by cjllanwarne** [comment] 2017-01-31 20:37
Closing as "believed fixed"

**Closed by cjllanwarne** 2017-01-31 20:37 UTC
Labels: GreenFriends, Q4_2016, UserSupport ❤️
