### ISSUE TITLE
Investigate: Call Caching updates original workflow metadata for start/end time

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4141] opened 2018-09-24 17:54 UTC
From user reports, this is upsetting cost estimation (and is scary anyway wrt re-writing history!

Needs validation and a reproducible case, but presumably something like:

- Run a long workflow, one shard fails
- Re-run the same workflow, most shard call cache
- The shards in the original workflow get updated to have the call-cache timings, rather than the original long timings.

**Comment by Horneth** [comment] 2018-09-24 20:06
Which version of cromwell are we talking about ? FC ?

**Comment by Horneth** [comment] 2018-09-24 20:33
I could not reproduce this after a quick test on develop. 

Running 

```wdl
version 1.0

task long_running {
    input {
        Int i
    }
    command {
        if [ ~{i} -eq 5 ]; then exit 1; fi
        sleep 60
    }
    runtime {
        docker: "ubuntu@sha256:de774a3145f7ca4f0bd144c7d4ffb2931e06634f11529653b23eba85aef8e378"
    }
}

workflow weird_metadata_overwriting {
    scatter (i in range(10)) {
        call long_running { input: i = i }
    }
}
```

twice didn't affect the metadata of my first run. Am I misinterpreting the test case description ?

**Comment by SHuang-Broad** [comment] 2018-09-25 21:00
I suspect that I can share the data here, but I can provide links to what actually happened

The execution buckets are [here](https://console.cloud.google.com/storage/browser/broad-dsde-methods/cromwell-execution-34/PindelSmallVariants/?project=broad-dsde-methods&organizationId=548622027621), and the Cromwell sever I used is the DSDE methods V.34.

There are two occasions/samples that I am seeing this behavior,

for sample one: the 1st run has workflow ID `324938cb-ca12-4573-999c-9ac1d13ba22b`, and the 2nd run has workflow ID `710a663d-1c28-49ef-884f-312bcceaa6f1` (this is currently still running).

for sample two: the 1st run has workflow ID `fe30d8cd-4995-4230-a3d3-5b1542b94273`, and the 2nd run has workflow ID `40cfd6c2-1a1a-4358-b23e-b49de74643b6` (both finished now for this sample).

I'm attaching the metadata for the three workflows that finished successfully.
[metadata.zip](https://github.com/broadinstitute/cromwell/files/2417048/metadata.zip)

**Comment by geoffjentry** [comment] 2018-11-15 19:42
@SHuang-Broad Hi Steve - we haven't been able to reproduce this. Do you have a reproducible example we could use here? I'll close this ticket for now, if you can find a reproducible example we'll reopen

**Closed by geoffjentry** 2018-11-15 19:42 UTC
Labels: 🐛Bug
