### ISSUE TITLE
All workflow tasks should be monitored until they reach a final state

### ISSUE THREAD

**Issue by abaumann** [broadinstitute/cromwell#1861] opened 2017-01-17 19:23 UTC
Right now if a workflow fails and Cromwell is in fail fast mode, the workflow gets marked as failed and monitoring stops.  What this means is if one task fails, but another is "Running", that other task will always be in a "Running" state.  This leads to many user questions (e.g. "Is this still running and costing me money?").  

Every task should be monitored to its final state rather than only workflows.

**Comment by katevoss** [comment] 2017-03-31 15:14
@abaumann is the issue that Cromwell doesn't update the state of the "Running" task, which has failed (or stopped), or that it keeps running that task, which should have failed (or stopped)?

**Comment by katevoss** [comment] 2017-03-31 17:12
@cjllanwarne do you know if this has been fixed?

**Comment by Horneth** [comment] 2017-03-31 17:15
This hasn't ben fixed

**Comment by knoblett** [comment] 2017-06-15 15:20
Another user encountered this issue [here](http://gatkforums.broadinstitute.org/firecloud/discussion/9786/workflow-was-marked-as-failed-but-many-tasks-continued-to-run-after-that). @katevoss Is there any plan to prioritize this bug fix soon? I'm not fully aware of what bugs you have to tackle at the moment.

**Comment by abaumann** [comment] 2017-06-15 15:23
Sorry @katevoss I didn't answer this before - it's the issue that the workflow fails because we are in fail fast state, but the calls inside that workflow don't get updated - so you can get a workflow that says "Failed" with a bunch of tasks that say "Running", which is confusing to users and they often ask if they are still running or not (the answer is that they are until they get to a final state, but no subsequent parts of the workflow continue after that point)

**Comment by knoblett** [comment] 2017-06-15 17:01
This bug is blocking Cromwell's ability to call cache, due to the fact that Cromwell won't pull "Running" calls as "Succeeded" ones. This would be very helpful to fix soon.

**Comment by katevoss** [comment] 2017-06-29 06:03
@danbillings if you could get a chance to look at this in your bug rotation that would be great, sounds like a high priority for FC.

**Comment by danbills** [comment] 2017-06-29 12:30
@katevoss Roger will start today

**Comment by katevoss** [comment] 2017-09-07 21:46
@knoblett is this still blocking Cromwell's call caching because calls aren't updated as succeeded? I haven't heard this come up in a while.

**Comment by bradtaylor** [comment] 2017-10-04 20:49
Hi Guys, we're getting more heat on this issue in firecloud. See:
https://gatkforums.broadinstitute.org/firecloud/discussion/comment/42587#Comment_42587

@katevoss FYI

**Comment by katevoss** [comment] 2017-10-05 14:13
@bradtaylor is this blocking people from running workflows? How often is it occurring? Is there a workaround?

@geoffjentry or @kshakir (our current bug rotator), do you have an idea of the effort to fix this?

**Comment by abaumann** [comment] 2017-10-05 14:17
just want to also be sure to make it clear there are more issues related to that forum post than this specific issue - this one is on making sure the task statuses reach a final state when the workflow ends in a terminal state - that's different than aborts not working - both are an issue, but different

**Comment by abaumann** [comment] 2017-10-05 14:22
I don't think these issues block anybody - they just lead to constant questions and give a bad impression of our reliability.  People are often worried they are still spending money because it looks that way.

I could do a query to probably find how often aborts don't work if that helps.  

There isn't a workaround to either issue - only that we tell users it's ok after we dig in to find out that it is and they just deal with the inconsistency.

**Comment by Horneth** [comment] 2017-10-05 14:42
Even though it's not technically the same, we talked about `ContinueWhilePossible` as a possible temporary workaround for this. Has it been rejected since ?

**Comment by abaumann** [comment] 2017-10-05 14:52
right now that's not the default in FC, nor do we expose it in the UI - people have used it and it does help for some circumstances where you need it, but it seems like overkill when all you want is reliable statuses.  it also won't help with the aborting issue which is what the gatk post was

**Comment by katevoss** [comment] 2017-10-05 15:22
@bradtaylor can you clarify which issue is more concerning? Is it the aborting issue or the status updating?

**Comment by kshakir** [comment] 2017-10-05 16:46
May also be the cause of / related to https://github.com/broadinstitute/cromwell/issues/2526

**Comment by kshakir** [comment] 2017-10-05 16:56
There are two tables in the cromwell database that are out of sync. Unofficially, if one knows what they're looking for, one can edit the values directly in the database. Often the case is the `WorkflowStoreEntry` doesn't have a record for the workflow, thus it cannot be aborted or resumed-on-restart, yet the last row in `MetadataEntry` says the workflow is still `Running`.

A "reconciler" could write a final row into `MetadataEntry` with Aborted/Success/Fail. This could be called:
- Manually by a user/service
- Automatically whenever a user requests status of a workflow
- Automatically by a MetadataEntry sweeper looking for workflows w/o a finalization and no row in WorkflowStoreEntry
- Other?

**Comment by tmm211** [comment] 2017-10-06 20:33
This was reported by another [FireCloud user](https://gatkforums.broadinstitute.org/firecloud/discussion/10352/removing-workflows-stuck-in-the-submitted-or-aborting-state#latest)
Is there a way that we can force these jobs into Aborted so that the workspace stops appearing as "Running"

**Comment by abaumann** [comment] 2017-10-06 20:52
Yes we can update the database manually but I hesitate to do that unless it's really serious.  Since this specific ticket is not about aborts, should this be moved to a ticket about aborts?

**Comment by tmm211** [comment] 2017-10-10 16:48
Sure. What's the ticket number? The issue this user posted is about both submitted workflows and aborted workflows getting stuck. I asked him/her to abort the submitted ones so that the workspace would stop showing as Running, but that didn't work. Can we confirm that they aren't getting charged for machines not aborting that they have requested to abort?

**Comment by abaumann** [comment] 2017-10-10 17:39
Don't know the ticket for aborts - but yes we can confirm individual submissions/workflows, however it's tedious process and you need an admin to do it.  Almost every time I've checked it's just a matter of statuses being incorrect and not that the machine is still running

**Comment by Horneth** [comment] 2017-11-07 19:04
Fixed by https://github.com/broadinstitute/cromwell/pull/2808

**Closed by Horneth** 2017-11-07 19:04 UTC
Labels: Fire Friends, PO Cleanup, User Requested Improvement
