### ISSUE TITLE
Custom retry strategies

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#1847] opened 2017-01-12 16:07 UTC
A significant amount of GotC failures are due to out of memory / disk errors.
Design a mechanism that allow to specify custom retry strategies that can modify runtime parameters based on failure modes.

For example, “Retry on return code X with double the amount of memory and / or disk”.

Thoughts:
- `currentAttempt()` wdl function to be used as a variable in a memory / disk formula
- monitor the job (monitoring script ?) to detect disk / memory overflows.

**Comment by geoffjentry** [comment] 2017-03-09 15:46
This is basically a dupe of #1991, closing.

**Closed by geoffjentry** 2017-03-09 15:46 UTC
Labels: Retry
