### ISSUE TITLE
The JES polling actor unexpectedly terminated while conducting polls. Making a new one...

### ISSUE THREAD

**Issue by seandavi** [broadinstitute/cromwell#1665] opened 2016-11-12 02:32 UTC
I was running Cromwell with a JES backend.  I got through about 300 out of 1000 workflows that were submitted as a batch; the rest are still listed as `Running`.  Oddly, the genomics API operations report that they are still running though there are no instances still up.  I am not sure if this is a Cromwell issue or a Google one, but here is what I am seeing from Cromwell.   Cromwell has been working well for smaller batches.  Any thoughts? 

Thanks!

```
[ERROR] [11/12/2016 02:22:12.170] [cromwell-system-akka.actor.default-dispatcher-2686] [akka://cromwell-system/user/cromwell-service/$b/$a] The JES polling actor Actor[akka://cromwell-system/user/cromwell-service/$b/$a/$8#-1275882726] unexpectedly terminated while conducting 11 polls. Making a new one...
[INFO] [11/12/2016 02:22:12.170] [cromwell-system-akka.actor.default-dispatcher-2686] [akka://cromwell-system/user/cromwell-service/$b/$a] watching Actor[akka://cromwell-system/user/cromwell-service/$b/$a/$9#-1852863496]
[WARN] [11/12/2016 02:22:12.171] [cromwell-system-akka.dispatchers.backend-dispatcher-2573] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor/WorkflowActor-7f0d7c16-d434-4dd7-a7ba-c7e897701c9a/WorkflowExecutionActor-7f0d7c16-d434-4dd7-a7ba-c7e897701c9a/7f0d7c16-d434-4dd7-a7ba-c7e897701c9a-EngineJobExecutionActor-salmonRun.salmonQuant:NA:1/7f0d7c16-d434-4dd7-a7ba-c7e897701c9a-BackendJobExecutionActor-7f0d7c16:salmonRun.salmonQuant:-1:1/JesAsyncBackendJobExecutionActor] JesAsyncBackendJobExecutionActor [UUID(7f0d7c16)salmonRun.salmonQuant:NA:1]: Caught exception, retrying:
java.lang.RuntimeException: Unexpected actor death!
	at cromwell.backend.impl.jes.statuspolling.JesPollingActorClient$$anonfun$pollingActorClientReceive$1.applyOrElse(JesPollingActorClient.scala:33)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.aroundReceive(JesAsyncBackendJobExecutionActor.scala:82)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by geoffjentry** [comment] 2016-11-12 03:00
I'm pretty sure what you're seeing is "let it crash" (a design principal for actor based systems) in action and isn't an issue. I was just thinking a few hours ago that I should make that logging less frightening. It's on my todo list to verify that my first statement is actually true. Now I don't need to make an issue for it :)

**Comment by geoffjentry** [comment] 2016-11-12 03:02
Actually I realized I didn't read your text, I just saw the exception and it was already what was on my mind.

What do you mean by there are no instances left up?

**Comment by seandavi** [comment] 2016-11-12 12:44
I was able to track partway back on the Google side of things.  In short, Cromwell reported jobs in the "Running" state.  These were associated with Google Genomics API operations, also listed as "Running".  However, the instances that were supposed to be associated with those GG operations were not alive.  I noticed in my billing statement that there were credits to offset compute instances, so I suspect that something happened at Google that was unexpected.  I'll dig a bit further.  

In the meantime, it would definitely help to have a way to differentiate exceptions that are "expected" from those that are not.  In this case, I assumed that a restart of a service after an exception was probably OK, but it was associated with "dead" jobs that now appear to have been on the google side of things and not with Cromwell directly.  I'll follow up with whatever else I can learn.

**Comment by geoffjentry** [comment] 2016-11-12 15:16
Hmm, that's interesting on the google side. So I'm clear you're saying that Cromwell is showing Running when they were not in Google? If so, how long did that stay the case - was it in perpetuity? I ask because as the number of jobs increases the average latency between a state change on Google's side and Cromwell detecting it increases due to QPS limitations. We're always trying to work with them to find ways to make that faster but we're limited on how many things we can query about at once, so we round robin them through. As an example the other day I submitted 200k single call workflows which each only slept for a couple of seconds but it took upwards of an hour for Cromwell to know that everything was complete due to that.

I'm still going to look into the root cause of the exceptions you saw, i've been seeing those a lot myself (but had reason to believe it was an artifact of my not-at-all-standard setup, glad you chimed in to fix that for me) and wanted to make sure they weren't masking something more fundamentally wrong.

re the logging aspect, I agree completely - this has always been an issue and is growing the more the people start adopting Cromwell. I found it amusing that just hours prior I said I should change that one to be less frightening and then it frightened someone ;) In general I think that logging is always a a dark art but answering the "who is the log for?" is even harder here as we intentionally designed cromwell to satisfy multiple use cases all of whom have different things they want to see. It's something that we're looking to work on over the next several months.

**Comment by geoffjentry** [comment] 2016-11-12 15:16
Tagging @cjllanwarne in case he has thoughts

**Comment by seandavi** [comment] 2016-11-12 19:18
I dropped a [question into the Google Genomics google group](https://groups.google.com/forum/#!topic/google-genomics-discuss/OL18jPoPvPE) about the "stuck" Google Genomics Pipeline operations.

**Comment by pgrosu** [comment] 2016-11-13 21:25
Hi Jeff,

You've built this great Actor system, but it needs to be actors on both ends.  The round-robin pool of actors is not an actor system anymore if you cannot pass a Promise/Future/ActorRef to the other side, even if the API/channel capacity is limited.  The status response should happen in less than a second, not an hour.  We both know that we can have [millions of Actors in Akka/Scala](http://doc.akka.io/docs/akka/snapshot/general/actor-systems.html#What_you_should_not_concern_yourself_with), and the throughput on the Google network is huge.  Thus no API limits should be prohibitive.

I suggested using Pub/Sub API here:

https://github.com/broadinstitute/cromwell/issues/1089#issuecomment-229703152

And if that's not an option, you can implement the whole Google Genomics Pipeline API super-easy as an ephemeral GCE instance, which really is just becomes a promise/future.  I even broke it down in a [post here](
https://groups.google.com/forum/#!topic/google-genomics-discuss/_ox9h-C0_50), specifically in the paragraph that starts with **_So you might ask what exactly is an Operation resource_**:

https://groups.google.com/forum/#!topic/google-genomics-discuss/_ox9h-C0_50

You know my philosophy, always build it yourself to bypass any limitations :)

`p

**Comment by kcibul** [comment] 2016-11-13 22:03
Thanks for the comment Paul -- we've already started those discussions with the Google folks.  We want this built deep into the Pipelines API as true notifications via pubsub which seems a reasonable feature.  It's possible to do what you say yourself (using a GCE node(s) to query and then post) but with 100,000s of operations in flight it's much more efficient to be notified than poll... but I'm sure you agree with that ;)

**Comment by pgrosu** [comment] 2016-11-14 08:51
Hi Kris,

Of course, I totally agree with the notification approach as things scale up ;)  Though the issue might be when you get into millions/billions of operations later on, then there are some things that would need to be tweaked for that.  As the number of operations scale up, the logging could then also become a bottleneck, as those are also API requests - besides the ones coming from the Pipeline API - and usually is a positive multiplier greater than 1 of the number of operations, with their own Retry requests.  I think you'll agree that it's usually better to be more modular, so that things can easily be tweaked and updated over time - such as the transition to Pluggable Backends, but in this case for the Pipeline API directly.

I agree with the capability of having fine-grained informational log events, though Pub/Sub API has certain limitations to be aware of:

https://cloud.google.com/pubsub/quotas#other_limits

Don't get me wrong, I'm still excited to see how version 2.0 of the Pipeline API evolves, but there are some tricky scalability issues that might emerge which could make the Cromwell code unnecessarily complex down the line, if one has to work through too many limitations/edge-cases.

Paul

**Comment by seandavi** [comment] 2016-11-14 22:10
Just a note that the second part of my issue was about operations stuck in the "Running" state.  It turns out that was a Google bug that has now been fixed.

**Comment by geoffjentry** [comment] 2016-11-15 02:20
@seandavi Thanks. One could say though that we're not adhering to one of the tenets of distributed computing which is to make sure everything you do has some reasonable timeout where you give up and assume its dead :)

**Comment by seandavi** [comment] 2016-11-15 02:24
There is a second issue that came up after Google fixed the first issue that is oddly ironic given your comment.  If they hit API quotas, it appears that they were immediately failing the operations, leading to some odd error messages passed through to Cromwell (and then to me).  In a sense, they were failing too quickly.  Tough balancing act, it seems.

**Comment by pgrosu** [comment] 2016-11-15 03:01
Hi Sean,

Yeah I noticed that, and glad that it is in the process of getting fixed.  Though this is precisely why we must have more control over the whole process, as creation of instances are basically just a cascade events which get tied to an **Operation**, through which you can interface with the VMs that are building or running.  I have fairly high confidence that this is basically what is happening underneath the Google service endpoint when performing a [**RunPipelineRequest**](https://github.com/googleapis/googleapis/blob/c4899b3f0cef2caa73bb1a32baf00f54c8a49921/google/genomics/v1alpha2/pipelines.proto#L51-L53) through the [Pipeline API here](https://github.com/googleapis/googleapis/blob/c4899b3f0cef2caa73bb1a32baf00f54c8a49921/google/genomics/v1alpha2/pipelines.proto#L51-L53):

```
  rpc RunPipeline(RunPipelineRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = { post: "/v1alpha2/pipelines:run" body: "*" };
  }
```

If you think of this as a graph of best-effort networked dependent triggers via APIs, you can stabilize this to make it more predictable and scalable.  It is just too obvious that we can collectively definitely make this better at this stage - as we already have the tools - and especially since we'll soon have nested workflows via https://github.com/broadinstitute/cromwell/issues/1532, which should be assumed to make the the current number of operations in flight grow by several orders of magnitude.

~p

**Comment by geoffjentry** [comment] 2016-11-15 13:43
@seandavi What are you seeing on the quota failures? We should be robust to that and putting things back in the to-retry pool, while our quotas are jacked pretty high we run into this as well for our larger stuff, so that's something we've needed to work around ourselves.

**Comment by seandavi** [comment] 2016-11-15 13:47
Thanks, @geoffjentry.  The quota failures were on the JES side, I think, and were reported back to Cromwell; I'm not sure how you would be able to detect a failure of one type versus another.  Probably good to follow the conversation [here](https://groups.google.com/forum/#!topic/google-genomics-discuss/OL18jPoPvPE), as it sounds like Google is still sorting out a few things.

**Comment by geoffjentry** [comment] 2016-11-15 13:47
@pgrosu I can assure you that nobody would like to see cromwell have the ability to scale to infinity and beyond on any arbitrary backend more than I :) OTOH I need to empower people to at least crawl prior to building out the running capability. Could we put together something which would provide better scalability for our purposes? Probably. However they have people who know this stuff a lot better than I do and we've got many other things on the todo list so for now the best course of action appears to be working w/ them to help parallelize our efforts.

**Comment by geoffjentry** [comment] 2016-11-15 13:48
@seandavi Gotcha, this might be another case of "frightening log message" if you were detecting it via cromwell, although IIRC we squelched those specifically as they were too spammy.

**Comment by seandavi** [comment] 2016-11-15 13:50
@geoffjentry, these were real failures. The jobs were marked by JES as failures, so Cromwell (correctly) did not attempt to retry.

**Comment by geoffjentry** [comment] 2016-11-15 13:52
@seandavi Yeah, was just reading the thread. That's something different than what I was picturing when I saw quota failures. I'll look into it a bit.

**Comment by pgrosu** [comment] 2016-11-15 18:08
@geoffjentry  I agree with crawling before running, and have definitely seen how busy you are through the evolution of Cromwell over the years, which will always be appreciated.  I do not disagree that the Google folks understand how to parallelize their products/services, but that does not mean they are the only ones to understand the concepts and how to actually implement it.  I agree it is not an overnight thing, as it took me many years to put the pieces together.

I think by opening these discussions with the larger Community here, you might be surprised how many more people can help you and your team out.  Vetting design decisions from the todo list before they approach an implementation stage, can sometimes streamline and simplify multiple requests from the list.  I understand that Cromwell is a mix of features to satisfy sometimes users' legacy preferences, but if an implemented backend of Cromwell has the capability to scale in such a way as to become a paradigm shift in the way one does analysis, I am sure users would welcome that.  Again I do not disagree with crawling, though I feel the Community would welcome the opportunity to help pave paths with the transition to running :)

**Comment by geoffjentry** [comment] 2016-11-17 21:40
@seandavi PR #1686 should take care of things on our end once it's merged. On our google call Melissa did address your issue and said it should be fixed promptly. Apparently it was also affecting our production stuff.

@pgrosu Just wanted to make sure you didn't take what I said as defensiveness or a "stay away". I definitely do watch all of the suggestions out there, I just am not capable of acting on everything directly :)

**Comment by pgrosu** [comment] 2016-11-19 02:42
@geoffjentry  Absolutely no worries, I totally understand but it is a bit weird to be aware of the concepts behind the following fault-tolerant scalable analysis pipelines and other distributed algorithms - which I'm sure you and many people are - and still be noticing that you have to deal with [20000 scatter/gather jobs](https://github.com/broadinstitute/cromwell/issues/1662) that might be causing issues when producing 10% of the world's genomic data:

* [Google's Continuous Pipelines at Google](http://research.google.com/pubs/pub43790.html)
* [Facebook's Real-Time Data Processing Pipelines](https://research.facebook.com/publications/realtime-data-processing-at-facebook/)
* [Microsoft's Whole-Exome Workflows](https://www.microsoft.com/en-us/research/publication/scalable-and-efficient-whole-exome-data-processing-using-workflows-on-the-cloud/)

Maybe it's my passion for high-throughput data integration, and knowing the potential of pipelined analysis that is achievable today through streamlined fault-tolerant scaling.  I'm sure the Broad is already aware of these, as some of the fundamental scalability concepts have and are being implemented in [Hail](https://github.com/hail-is/hail).  At least I'm comforted that you watch all the suggestions, and maybe in the future this might provide some helpful support :)

**Comment by geoffjentry** [comment] 2016-11-20 16:00
@pgrosu Thanks for reminding me about that ticket - there's definitely a bug somewhere but I think it's an artifact of using mock-jes and I was never able to replicate it so it's hard to say what was going on. What I saw in the database *should* be impossible to have achieved, joy ;)

I'm definitely aware of this sort of stuff, if our goal was pure scale you'd see a pretty different design to things. The goal is to be flexible enough to respond to scale demands as they increase. To date the folks that set our priorities for us have consistently set the bar for scale to be just enough to manage what we need to handle internally - as you note this means there's always more to squeeze out. 

At the moment the plan is to loop back to scaling in the next quarter, but we're still talking about what we project for Broad's sequencing production (which really means "how big of a joint genotyping run does daniel macarthur want to run this time?") and a projection of firecloud usage for a relatively near-mid term horizon.

**Comment by pgrosu** [comment] 2016-11-22 02:28
@geoffjentry  Yeah, I have also hit my share of obscure errors, though by that time the failure-recovery rules usually kicked in to keep the system in a running state, with the periodic subsequent log monitoring and analysis in case certain edge-cases become more prevalent.

It is great to hear about the shift towards scaling being explored for the near future, but I think you might have made things unnecessarily hard for yourself.  Usually it is much easier to have scaling be built-in from the start into the application, and then tuning through metric-based scaling policies the application-triggered scaling rules, which can be bounded by appropriate upper limits before, or interactively after application deployment.  This way one has the benefits of both worlds - controlling costs with scalability capabilities for satisfying possible capacity/performance requirements - but I am sure you are already aware of that as well :)

**Comment by kcibul** [comment] 2016-11-22 02:39
Hi @pgrosu -- we're very glad to have you involved in the Cromwell community, sharing ideas and helping make a better product!  I think it might be time to move this thread out of this github issue (which will eventually be closed!) and into another forum.  Maybe email, or the Gitter channel.

Thanks again

**Comment by seandavi** [comment] 2016-11-22 03:12
Given that the critical portion of this issue was related to a google bug that has been resolved, I'm happy to close the issue. The original report was about the "unexpected actor death" log message, but that turned out to be a red herring relative to the underlying google bug.  @geoffjentry, I'll leave it up to you as to whether leaving this issue open serves a purpose to you, but my original problem is solved, I believe.

**Comment by pgrosu** [comment] 2016-11-22 03:14
@kcibul  Gladly and feel free to place it where you think it might be most appropriate.   Though probably keeping it here on Github might make it easier to search for during future discussions of new design decisions, when there might be a need to refer to it for possible implementation ideas, otherwise it might get lost.

Thank you again for the fruitful discussion, which I found very helpful.

Paul

**Comment by kcibul** [comment] 2016-11-22 14:25
Great -- I'll close this since Sean is ok.  I didn't mean that I would move this contents of conversation elsewhere... just that if it were to continue that we should probably have it elsewhere ;)

**Closed by kcibul** 2016-11-22 14:25 UTC
