### ISSUE TITLE
Cromwell reports SUCCESS for task that should have produced file output but actually did not

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/cromwell#4147] opened 2018-09-25 20:09 UTC
Hi, 

I'm reporting a behavior that is strange to me:
If a task declares it is going to output some files in the `output` block, but the `command` block doesn't actually do that (i.e. produce those files), Cromwell will mark that as SUCCESS, and delocalize what ever is produced by the command.

-----------
Expected behavior:

The job should fail.

-----------
Actually happen:

The job is marked `Success`.

-----------

the backend is the methods cromwell server v 34, the actual workflow-ID is 
`17faf5b5-be67-4756-b168-130450081cfb`
The bucket is here:
`gs://broad-dsde-methods/cromwell-execution-34/TestOutputMultipleFiles/17faf5b5-be67-4756-b168-130450081cfb/call-PrintsToFileTest`

JSON input

```json
{
  "TestOutputMultipleFiles.dummy_array": ["chr1", "chr2"]
}

```
And the WDL script
```wdl
workflow TestOutputMultipleFiles {

  Array[String] dummy_array

  scatter (ele in dummy_array) {
    call PrintsToFile as PrintsToFileTest {
      input:
      out_prefix = ele,
      to_print = ele
    }
  }

  output {
    Array[Array[File]] matrix = [PrintsToFileTest.out_txt, 
                                 PrintsToFileTest.out_md]
  }
}

task PrintsToFile {

  String out_prefix
  String to_print

  command {
    touch ${out_prefix}.txt
    echo "${to_print}" > ${out_prefix}.txt
    # delibrately forgetting to generate a file, so cromwell should capture that and report failure
    # touch ${out_prefix}.md
    # echo "${to_print}" > ${out_prefix}.md
  }

  runtime {
    docker: "ubuntu:trusty"
    disks: "local-disk " + "10" + " HDD"
    cpu: "1"
    preemptible: 1
  }

  output {
    File out_txt = "${out_prefix}.txt"
    File out_md = "${out_prefix}.md"
  }
}

```

-------------

If the workflow has multiple tasks, and downstream tasks depends on (i.e. File input) upstream task that should have produced the file as output, previously the workflow would fail, now the workflow just hangs there

Example (ID: 55f8ac4e-a6e1-4b1f-9086-f6d04fec5bb8, location: `gs://broad-dsde-methods/cromwell-execution-34/TestMultiStage/55f8ac4e-a6e1-4b1f-9086-f6d04fec5bb8`)

some json input content, WDL below:

```wdl
workflow TestMultiStage {

  Array[String] dummy_array

  scatter (ele in dummy_array) {
    call PrintsToFile as UpstreamPrintToFile {
      input:
      out_prefix = ele,
      to_print = ele
    }

    output {
        UpstreamPrintToFile.out_txt
        UpstreamPrintToFile.out_md
    }
  }

  call DownstreamConsumer {
    input:
    txt_array = UpstreamPrintToFile.out_txt,
    md_array = UpstreamPrintToFile.out_md
  }

  output {
    File merged_txt = DownstreamConsumer.cat_txt
    File merged_md = DownstreamConsumer.cat_md
  }
}

# upstream task that supposed to be producing 2 out files
task PrintsToFile {

  String out_prefix
  String to_print

  command {
    touch ${out_prefix}.txt
    echo "${to_print}" > ${out_prefix}.txt
    # delibrately forgetting to generate a file, so cromwell should capture that and report failure
    # touch ${out_prefix}.md
    # echo "${to_print}" > ${out_prefix}.md
  }

  runtime {
    docker: "ubuntu:trusty"
    disks: "local-disk " + "10" + " HDD"
    cpu: "1"
    preemptible: 1
  }

  output {
    File out_txt = "${out_prefix}.txt"
    File out_md = "${out_prefix}.md"
  }
}

# downstream task that depends on upstream task outputing all files
task DownstreamConsumer {
  Array[File] txt_array
  Array[File] md_array

  command {
    cat ${sep=" "} txt_array > merged.txt
    cat ${sep=" "} md_array > merged.md
  }

  runtime {
    docker: "ubuntu:trusty"
    disks: "local-disk " + "50" + " HDD"
    cpu: "1"
    preemptible: 1
  }

  output {
    File cat_txt = "merged.txt"
    File cat_md = "merged.md"
  }
}
```

**Comment by SHuang-Broad** [comment] 2018-09-25 20:10
Thanks to @cjllanwarne for helping me with this.

**Comment by SHuang-Broad** [comment] 2018-09-25 20:11
A screenshot showing the overhang issue
![screen shot 2018-09-25 at 4 10 37 pm](https://user-images.githubusercontent.com/16310888/46040199-a4ccf100-c0dd-11e8-9e33-7a032144e7eb.png)

**Comment by ruchim** [comment] 2018-09-27 03:27
@SHuang-Broad I just realized this is a duplicate of https://github.com/broadinstitute/cromwell/issues/4140

criteria #3 in that ticket states a job should be failed if any expected output file fails to delocalize, which is the behavior you're also requesting.

**Closed by ruchim** 2018-09-27 03:27 UTC
Labels: PAPI v2 Blocker, 🐛Bug
